### ISSUE TITLE
ureteric bud synonyms

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#1034]
Please add the following terms as synonyms for ureteric bud

SYN: metanephrogenic diverticulum
SYN: mesonephric diverticulum \(i.e diverticulum arising from the mesonephric duct\)

Apply to all ureteric bud subterms

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/1034](https://sourceforge.net/p/obo/mammalian-phenotype-requests/1034)

**Comment by sbello** [comment]
added term:
MP:0020343 abnormal ureteric bud number
