### ISSUE TITLE
abnormal induced morbidity/mortality

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#1079]
I am using abnormal induced morbidity/mortality \(MP:0001657\) for a phenotype of "poor survival after 30 minutes of ischemia while a 70% hepatectomy is performed."  None of the children of this term are satisfactory.  Perhaps this is the correct place for this annotation but the term definition makes me a little uneasy.  Could we use a specifc term such as "poor survival of surgical intervention"?

Reported by: hdene

Original Ticket: [obo/mammalian-phenotype-requests/1079](https://sourceforge.net/p/obo/mammalian-phenotype-requests/1079)

**Comment by sbello** [comment]
Some annotations have been made to abnormal response to injury (MP:0005164) and children of this term. Added term 'abnormal susceptibility to injury induced morbidity/mortality' (MP:0020344). I don't think we need to create children of this term currently.
