### ISSUE TITLE
classes with no definitions

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#1148]
Classes with no definition

MP:0001186
MP:0001820
MP:0002006
MP:0002873
MP:0004050
MP:0004051
MP:0004052
MP:0005367
MP:0005369
MP:0005370
MP:0005371
MP:0005376
MP:0005377
MP:0005378
MP:0005379
MP:0005380
MP:0005381
MP:0005382
MP:0005384
MP:0005387
MP:0005388
MP:0005389
MP:0005390
MP:0005391
MP:0005394
MP:0005395
MP:0005397
MP:0008264
MP:0008266
MP:0008267
MP:0008268
MP:0008270
MP:0008284
MP:0008285
MP:0008286
MP:0008927
MP:0008931
MP:0009572
MP:0009573
MP:0009574
MP:0009627
MP:0009846
MP:0009939
MP:0009944
MP:0009948
MP:0009949
MP:0009950
MP:0009951
MP:0009978
MP:0009988
MP:0009989
MP:0009990
MP:0009991
MP:0009992
MP:0009993
MP:0009994
MP:0009995
MP:0009996
MP:0009997
MP:0009998
MP:0009999
MP:0010000
MP:0010001
MP:0010002
MP:0010003
MP:0010004
MP:0010005
MP:0010007
MP:0010336
MP:0010337
MP:0010828
MP:0010829
MP:0010830
MP:0010899
MP:0010903
MP:0011149
MP:0011150
MP:0011151
MP:0011152
MP:0011153
MP:0011154
MP:0011155
MP:0011273
MP:0011274
MP:0011324
MP:0011329
MP:0011330
MP:0011495
MP:0011496
MP:0011504
MP:0011510
MP:0011511

Reported by: cindyJax

Original Ticket: [obo/mammalian-phenotype-requests/1148](https://sourceforge.net/p/obo/mammalian-phenotype-requests/1148)

**Comment by anna-anagnostop** [comment]
This issue will be closed as it is superseded by MP issue #3159
