### ISSUE TITLE
ventricle term name inconsistency

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#1179]
Hi,
The terms decreased left ventricle systolic pressure \(MP:0003822\), increased left ventricle diastolic pressure \(MP:0003819\), increased left ventricle weight \(MP:0003915\), decreased ventricle muscle contractility \(MP:0005598\), increased left ventricle weight \(MP:0003915\) lack the word "heart" in the term name. Most of the other heart ventricle terms include heart. Please add heart to these terms.
Thanks,
Sue

Reported by: sbello

Original Ticket: [obo/mammalian-phenotype-requests/1179](https://sourceforge.net/p/obo/mammalian-phenotype-requests/1179)

**Comment by cindyJax** [comment]
done
