### ISSUE TITLE
fused branchial arches

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#1181]
Consider adding the term 
fused branchial arches
def - failure of two or more arches to fully separate
child of abnormal branchial arch morphology \(MP:0002884\)
phenotype appears in J:185330

Reported by: sbello

Original Ticket: [obo/mammalian-phenotype-requests/1181](https://sourceforge.net/p/obo/mammalian-phenotype-requests/1181)

**Comment by sbello** [comment]
MP:0020350
