### ISSUE TITLE
abnormal capillary morphology children

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#1326]
Currently the only child of abnormal capillary morphology is abnormal kidney capillary morphology. We have over 50 annotations to the general capillary term, so I think we should consider adding new terms. Some basic suggestions increased and decreased number \(or density\) and dilated capillaries. 

The paper I'm working on \(J:191046\) deals with capillary caveolae, fenestra and transendothelial channel diaphragms. We have a term for abnormal glomerular endothelium fenestra morphology and a term for absent caveolae but nothing else. I'm annotating to abnormal capillary morphology and abnormal vascular endothelial cell morphology for this phenotype plus to appropriate tissue specific capillary terms. It may be helpful to have some combined terms to avoid the double and triple annotating.

Abnormal peritubular capillary endothelium morphology is currently not a child of abnormal vascular endothelial cell morphology.

Reported by: sbello

Original Ticket: [obo/mammalian-phenotype-requests/1326](https://sourceforge.net/p/obo/mammalian-phenotype-requests/1326)

**Comment by sbello** [comment]
MP:0020326 - dilated capillary

**Comment by sbello** [comment]
MP:0020327 - abnormal capillary branching pattern
MP:0020328 - abnormal capillary density
MP:0020329 - decreased capillary density
MP:0020330 - increased capillary density

I'm struggling with the logical definition for "density" I'm uncertain from the definition of "area density" PATO:0001351 if this would be correct in this case. The closest term with a logical definition I could find is MP:0009408 which is:
'has part' some 
    ('decreased amount'
     and ('inheres in' some 'cell of skeletal muscle')
     and ('has modifier' some abnormal))
I don't think this is right as the reasoner wants to make this term equivalent to 'decreased skeletal muscle fiber number'

**Comment by sbello** [comment]
MP:0020331 - increased capillary tortuosity
