### ISSUE TITLE
absent cornea

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#1466]
Please add:

absent cornea
DEF: absence of the transparent anterior portion of the fibrous coat of the eye that serves as the chief refractory structure. 
SYN: cornea agenesis
SYN: corneal agenesis
SYN: cornea aplasia
SYN: corneal aplasia
SYN: absent tunica cornea
SYN: absent cornea of camera-type eye
From J:190013

NOTE: UBERON defines cornea as the "transparent front part of the eye that covers the iris, pupil, and anterior chamber. Together with the lens, the cornea refracts light, accounting for approximately two-thirds of the eye's total optical power". Modify MP definition?

ALSO, please add "tunica cornea" and "cornea of camera-type eye" as synonyms of cornea where applicable.

Finally, add "keratitis" as a new synonym of corneal inflammation; see term "increased incidence of corneal inflammation [MP:0001313]"

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/1466](https://sourceforge.net/p/obo/mammalian-phenotype-requests/1466)

**Comment by cindyJax** [comment]
Definition is revised.
