### ISSUE TITLE
pleural cavity

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#1650]
Please add:

abnormal pleural cavity morphology as a parent term of "pleural effusion [MP:0010334]", "hemothorax [MP:0005243]", and "pneumothorax [MP:0010822]"
DEF: any structural anomaly of the potential space between the two pleurae (visceral and parietal) of the lungs; the pleural cavity, with its associated pleurae, aids optimal functioning of the lungs during breathing; it normally contains a thin film of serous fluid (“pleural fluid”) which lubricates the opposed pleural membranes so that they can glide smoothly against one another during ventilation.
Syn: abnormal intrapleural space morphology
Syn: abnormal pleural space morphology
From J:30559, J:54641

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/1650](https://sourceforge.net/p/obo/mammalian-phenotype-requests/1650)

**Comment by cindyJax** [comment]
Already completed.
