### ISSUE TITLE
NTR: children of abnormal erythrocyte physiology

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#1757]
Proposed new hierarchy
MP:0003656 abnormal erythrocyte physiology
-i-MP:NEW abnormal erythrocyte agglutinability
-i-MP:NEW high erythrocyte agglutinability
## -i-MP:NEW low erythrocyte agglutinability

MP:NEW abnormal erythrocyte agglutinability
Def: an anomaly in the ability of red cells to be aggregated or clump
Source: PMID: 4810935

MP:NEW high erythrocyte agglutin ability
Def: greater ability of red cells to be aggregated or clump
Source: PMID: 4810935

MP:NEW low erythrocyte agglutin ability
Def: reduced ability of red cells to be aggregated or clump
Source: PMID: 4810935

Reported by: nicolevasilevsky

Original Ticket: [obo/mammalian-phenotype-requests/1757](https://sourceforge.net/p/obo/mammalian-phenotype-requests/1757)

**Comment by sbello** [comment]
added terms for abnormal/increased/decreased erythrocyte aggregation - MP:0020453/MP:0020455/MP:0020454 
used aggregation rather than agglutinability as this matches the GO term name
