### ISSUE TITLE
abnormal male germ cell physiology

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#1780]
I ended up annotating failure of male germ cell mitotic arrest for J:205334 to abnormal male reproductive system physiology as we don't have a generic term for male germ cell physiology. Please consider adding a term for abnormal male germ cell physiology and/or abnormal male germ cell mitotic arrest as a child of abnormal male reproductive system physiology. If you add abnormal male germ cell physiology, then the term abnormal male germ cell apoptosis should be made a child of the new term.
thanks,
Sue

Reported by: sbello

Original Ticket: [obo/mammalian-phenotype-requests/1780](https://sourceforge.net/p/obo/mammalian-phenotype-requests/1780)

**Comment by sbello** [comment]
germ cell - MP:0020363
male germ cell - MP:0020362
female germ cell - MP:0020364
