### ISSUE TITLE
abnormal amacrine cell morphology MP:0005240

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#1785]
The term abnormal amacrine cell morphology (MP:0005240) currently has 30+ annotations. A number of these specify subtypes of amacrine cells, most frequently starburst amacrine cells (SAC) and dopaminergic amacrine cells. We may want to add child terms for at least some of these subtypes:
abnormal starburst amacrine cell morphology
syn abnormal SAC morphology
def: any structural anomaly of the retinal amacrine cells with a characteristic “starburst” shape of the dendritic arbor and that secrete both the the inhibitory neurotransmitter gamma-aminobutyric acid and the excitatory neurotransmitter acetylcholine.
def source: http://wiki.eyewire.org/en/Starburst_Amacrine_Cell
see also http://webvision.med.utah.edu/book/part-iii-retinal-circuits/roles-of-amacrine-cells/ for other subtypes of amacrine cells

abnormal dopaminergic amacrine cell morphology
def: any structural anomaly of the retinal amacrine cells that express dopamine and are often identified by immunostaining for expression of tyrosine hydroxylase.
def source:  http://webvision.med.utah.edu/book/part-iii-retinal-circuits/roles-of-amacrine-cells/ 
a number of the annotations mention TH+ amacrine cells without mentioning dopamine so I thought the inclusion of TH in the definition would be helpful.

Please consider also adding a term for:
abnormal amacrine cell body localization
syn  abnormal amacrine cell body stratification
child of abnormal retinal inner plexiform layer morphology (MP:0003734) and abnormal amacrine cell morphology (MP:0005240)
There are many existing annotations for this phenotype which are annotated to either one or both of the suggested parent terms.

SAC and stratification phenotypes are in J:202884.

Thanks,
Sue

Reported by: sbello

Original Ticket: [obo/mammalian-phenotype-requests/1785](https://sourceforge.net/p/obo/mammalian-phenotype-requests/1785)

**Comment by sbello** [comment]
MP:0020376 - starburst
MP:0020377 - dopaminergic
