### ISSUE TITLE
abnormal axon radial sorting

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#1789]
In J:204174 the authors describe impaired radial sorting of axons. In trying to figure out where to put this I found 2 annotations made to abnormal nervous system morphology (genotypes MGI:3789189, MGI:3789289) and 1 to abnormal myelination (MGI:3687860) based on the description of the process in J:204174 I was thinking of putting my annotation under abnormal Schwann cell physiology. Given the variability in annotations I think we should add a term for:
abnormal axon radial sorting
def: any anomaly in the process during which Schwann extend lamellipodia-like processes to segregate large- and small-caliber axons prior to myelination
def source: J:204174
child of abnormal Schwann cell physiology

Reported by: sbello

Original Ticket: [obo/mammalian-phenotype-requests/1789](https://sourceforge.net/p/obo/mammalian-phenotype-requests/1789)

**Comment by sbello** [comment]
reference: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5181106/
" Immature Schwann cells derive from Schwann cell precursors. They perform radial sorting of axons, a physiological process that starts perinatally and proceeds until ~ post/natal day 10 (P10) in the rodent peripheral nervous system (PNS) (Fig. 1). A similar process occurs in all vertebrates, including humans. At the beginning of radial sorting, axons are grouped in bundles by a “family” of 3–8 immature Schwann cells that organize a common basal lamina around them (Jessen and Mirsky, 2005; Webster and others, 1973) (Fig. 1). Ultrastructural reconstructions of developing nerves by Henry deF. Webster (Fig. 2) showed that these Schwann cell families surround axons of mixed caliber, and send cytoplasmic processes that resemble lamellipodia between axons, to progressively choose and segregate the larger axons at the periphery of the bundle. Through progressive Schwann cell proliferation and subdivision of the axon bundles, these large axons acquire a 1:1 relationship with a Schwann cell (pro-myelinating) and become myelinated, following the deposition of the Schwann cell own basal lamina (defasciculation). As Schwann cell proliferation and axonal segregation progresses axon bundles become smaller until they contain only small caliber axons, which will subsequently differentiate into Remak bundles."

**Comment by sbello** [comment]
MP:0020452, placed under abnormal nervous system development
