### ISSUE TITLE
beige fat

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#1808]
Need terms for beige adipocytes (req by A Valenzuela)

See PMID:22796012, PMID:23603813 and PMID:24575370

Reported by: cindyJax

Original Ticket: [obo/mammalian-phenotype-requests/1808](https://sourceforge.net/p/obo/mammalian-phenotype-requests/1808)

**Comment by sbello** [comment]
MP:0020325
