### ISSUE TITLE
abnormal synapse morphology

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#1834]
Please consider adding new child terms for abnormal synapse morphology. Some suggestions
abnormal excitatory synapse morphology (we have several annotations including some in J:205570 that specify excitatory synapses with several mentioning that inhibitory synapses are normal)
abnormal inhibitory synapse morphology
abnormal synapse number (syn abnormal synapse density) phenotype appears in J:205570
Thanks,
Sue 

Reported by: sbello

Original Ticket: [obo/mammalian-phenotype-requests/1834](https://sourceforge.net/p/obo/mammalian-phenotype-requests/1834)

**Comment by sbello** [comment]
symmetric - MP:0020361
asymmetric - MP0020360
inhibitory - MP:0020358
excitatory - MP:0020357
ribbon - MP:0020359
