### ISSUE TITLE
irregular external granule cell layer [MP:0000874]

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#1838]
The name of this term (irregular external granule cell layer [MP:0000874]) is easily confused with the parent term abnormal cerebellum external granule cell layer morphology [MP:0000872]. The definition specifies that it's the thickness that's irregular. 

Consider renaming the term to irregular external granule cell layer thickness.

Reported by: michknow

Original Ticket: [obo/mammalian-phenotype-requests/1838](https://sourceforge.net/p/obo/mammalian-phenotype-requests/1838)

**Comment by sbello** [comment]
modified term name to include thickness
