### ISSUE TITLE
adding synonym to sperm motility terms

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#1839]
There is currently no term for "progressive motility" in Mammalian Phenotype.
Progressive motility contains the aspects of directionality and speed.

The closest term on MP is "abnormal activated sperm motility [MP:0009279]". 

Reported by: mylaw

Original Ticket: [obo/mammalian-phenotype-requests/1839](https://sourceforge.net/p/obo/mammalian-phenotype-requests/1839)

**Comment by sbello** [comment]
abnormal - MP:0020450
decreased - MP:0020451
