### ISSUE TITLE
reactive microglia

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#1846]
Per Alicia V,

Need term (or synonym of existing MP:0010762?) for reactive microglia

J:213552

Reported by: cindyJax

Original Ticket: [obo/mammalian-phenotype-requests/1846](https://sourceforge.net/p/obo/mammalian-phenotype-requests/1846)

**Comment by sbello** [comment]
Added terms for increased (MP:0020448) and decreased (MP:0020449). Reactive microglia is a synonym for activated microglia so I would not add this as a term.
