### ISSUE TITLE
abnormal saccharin consumption [MP:0002849] definition

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#1849]
In the definition of abnormal saccharin consumption [MP:0002849] "subjects demonstrate interest in ingesting saccharine" saccharin is misspelled. Isn't it normal for mice to demonstrate a preference for saccharin consumption? Also, I was confused as to why there wasn't a tree link to saccharin preference [MP:0002850] "subjects demonstrate predilection for saccharine over other offered substance". These terms seem to be related, if not overlapping.

Reported by: michknow

Original Ticket: [obo/mammalian-phenotype-requests/1849](https://sourceforge.net/p/obo/mammalian-phenotype-requests/1849)

**Comment by cindyJax** [comment]
Clarified definition for "abnormal saccharin consumption"
