### ISSUE TITLE
mammary gland synonyms

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#1951]
Consider adding the following terms as synonyms of mammary gland where applicable:

NEW SYN: lactiferous gland
NEW SYN: glandula mammaria

Consult CellFinder (http://cellfinder.org/ontology?id=CF_175078) and UBERON:0001911 for additional exact and related synonyms.

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/1951](https://sourceforge.net/p/obo/mammalian-phenotype-requests/1951)

**Comment by cindyJax** [comment]
Synonyms were added.
