### ISSUE TITLE
palatal rugae

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2009]
Please add the following synonyms and amend the definition of "abnormal palatal rugae morphology [MP:0009652]" to read as"

abnormal palatal rugae morphology [MP:0009652]
SUGGESTED DEF: any structural anomaly in the series of transverse folds (ridges) of the mucosa located on the anterior third part of the secondary (hard) palate of most mammalian species; rugae are present on each side of the median palatal raphe and behind the incisive papillae, but their number and arrangement are species specific; together with the teeth and the tongue, rugae take part in mastication by helping to sense, hold and mash the food; rugae harbor various types of intraepithelial sensory structures (such as Merckel cells, corpuscular endings and free nerve endings), and play a sensory role when the food is pressed by the tongue against the hard palate

SYN: abnormal impressiones rugales morphology
SYN: abnormal plica palatina transversa morphology
SYN: abnormal plica palatinae transversae morphology
SYN: abnormal palatal ridge morphology
SYN: abnormal palatine fold morphology
SYN: abnormal palatine rugae morphoogy
SYN: abnormal ruga of palate morphology
SYN: abnormal rugae of palate morphology
SYN: abnormal ruga palatina morphoogy
SYN: abnormal rugae palatinae morphoogy
SYN: abnormal transverse palatine fold morphology
SYN: abnormal transverse palatine folds set
SYN: abnormal transverse palatine ridge morphology
SYN: abnormal plicae palatinae transversae morphology

SOURCES:

Pantalacci S et al. Patterning of palatal rugae through sequential addition reveals an anterior/posterior boundary in palatal development. BMC Dev Biol. 2008 Dec 16;8:116. doi: 10.1186/1471-213X-8-116.

UBERON SYNONYMS: http://bioportal.bioontology.org/ontologies/UBERON/?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0008799

Then, add new terms

1. absent palatal rugae

2. decreased palatal rugae number

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2009](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2009)

**Comment by cindyJax** [comment]
synonyms added.
