### ISSUE TITLE
paneth cell terms

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2028]
Please add:

ectopic Paneth cells
DEF: abnormal position of the large secretory cells containing coarse granules normally confined to the base of the crypts of Lieberkuhn in the small intestine 
SYN: ectopic Davidoff cells
SYN: ectopic Paneth granule cells
SYN: mislocalized Paneth cells
SYN: Paneth cell ectopia

absent Paneth cells
DEF: absence or loss of the large secretory cells containing coarse granules normally confined to the base of the crypts of Lieberkuhn in the small intestine
SYN: absent Davidoff cells
SYN: absent Paneth granule cells

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2028](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2028)

**Comment by cindyJax** [comment]
New terms added:
absent Paneth cells   MP:0014076
ectopic Paneth cells   MP:0014077
