### ISSUE TITLE
small intestinal villus terms

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2029]
Please add:

small intestinal villus atrophy
DEF: erosion or abnormal flattening of the surface secondary to the shortening and blunting of the small intestinal villi; villus atrophy is a non‐specific reaction of the intestinal mucosa to a variety of injuries; the pathogenesis is either associated with a hyper‐regenerative increase in crypt cell mitoses leading to crypt elongation or it results from hyporegeneration, that is, reduced mitotic rate with shortened crypts 
SYN: atrophic small intestinal villi
SYN: small intestinal villous atrophy

DEF SOURCE: http://www.ncbi.nlm.nih.gov/pmc/articles/PMC1860495/

decreased small intestinal villus number
DEF: fewer than normal numbers of the tiny hair-like projections which protrude from the inside of the small intestine and contain blood vessels that capture digested nutrients that are absorbed through the intestinal wall
SYN: decreased small intestinal villous number
SYN: reduced small intestinal villous number
SYN: reduced small intestinal villus number

fused small intestinal villi
DEF: partial or complete fusion of the tiny hair-like projections which protrude from the inside of the small intestine and contain blood vessels that capture digested nutrients that are absorbed through the intestinal wall
SYN: intestinal villous fusion 
SYN: intestinal villus fusion 

branched small intestinal villi
DEF: atypical formation of branched tree-like structures in the tiny hair-like projections which protrude from the inside of the small intestine and contain blood vessels that capture digested nutrients that are absorbed through the intestinal wall; branching may occur in association with increased or ectopic epithelial proliferation
SYN: intestinal villous branching
SYN: intestinal villus branching

decreased small intestinal villus height 
DEF: decreased height of the tiny hair-like projections which protrude from the inside of the small intestine and contain blood vessels that capture digested nutrients that are absorbed through the intestinal wall; usually accompanied by crypt elongation or hyperplasia
SYN: decreased small intestinal villous height
SYN: reduced small intestinal villous height
SYN: reduced small intestinal villus height
SYN: shortened small intestinal villi

blunted small intestinal villi
DEF: abnormal flattening of the surface of the tiny hair-like projections which protrude from the inside of the small intestine and contain blood vessels that capture digested nutrients that are absorbed through the intestinal wall; usually due to intestinal damage or injury
SYN: flattened small intestinal villi
SYN: intestinal villous blunting
SYN: intestinal villus blunting

clubbed small intestinal villi
DEF: club-shaped small intestinal villi with tips broader than the base; usually accompanied by cytoplasmic swelling and vacuolization
SYN: club-shaped intestinal villi
SYN: intestinal villous clubbing
SYN: intestinal villus clubbing

***NOTE: alternate spelling of villus = villous***

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2029](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2029)

**Comment by cindyJax** [comment]
New terms added:
small intestinal villus atrophy   MP:0014078
decreased small intestinal villus number  MP:0014079
fused small intestinal villi   MP:0014080
branched small intestinal villi  MP:0014081
decreased small intestinal villus height  MP:0014082
blunted small intestinal villi  MP:0014083
clubbed small intestinal villi  MP:0014084
