### ISSUE TITLE
forestomach

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2030]
Please add the following synonyms where applicable:

forestomach
NEW SYN: anterior stomach
NEW SYN: antrum cardiacum
NEW SYN: proximal stomach
NEW SYN: stomach non-glandular region

SOURCES:

https://books.google.com/books?id=ytWBLAy1FGQC&pg=PA101&lpg=PA101&dq=gastric+pit+and+mouse&source=bl&ots=0aOWpvOeCg&sig=0DVr57nSJBxqIbDZGZXCRFKksfI&hl=en&sa=X&ei=YCrwVNj9K82oyATm3oCoAQ&ved=0CDkQ6AEwBDgK#v=onepage&q=gastric%20pit%20and%20mouse&f=false

http://medical-dictionary.thefreedictionary.com/forestomach

http://www.sciencedirect.com/science/article/pii/S0012160612003454

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2030](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2030)

**Comment by cindyJax** [comment]
synonyms were added.
