### ISSUE TITLE
abnormal stomach squamous epithelium morphology [MP:0000472]

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2031]
Please consider relabeling "abnormal stomach squamous epithelium morphology [MP:0000472]" to
"abnormal stomach non-glandular epithelium morphology"

SUGGESTED DEF: any structural anomaly of the squamous epithelium that lines the distinct rodent non-glandular region of the stomach, i.e. the forestomach (aka anterior or proximal stomach); in neonatal and adult mice, this epithelium is stratified, fully keratinized, and devoid of gastric glands
SYN: abnormal anterior stomach epithelium morphology
SYN: abnormal antrum cardiacum epithelium morphology
SYN: abnormal forestomach epithelium morphology
SYN: abnormal non-glandular stomach epithelium morphology
SYN: abnormal proximal stomach epithelium morphology
SYN: abnormal stomach cardiac antrum epithelium morphology

SOURCE: http://www.sciencedirect.com/science/article/pii/S0012160612003454

stomach non-glandular epithelium hyperkeratosis
DEF: abnormal thickening of the stratum corneum in the stratified squamous epithelium lining the distinct rodent non-glandular region of the stomach, i.e. the forestomach (aka anterior or proximal stomach); hyperkeratosis frequently accompanies epithelial hyperplasia
SYN: anterior stomach epithelium hyperkeratosis
SYN: antrum cardiacum epithelium hyperkeratosis
SYN: forestomach epithelium hyperkeratosis
SYN: non-glandular stomach epithelium hyperkeratosis
SYN: proximal stomach epithelium hyperkeratosis
SYN: stomach cardiac antrum epithelium hyperkeratosis
SYN: stomach squamous epithelium hyperkeratosis

SOURCES:

J:203032

http://ntp.niehs.nih.gov/nnl/alimentary/forestomach/hyperker/stomach-forestomach-hyperkeratosis-pdf_508.pdf

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2031](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2031)

**Comment by cindyJax** [comment]
abnormal stomach squamous epithelium morphology MP:0000472 is relabeled and revised.

New term added:
stomach non-glandular epithelium hyperkeratosis  MP:0014085
