### ISSUE TITLE
parotid gland placement

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2032]
Acini in the parotid glands are almost exclusively of the serous type. Consider making "abnormal parotid gland morphology [MP:0003452]" a child term of "abnormal serous gland morphology [MP:0008052]".

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2032](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2032)

**Comment by cindyJax** [comment]
Additional parent term added to class.
