### ISSUE TITLE
parotid gland myoepithelium 

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2033]
Please add:

abnormal parotid gland myoepithelium morphology
DEF: any structural anomaly of the stellate-shaped contractile cells with long dendritic processes that surround the secretory acini and intercalated ducts of the parotid gland, usually found in the glandular epithelium as a thin layer above the basement membrane but generally beneath the luminal cells; they display features of both smooth muscle and epithelium, such as numerous microfilaments with focal densities in the cytoplasmic processes, and desmosomes which attach them to the epithelial cells; their functions include contraction when the gland is stimulated to secrete, compressing or reinforcing the underlying parenchymal cells, thus aiding in the expulsion of saliva and preventing damage to the other cells
SYN: abnormal parotid gland basket cell morphology
SYN: abnormal parotid gland myoepithelial cell morphology
SYN: abnormal parotid myoepithelial cell morphology
SYN: abnormal parotid myoepithelium morphology

SOURCES:

http://www.ccij-online.org/article.asp?issn=2278-0513;year=2013;volume=2;issue=2;spage=101;epage=105;aulast=Redder

http://en.wikipedia.org/wiki/Myoepithelial_cell

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2033](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2033)

**Comment by cindyJax** [comment]
MP:0014199
