### ISSUE TITLE
Ebner's gland placement

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2034]
Ebner's gland is a **posterior lingual gland** that is part of the **minor salivary gland system** in mammals.
 
Additional von Ebner's gland synonyms include:

NEW SYN: posterior deep lingual gland
NEW SYN: posterior lingual serous gland

SOURCES: 

http://www-06.all-portland.net/bst/031/0801/0310801.pdf

http://onlinelibrary.wiley.com/doi/10.1111/j.1469-7580.2008.01019.x/full

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2034](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2034)

**Comment by cindyJax** [comment]
already completed
