### ISSUE TITLE
Weber’s gland 

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2035]
Please add:

abnormal Weber’s gland morphology as a child of "abnormal minor salivary gland morphology [MP:0003791]"
DEF: any structural anomaly of the lingual glands located on the lateral margins of the tongue, at the level of the foliate papillae and in the root of the tongue behind the circumvallate papillae; in humans, the ducts of posterior superficial lingual glands open into the crypts of lingual tonsils; mucous supplied by these glands may help to cleanse the crypts and aid in deglutition
SYN: abnormal posterior superficial lingual gland morphology

SOURCE:
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2667924/

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2035](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2035)

**Comment by cindyJax** [comment]
previously entered
