### ISSUE TITLE
mucous gland

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2036]
Please add:

abnormal mucous gland morphology
DEF: any structural anomaly of any exocrine gland in which the principal secretory cells are mucus-secreting cells; mucus is a slippery secretion with lubricating or protective function produced by, and covering, mucous membranes; mucous glands typically stain lighter than serous glands during standard histological preparation; most are multicellular, but goblet cells are single-celled glands
SYN: abnormal glandula mucosa morphology
SYN: abnormal muciparous gland morphology
SYN: abnormal mucus-secreting gland mophology

abnormal mucous gland physiology
DEF: any functional anomaly of any exocrine gland in which the principal secretory cells are mucus-secreting cells; mucus is a slippery secretion with lubricating or protective function produced by, and covering, mucous membranes; mucous fluid is typically produced from cells found in mucous glands, but may also originate from mixed glands, which contain both serous and mucous cells; mucous cells secrete products that are rich in glycoproteins and water; mucus is a viscous colloid containing antiseptic enzymes (such as lysozyme), immunoglobulins, inorganic salts, proteins such as lactoferrin, and glycoproteins known as mucins that are produced by goblet cells in the mucous membranes and submucosal glands
SYN: abnormal glandula mucosa physiology
SYN: abnormal muciparous gland physiology
SYN: abnormal mucus-secreting gland physiology

SOURCES: 

UBERON:0000414

http://en.wikipedia.org/wiki/Mucous_gland

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2036](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2036)

**Comment by cindyJax** [comment]
previously entered
