### ISSUE TITLE
lacrimal gland myoepithelium

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2037]
Please add:

abnormal lacrimal gland myoepithelium morphology
DEF: any structural anomaly of the stellate-shaped contractile cells with flattened nuclei and long slender processes that surround the secretory acini and intralobular ducts of the lacrimal gland, located between the epithelium and the basement membrane; myoepithelial cells not only exhibit characteristics of other epithelial cells, such as expression of cytokeratin, but also exhibit properties of smooth muscle cells, such as expression of alpha-smooth muscle actin; their contraction might aid in the expulsion of fluid out of the secretory tubules or help maintain the patency of acinar and ductal lumens
SYN: abnormal lacrimal gland myoepithelial cell morphology
SYN: abnormal lacrimal myoepithelium morphology
SYN: abnormal lacrymal gland myoepithelium morphology
SYN: abnormal lacrymal gland myoepithelial cell morphology
SYN: abnormal lacrymal myoepithelium morphology

https://books.google.com/books?id=fjZjN_xGfGAC&pg=PA69&lpg=PA69&dq=mouse+lacrimal+gland+duct&source=bl&ots=NCMoeK0H4c&sig=nl2vgDM5Yi0Sp80clEABJvNTRbM&hl=en&sa=X&ei=ynL4VNClBYONyATAxIDICA&ved=0CE8Q6AEwBjgK#v=onepage&q=mouse%20lacrimal%20gland%20duct&f=false

https://books.google.com/books?id=me3Yb2H2KeIC&pg=PT208&lpg=PT208&dq=mouse+lacrimal+gland+and+lobe+and+lobule&source=bl&ots=Gij2SWFLQ4&sig=sIux57r77qpiR5MsK9_Qc-CS6bk&hl=en&sa=X&ei=IGX4VKrtL8GAygTF-YLoAQ&ved=0CC0Q6AEwBQ#v=onepage&q=mouse%20lacrimal%20gland%20and%20lobe%20and%20lobule&f=false

https://books.google.com/books?id=93s6aes5ob0C&pg=PA29&lpg=PA29&dq=lacrimal+gland+myoepithelial+cell+and+duct&source=bl&ots=AybwQh86W4&sig=93MFZ_oFG4mYwVqhuLJ7LI3MaVY&hl=en&sa=X&ei=bID4VPKJFNOmyATdpYHYCA&ved=0CB0Q6AEwADgK#v=onepage&q=lacrimal%20gland%20myoepithelial%20cell%20and%20duct&f=false

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2037](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2037)

**Comment by cindyJax** [comment]
abnormal lacrimal gland myoepithelium morphology  MP:0014156
