### ISSUE TITLE
absent intraorbital lacrimal gland

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2038]
Please add:

absent intraorbital lacrimal gland
DEF: absence of the small intra-orbital lacrimal gland, normally located superficially at the lateral canthus, where both the lacrimal gland and Harderian gland ducts open 
SYN: absent intra-orbital lacrimal gland
SYN: absent intraorbital lacrymal gland
SYN: absent intra-orbital lacrymal gland
J:107208

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2038](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2038)

**Comment by cindyJax** [comment]
Duplicate request
