### ISSUE TITLE
absent exorbital lacrimal gland 

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2039]
Please add:

absent exorbital lacrimal gland 
DEF: absence of the large exorbital (extra-orbital) lacrimal gland, normally located subcutaneously at the anteroventral base of the ear adjacent to the parotid gland 
SYN: absent extra-orbital lacrimal gland
SYN: absent extraorbital lacrimal gland
SYN: absent extra-orbital lacrymal gland
SYN: absent extraorbital lacrymal gland
SYN: absent exorbital lacrymal gland 
J:72517

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2039](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2039)

**Comment by cindyJax** [comment]
Duplicate request
