### ISSUE TITLE
absent pituitary infundibular stalk

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2040]
absent pituitary infundibular stalk
DEF: absence of the apical portion of the tubular structure extending from the hypothalamus to the posterior lobe of the pituitary gland
SYN: absent hypophyseal stalk
SYN: absent infundibular stem
SYN: absent pituitary infundibulum
SYN: absent pituitary stalk
J:47920

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2040](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2040)

**Comment by cindyJax** [comment]
MP:0014198
