### ISSUE TITLE
absent olfactory epithelium 

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2041]
Please add:

absent olfactory epithelium 
DEF: absence of the epithelial cells that line the interior of the nose
SYN: absent nasal epithelium
J:104488

NOTE: relabel "abnormal horizontal basal cell morphology MP:0012069" to "abnormal horizontal basal cell of olfactory epithelium morphology".

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2041](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2041)

**Comment by cindyJax** [comment]
absent olfactory epithelium MP:0014155
