### ISSUE TITLE
abnormal tear film physiology

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2044]
abnormal tear film physiology
DEF: any functional anomaly of the thin acelullar fluid layer that covers the anterior surface of the mammalian eye and has a variety of constituents that are essential for the maintenance of the avascular transparent corneal epithelium; this film keeps the cornea wet, thus allowing gas exchange between the air and the epithelium, it cleans debris from the transparent surface, providing a clear optical path to the retina, and protects the ocular surface from invasion by bacteria and viruses; the tear film also provides essential metabolites such as retinol, which serves to preserve the transparent nature of the epithelium
SYN: abnormal precorneal film physiology 

SOURCE: http://physiologyonline.physiology.org/content/13/2/97

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2044](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2044)

**Comment by cindyJax** [comment]
New term added:
abnormal tear film physiology  MP:0014132
