### ISSUE TITLE
abnormal tear film morphology

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2045]
Please add:

abnormal tear film morphology
DEF: any alteration in the structure, biochemical composition, or stability of the thin acellular fluid layer that adheres to the most superficial layer of the corneal epithelium and lubricates and protects the ocular surface; the film is generally composed of three layers: (i) an inner mucous layer, secreted largely by the conjunctival goblet cells with contributions from the lacrimal glands, which coats the cornea, provides a hydrophobic layer, and allows for even distribution of the tear film; (ii) a middle aqueous layer, secreted by the lacrimal glands, which keeps the corneal surface moist, and provides a mechanism for oxygenation and nutrient exchange with the avascular anterior corneal tissue; and (iii) an outer lipid layer, secreted principally by the Meibomian (tarsal) glands although lipid tear elements also are contributed by the Harderian glands; tear film lipids form a monolayer on the tear surface, and function by enhancing the surface tension which supports the integrity of the tear film against collapse due to gravity and also slows down the loss of the tear film by evaporation; in addition , the lipid layer provides a glassy, smooth interface between the air and the transparent cornea
SYN: abnormal precorneal film morphology

SOURCES:

https://books.google.com/books?id=RXsdAAAAQBAJ&pg=PA2116&lpg=PA2116&dq=tear+film+and+harderian&source=bl&ots=h2mhQ-RwY0&sig=Ic7jRIV3R_aYRMDNwDvks3dsKzw&hl=en&sa=X&ei=2Jb5VI-3GoWxyASFvYLoAw&ved=0CE8Q6AEwCQ#v=onepage&q=tear%20film%20and%20harderian&f=false

http://en.wikipedia.org/wiki/Tears

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2045](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2045)

**Comment by cindyJax** [comment]
New term added:
abnormal tear film morphology  MP:0014131
