### ISSUE TITLE
thymus cyst

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2046]
Please add:

thymus cysts
DEF: presence of fluid-filled spaces lined by epithelium within the thymus; thymic cysts are rare mediastinal lesions and are thought to result from the congenital persistence of thymopharyngeal tracts and acquired, progressive cystic degeneration of thymic (Hassall) corpuscles and epithelial reticulum of the thymus; congenital cysts are unilocular, whereas acquired cysts are usually multilocular and result as a consequence of inflammatory processes
SYN: cystic thymus
SYN: thymic cysts

SOURCES:

http://www.pedsradiology.com/historyanswer.aspx?qid=408&fid=1

http://www.jthoracdis.com/article/view/514/997

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2046](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2046)

**Comment by cindyJax** [comment]
New term added:
thymus cysts MP:0014130
