### ISSUE TITLE
thymus fibrosis

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2047]
Please add:

thymus fibrosis
DEF: invasion of fibrous connective tissue into the thymus, often resulting from inflammation or injury
SYN: thymic fibrosis

J:139032	

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2047](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2047)

**Comment by cindyJax** [comment]
New term added:
thymus fibrosis MP:0014129
