### ISSUE TITLE
abnormal thymus development

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2048]
Consider amending the definition to read as:

abnormal thymus development [MP:0000704] 
SUGGESTED DEF: anomaly in the formation and/or differentiation of the thymus; in mouse, the parathyroid glands develop with the thymus from two common parathyroid/thymus primordia originating from the third pharyngeal pouch endoderm; the third pharyngeal pouches are formed at E9.5-E10 and are patterned into dorsal/anterior parathyroid and ventral/posterior thymus domains; the third pouch endoderm proliferates to form bilateral parathyroid/thymus common primordia at E11-E11.5; each primordium separates into one parathyroid gland and one thymus lobe at E12.5-E13.5, which then migrate to their eventual adult locations by about E14.5; the parathyroids locate adjacent to, or sometimes embedded within, the thyroid gland; the thymus migrates further caudally into the thorax, where the two lobes meet at the midline just above the heart; embryonic thymic remnants can give rise to ectopic thymic tissue in the neck, thyroid, and parathyroid glands; the thymus is the first of the lymphoid organs to be formed and grows considerably immediately after birth in response to postnatal antigen stimulation and the demand for large numbers of mature T cells; in rats and mice, the thymus reaches maximal size by sexual maturity and then gradually involutes
SYN: abnormal thymic development
SYN: abnormal thymus organogenesis

DEF COMPILED FROM:

J:121311

http://dev.biologists.org/content/138/18/3865.full.pdf

http://tpx.sagepub.com/content/34/5/504.full

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2048](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2048)

**Comment by cindyJax** [comment]
Added synonyms but put most of the additional new text in as a comment.
