### ISSUE TITLE
increased thymus apoptosis

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2049]
Please add:

increased thymus apoptosis
DEF: increase in the number of cells of the thymus undergoing programmed cell death
SYN: increased thymic apoptosis
J:15224, J:71404, J:46522, J:64151, J:108405	

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2049](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2049)

**Comment by cindyJax** [comment]
Need to consider how this is different or may overlap with 'abnormal thymocyte apoptosis'
