### ISSUE TITLE
Harderian gland adenocarcinoma 

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2050]
Please add:

increased Harderian gland adenocarcinoma incidence
DEF: greater than the expected number of a malignant neoplasm of acinar epithelial cells in the Harderian gland, occurring in a specific population in a given time period; these usually are larger than adenomas and may cause facial selling and/or exophthalmos; they are highly cellular and disorganized compared to adenomas, with piling up of pleomorphic cells; areas of medullary or solid growth patterns are common; there may necrosis or hemorrhage, invasion beyond the orbit, and distant metastasis to the lungs, local lymph nodes, thymus or liver
SYN: Harderian adenocarcinoma
SYN: Harderian gland adenocarcinoma

DEF SOURCE:

The Mouse in Biomedical Research: Diseases p690
https://books.google.com/books?id=MFQ_-Ijb_ycC&pg=PA690&lpg=PA690&dq=harderian+adenocarcinoma&source=bl&ots=ooOSk3fDMU&sig=mCdaS2L4UA4muMtQGnmrlHxmmwM&hl=en&sa=X&ei=MF0BVcSCNbiSsQTOooKQCA&ved=0CB0Q6AEwADgK#v=onepage&q=harderian%20adenocarcinoma&f=false

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2050](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2050)

**Comment by cindyJax** [comment]
New term added:
increased Harderian gland adenocarcinoma incidence  MP:0014128
