### ISSUE TITLE
thymoma

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2051]
Please add:

increased thymoma incidence
DEF: greater than the expected number of a malignant neoplasm originating from the epithelial cells of the thymus, occurring in a specific population in a given time period; thymoma is an uncommon tumor linked with myasthenia gravis and other autoimmune diseases
SYN: thymoma

J:198260 (correct typo in “thyoma”)

SOURCES:
http://www.cancer.gov/cancertopics/pdq/treatment/thymoma/patient/page1#_139
http://medical-dictionary.thefreedictionary.com/thymoma

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2051](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2051)

**Comment by cindyJax** [comment]
New term added:
increased thymoma incidence  MP:0014127
