### ISSUE TITLE
increased mammary gland apoptosis

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2054]
Please add:

increased mammary gland apoptosis
DEF: increase in the number of any cells of a mammary gland undergoing programmed cell death
J:111560

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2054](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2054)

**Comment by cindyJax** [comment]
New term added:
increased mammary gland apoptosis MP:0014126
