### ISSUE TITLE
lethality term

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2057]
new child of preweaning lethality [MP:0010770]

complete lethality between fetal growth and the end of the neonatal period

def:  death of individual organisms of a given genotype in a population anytime during fetal growth and development stages through the end of the perinatal period
(Mus: E18.5 through postnatal day 1)

                                                                                          

Reported by: llw2

Original Ticket: [obo/mammalian-phenotype-requests/2057](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2057)

**Comment by cindyJax** [comment]
timing suggested is the same as perinatal lethality - use this term instead
