### ISSUE TITLE
RE seizures

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2062]
request child of 
seizures [MP:0002064]

partial seizure  

def 
restricted uncontrolled electrical activity resulting when abnormal electrical disturbances occur in a limited area of the brain

syn focal seizure

Reported by: llw2

Original Ticket: [obo/mammalian-phenotype-requests/2062](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2062)

**Comment by cindyJax** [comment]
New term added 
focal seizures  MP:0014120
