### ISSUE TITLE
exocrine pancreatic insufficiency

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2063]
Consider amending the definition for exocrine pancreatic insufficiency [MP:0003335] to read as:

SUGGESTED DEF: inadequate synthesis and secretion of digestive enzymes by the exocrine portion of the pancreas, usually due to loss of acinar tissue from idiopathic atrophy or acute or chronic inflammation, causing maldigestion and malabsorption of nutrients

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2063](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2063)

**Comment by cindyJax** [comment]
Definition is revised
