### ISSUE TITLE
abnormal pancreatic amylin secretion

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2064]
Consider renaming "abnormal glucagon secretion [MP:0003565]" and abnormal insulin secretion [MP:0003564] plus any children thereof using "pancreatic" as part of the primary term label for consistency (see "abnormal pancreatic ghrelin secretion [MP:0009196]").

Then add new terms:

abnormal pancreatic amylin secretion
DEF: any anomaly in the production or release of the polypeptide hormone that is co-secreted with insulin by the beta cells of the pancreatic islets of Langerhans and is known to inhibit glucagon secretion, delay gastric emptying, and act as a satiety agent
SYN: abnormal pancreatic islet amyloid polypeptide secretion
SYN: abnormal pancreatic IAPP secretion

increased pancreatic amylin secretion
DEF: greater than normal production or release of the polypeptide hormone that is normally co-secreted with insulin by the beta cells of the pancreatic islets of Langerhans and is known to inhibit glucagon secretion, delay gastric emptying, and act as a satiety agent
SYN: increased pancreatic islet amyloid polypeptide secretion
SYN: increased pancreatic IAPP secretion

decreased pancreatic amylin secretion
DEF: reduction in the production or release of the polypeptide hormone that is normally co-secreted with insulin by the beta cells of the pancreatic islets of Langerhans and is known to inhibit glucagon secretion, delay gastric emptying, and act as a satiety agent
SYN: decreased pancreatic islet amyloid polypeptide secretion
SYN: decreased pancreatic IAPP secretion
SYN: reduced pancreatic islet amyloid polypeptide secretion
SYN: reduced pancreatic IAPP secretion
J:75664 

DEF SOURCE: http://www.ajpcr.com/Vol6Issue1/1462.pdf

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2064](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2064)

**Comment by cindyJax** [comment]
amylin is known only to be secreted by pancreatic beta cells, so specifying 'pancreatic' location in the term name is not necessary.
New terms added:
abnormal amylin secretion MP:0014123
increased amylin secretion MP:0014124
decreased amylin secretion MP:0014125
