### ISSUE TITLE
abnormal limb position [MP:0012000]

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2065]
Consider changing the primary term label for MP term "abnormal limb position [MP:0012000]" to "ectopic limb(s)" for consistency.

See J:207896

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2065](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2065)

**Comment by cindyJax** [comment]
Text definition is inconsistent with the proposed new label "ectopic limbs".  The broad synonym "ectopic limbs was removed from this class.  Another term "supernumerary limbs" MP:0002288 was relabeled "ectopic limbs" with the original label retained as a synonym.
