### ISSUE TITLE
abnormal endocrine pancreas secretion

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2066]
Please add:

abnormal endocrine pancreas secretion as a child of "abnormal pancreas secretion [MP:0002694]"
DEF: anomaly in the synthesis and/or release of any of the hormones produced by different types of cells in the islets of Langerhans of the endocrine pancreas and secreted directly into the blood stream to regulate blood glucose homeostasis; these hormones include glucagon secreted by alpha cells, insulin and amylin (also known as Islet Amyloid Polypeptide or IAPP) co-secreted by beta cells, somatostatin secreted by delta cells, gherlin secreted by epsilon cells, and pancreatic polypeptide secreted by PP cells (also known as F cells)
SYN: abnormal endocrine pancreatic secretion

Children terms of "abnormal endocrine pancreas secretion" should include:

abnormal pancreatic amylin secretion (see ticket #2064)
abnormal pancreatic ghrelin secretion
abnormal pancreatic glucagon secretion (see ticket #2064)
abnormal pancreatic insulin secretion (see ticket #2064)
abnormal pancreatic polypeptide secretion
abnormal pancreatic somatostatin secretion

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2066](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2066)

**Comment by cindyJax** [comment]
MP:0014195
