### ISSUE TITLE
split abnormal pancreatic islet cell apoptosis

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2067]
Split abnormal pancreatic islet cell apoptosis into:

increased pancreatic islet cell apoptosis
DEF: increase in the number of pancreatic islet cells undergoing programmed cell death

decreased pancreatic islet cell apoptosis
DEF: decrease in the number of pancreatic islet cells undergoing programmed cell death  
SYN: reduced pancreatic islet cell apoptosis

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2067](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2067)

**Comment by cindyJax** [comment]
New terms added:
increased pancreatic islet cell apoptosis MP:0014121
decreased pancreatic islet cell apoptosis MP:0014122
