### ISSUE TITLE
abnormal pancreatic beta cell apoptosis

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2068]
Please add:

abnormal pancreatic beta cell apoptosis as a child of "abnormal pancreatic beta cell physiology [MP:0003562]"
DEF: change in the timing or the number of pancreatic beta cells undergoing programmed cell death 

increased pancreatic beta cell apoptosis
DEF: increase in the number of pancreatic beta cells undergoing programmed cell death 

decreased pancreatic beta cell apoptosis
DEF: decrease in the number of pancreatic beta cells undergoing programmed cell death 
SYN: reduced pancreatic beta cell apoptosis

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2068](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2068)

**Comment by cindyJax** [comment]
New terms added:
abnormal pancreatic beta cell apoptosis   MP:0014116
increased pancreatic beta cell apoptosis  MP:0014117
decreased pancreatic beta cell apoptosis  MP:0014118
