### ISSUE TITLE
increased pancreatic alpha cell proliferation

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2069]
Please add:

increased pancreatic alpha cell proliferation
DEF: increase in the ability of the glucagon-producing cells of the islets of Langerhans in the endocrine pancreas to undergo expansion by cell division 
SYN: increased glucagon-secreting cell proliferation
SYN: increased pancreatic A cell proliferation

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2069](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2069)

**Comment by cindyJax** [comment]
New term added:
increased pancreatic alpha cell proliferation  MP:0014109
