### ISSUE TITLE
calcified pancreas

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2070]
Please add:

calcified pancreas
DEF: pathologic deposition of calcium salts in the pancreas; commonly seen in chronic pancreatitis
SYN: pancreas calcification
SYN: pancreatic calcification
J:155058

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2070](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2070)

**Comment by cindyJax** [comment]
New term added:
calcified pancreas MP:0014108
