### ISSUE TITLE
pancreatic amylase secretion

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2071]
Please add:

abnormal pancreatic amylase secretion
DEF: anomaly in the production and/or release of alpha-amylase, the main starch digesting enzyme component of pancreatic juice, from the acinar cells of the exocrine pancreas; pancreatic alpha-amylase is released into pancreatic ducts in its active form and acts at random locations along the starch chain to break down long-chain carbohydrates, ultimately yielding maltotriose and maltose from amylose, or maltose, glucose and limit dextrin from amylopectin
SYN: abnormal pancreatic alpha-amylase secretion

increased pancreatic amylase secretion
DEF: greater production and/or release of alpha-amylase, the main starch digesting enzyme component of pancreatic juice, from the acinar cells of the exocrine pancreas; pancreatic alpha-amylase is released into pancreatic ducts in its active form and acts at random locations along the starch chain to break down long-chain carbohydrates, ultimately yielding maltotriose and maltose from amylose, or maltose, glucose and limit dextrin from amylopectin
SYN: increased pancreatic alpha-amylase secretion

decreased pancreatic amylase secretion
DEF: reduction in the production and/or release of alpha-amylase, the main starch digesting enzyme component of pancreatic juice, from the acinar cells of the exocrine pancreas; pancreatic alpha-amylase is released into pancreatic ducts in its active form and acts at random locations along the starch chain to break down long-chain carbohydrates, ultimately yielding maltotriose and maltose from amylose, or maltose, glucose and limit dextrin from amylopectin
SYN: decreased pancreatic alpha-amylase secretion
SYN: reduced pancreatic alpha-amylase secretion

SOURCES:

http://www.newworldencyclopedia.org/entry/Pancreas
http://en.wikipedia.org/wiki/Amylase

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2071](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2071)

**Comment by cindyJax** [comment]
New terms added:
abnormal pancreatic amylase secretion  MP:0014096
increased pancreatic amylase secretion MP:0014097
decreased pancreatic amylase secretion MP:0014098
