### ISSUE TITLE
decreased pancreatic acinar cell zymogen granule number

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2072]
Please add:

decreased pancreatic acinar cell zymogen granule number
DEF: fewer than the expected number of membrane-bounded, cytoplasmic secretory granules found in pancreatic acinar cells that contain inactive digestive enzyme precursors 
SYN: reduced pancreatic acinar cell zymogen granule number
J:84450 

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2072](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2072)

**Comment by cindyJax** [comment]
New term added:
decreased pancreatic acinar cell zymogen granule number  MP:0014095
