### ISSUE TITLE
pancreatic primary cilia

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2073]
Please add:

abnormal pancreatic primary cilium morphology
DEF: any structural anomaly of the nonmotile primary cilia that assemble in the normal duct, islet, and centroacinar cells of the pancreas and function in sensing and signal transduction; acinar cells are not ciliated in the healthy pancreas; pancreatic ductal adenocarcinoma cells and precursor lesions (pancreatic intraepithelial neoplasia), in which Kras is frequently activated, lack primary cilia

decreased pancreatic primary cilium length
DEF: reduced length of the nonmotile primary cilia that are found in the normal duct, islet, and centroacinar cells of the pancreas and function in sensing and signal transduction; acinar cells are not ciliated in the healthy pancreas; pancreatic ductal adenocarcinoma cells and precursor lesions (pancreatic intraepithelial neoplasia), in which Kras is frequently activated, lack primary cilia
SYN: shortened pancreatic primary cilium
SYN: shortened pancreatic primary cilia
J:95813, J:155058

decreased pancreatic primary cilium number
DEF: reduced number of the nonmotile primary cilia that are found in the normal duct, islet, and centroacinar cells of the pancreas and function in sensing and signal transduction; acinar cells are not ciliated in the healthy pancreas; pancreatic ductal adenocarcinoma cells and precursor lesions (pancreatic intraepithelial neoplasia), in which Kras is frequently activated, lack primarycilia
SYN: reduced pancreatic primary cilium number
J:95813, J:155058

DEF SOURCE: 

http://jcb.rupress.org/content/193/3/435.full

http://jcs.biologists.org/content/123/4/511.full.pdf

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2073](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2073)

**Comment by cindyJax** [comment]
Revised somewhat using PMID:24861006 and PMID:24864023.
New terms added:
abnormal pancreatic primary cilium morphology  MP:0014092
decreased pancreatic primary cilium length  MP:0014093
decreased pancreatic primary cilium number  MP:0014094
