### ISSUE TITLE
increased glycogen level in cardiac muscle and brain

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2074]
Please add:

increased cardiac muscle glycogen level
DEF: greater than the normal concentration of a readily converted carbohydrate reserve in heart muscle
SYN: increased heart muscle glycogen level
SYN: increased myocardial glycogen level
SYN: increased cardiomyocyte glycogen level

increased brain glycogen level
DEF: greater than the normal concentration of a readily converted carbohydrate reserve in brain

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2074](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2074)

**Comment by cindyJax** [comment]
increased cardiac muscle glycogen level   MP:0014071
increased brain glycogen level  MP:0014074
