### ISSUE TITLE
Lafora bodies

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2077]
Please add:

Lafora bodies
DEF:  abnormal presence of insoluble periodic acid-Schiff-positive deposits that contain polyglucosan, a poorly branched form of glycogen, seen in familial myoclonic epilepsy; Lafora bodies develop in many tissues, including muscle, liver, and neurons, but it is generally believed that Lafora body accumulation ultimately leads to neuronal cell death
SYN: Lafora body accumulation
J:165994, J:181559, J:181674

DEF SOURCE: J:165994

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2077](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2077)

**Comment by cindyJax** [comment]
New terms entered:
Lafora bodies MP:0014063
