### ISSUE TITLE
ethmocephaly

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2078]
Please add:

ethmocephaly
DEF: the rarest form of holoprosencephaly, which occurs due to an incomplete cleavage of the forebrain; ethmocephaly presents with a proboscis situated above hypoteloric orbits in the midline, microphthalmos, absent nasal structures (arrhinia) and lowset malformed ears

SOURCE: http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3519136/

J:29682, J:220544

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2078](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2078)

**Comment by cindyJax** [comment]
ethmocephaly MP:0014061
