### ISSUE TITLE
abnormal platelet alpha-granule morphology

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2079]
In J:220801, platelets of mutant mice lack alpha-granules. Based on a web search, alpha-granules are different from dense granules. Alpha-granules are secretory granules that contain growth factors (platelets contain three types of secretory granules: alpha-granules, dense granules, and lysosomes). It looks like we have several annotations that refer to alpha-granules so there is precedence for creating this term (MP: abnormal platelet alpha-granule morphology). 

Reported by: monikat

Original Ticket: [obo/mammalian-phenotype-requests/2079](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2079)

**Comment by cindyJax** [comment]
abnormal platelet alpha-granule morphology MP:0014060
