### ISSUE TITLE
mammary gland bud placement

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2080]
Consider placing "abnormal mammary gland bud morphology" [MP:0013785], "abnormal mammary gland bud elongation" [MP:0013784] and proposed new term "abnormal mammary gland bud formation" [open ticket #2021] as children of "abnormal mammary gland embryonic development [MP:0004135]".

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2080](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2080)

**Comment by cindyJax** [comment]
Terms have been reorganized.
