### ISSUE TITLE
photoreceptor connecting cilium 

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2084]
Please add:

abnormal photoreceptor connecting cilium morphology as a child of “abnormal nonmotile primary cilium morphology [MP:0013205]”
DEF: any structural anomaly of the nonmotile primary cilium that has a 9+0 microtubule array and forms the portion of the axoneme traversing the boundary between the retinal photoreceptor inner and outer segments.

From J:214319

SOURCES:
Definition above is based on GO term: photoreceptor connecting cilium [GO:0032391]
see also Figure 4 Nature Reviews Genetics 11, 273-284 | doi:10.1038/nrg2717

------------

Alternative definition for photoreceptor connecting cilium:

The bridge between the inner and the outer segments of a retinal rod or a cone photoreceptor cell. Through it, proteins synthesized in the inner segment are transported to the outer segment.

see http://www.bioportfolio.com/resources/pmarticle/1069130/Ciliopathies-A-journey-through-the-cilium.html

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2084](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2084)

**Comment by cindyJax** [comment]
abnormal photoreceptor connecting cilium morphology  MP:0014059
