### ISSUE TITLE
abnormal mammary gland stroma 

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2085]
Please add:

abnormal mammary gland stroma morphology
DEF: any structural anomaly of the complex non-epithelial mammary gland tissue composed of fibrous connective tissue extracellular matrix (ECM) proteins, and a wide variety of cell types, including inter- and intralobular fibroblasts, adipocytes, endothelial cells, and innate immune cells (both macrophages and mast cells); the mammary gland stroma is the support network for the epithelium, providing both nutrients and blood supply, and immune defenses, as well as physical structure to the gland; each of the different stromal cell types secrete instructive signals that are crucial for various aspects of the development and function of the epithelium 
SYN: abnormal mammary stroma morphology

abnormal mammary gland stroma physiology
DEF: any functional anomaly of the complex non-epithelial mammary gland tissue composed of fibrous connective tissue extracellular matrix (ECM) proteins, and a wide variety of cell types, including inter- and intralobular fibroblasts, adipocytes, endothelial cells, and innate immune cells (both macrophages and mast cells); the mammary gland stroma is the support network for the epithelium, providing both nutrients and blood supply, and immune defenses, as well as physical structure to the gland; each of the different stromal cell types secrete instructive signals that are crucial for various aspects of the development and function of the epithelium 
SYN: abnormal mammary stroma physiology

SOURCE:  http://cshperspectives.cshlp.org/content/2/10/a003202.full

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2085](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2085)

**Comment by cindyJax** [comment]
abnormal mammary gland stroma morphology MP:0014057
abnormal mammary gland stroma physiology MP:0014058
