### ISSUE TITLE
increased sebocyte proliferation

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2086]
Please add:

increased sebocyte proliferation
DEF: increase in the expansion rate of sebocytes by cell division
SYN: increased sebaceous epithelial cell proliferation
SYN: increased sebaceous gland acinar cell proliferation

J:102127

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2086](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2086)

**Comment by cindyJax** [comment]
increased sebocyte proliferation  MP:0014056
