### ISSUE TITLE
dry hair

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2087]
Please add:

dry hair as a child of "abnormal hair texture [MP:0002074]"
SUGGESTED DEF: hair characterized by the lack of natural or normal moisture 

From J:215366 

NOTE: compare with HP ontology definition (http://www.human-phenotype-ontology.org/hpoweb/showterm?id=HP:0011359)
HP DEF: Hair that lacks the lustre (shine or gleam) of normal hair.

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2087](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2087)

**Comment by cindyJax** [comment]
dry hair MP:0014053
