### ISSUE TITLE
dry skin synonym

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#2088]
Please add skin xerosis as a new synonym of "dry skin [MP:0003853]".

Thanks

Anna

Reported by: anna_anagnos

Original Ticket: [obo/mammalian-phenotype-requests/2088](https://sourceforge.net/p/obo/mammalian-phenotype-requests/2088)

**Comment by cindyJax** [comment]
Synonym is added.
