### ISSUE TITLE
increased common myeloid progenitor cell number

### ISSUE THREAD

**Issue by MonikaTomczuk** [obophenotype/mammalian-phenotype-ontology#2089]
We have a decreased common myeloid progenitor cell number (MP:0008813) but not an increased term. In J:216746, mice have increased numbers of common myeloid progenitors so it would make sense to have the increased term. Can you add: increased common myeloid progentior cell number?

**Comment by cindyJax** [comment]
New term added:
increased common myeloid progenitor cell number  MP:0013891
