### ISSUE TITLE
increased common lymphocyte progenitor cell number

### ISSUE THREAD

**Issue by MonikaTomczuk** [obophenotype/mammalian-phenotype-ontology#2090]
In J:216746, mice have increased numbers of common lymphoid progenitor cells. Two other alleles come up when I search 'increase in common lymphocyte progenitor' so it looks like we have others (J:160090, 186700). So, I think it makes sense to add: increased common lymphocyte progenitor cell number as a child of MP:0008249: abnormal common lymphocyte progenitor cell morphology.

**Comment by cindyJax** [comment]
Added NTs:
increased common lymphocyte progenitor cell number  MP:0013892
decreased common lymphocyte progenitor cell number MP:0013893
