### ISSUE TITLE
abnormal behavioral response to amphetamine

### ISSUE THREAD

**Issue by sbello** [obophenotype/mammalian-phenotype-ontology#2092]
We have a term for response to methamphetamine but not one for the more general class of amphetamine. I would suggest adding a new term for abnormal behavioral response to amphetamine and making the existing term a child term. There are 4 existing annotations that could be moved to this term from the term abnormal behavioral response to addictive substance (MP:0009748). I'll also be adding at least 1 more from J:214739. Given the relation of amphetamine response to ADHD I think this is an important term to add.

**Comment by cindyJax** [comment]
ChEBI has the methamphetamine and amphetamine classes as siblings, so the methamphetamine term was not added as a subclass of the new term.

New term added:
abnormal behavioral response to amphetamine MP:0013894
