### ISSUE TITLE
eyelid cilium (eyelash) terms

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2093]
Please add:

abnormal eyelid cilium morphology
DEF: any structural anomaly of the hairs that grow at the edge of the upper or lower eyelid; eyelashes protect the eye from debris and are sensitive to touch, thus providing a warning that an object is near the eye (which is then closed reflexively)
SYN: abnormal eyelash morphology
SYN: abnormal eyelid cilia morphology
SYN: abnormal lash morphology

abnormal eyelid cilium number
DEF: anomaly in the number of the hairs that grow at the edge of the upper or lower eyelid
SYN: abnormal eyelash number
SYN: abnormal eyelid cilia number
SYN: abnormal lash number

decreased eyelid cilium number
DEF: reduction in the number of the hairs that grow at the edge of the upper or lower eyelid
SYN: decreased eyelash number
SYN: decreased eyelid cilia number
SYN: decreased lash number
From J:30747, J:13040

short eyelid cilia
DEF: decreased length of any of the hairs that grow at the edge of the upper or lower eyelid
SYN: decreased eyelash length
SYN: decreased eyelid cilium length
SYN: decreased eyelid cilia length
SYN: decreased lash length
From J:30747

Thanks

Anna

**Comment by cindyJax** [comment]
New terms added:
abnormal eyelid cilium morphology  MP:0013895
abnormal eyelid cilium number MP:0013896
decreased eyelid cilium number MP:0013897
short eyelid cilia MP:0013898
