### ISSUE TITLE
seminal vesicle epithelium 

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2095]
Please add:

abnormal seminal vesicle epithelium morphology
DEF: any structural anomaly of the pseudostratified columnar epithelium that lines the seminal vesicles and consists of tall, non-ciliated columnar cells and short, rounded basal cells that rest on the basal lamina; polarized columnar cells show features typical of secretory epithelium, including a well-developed Golgi complex, abundant rough endoplasmic reticulum, numerous mitochondria, and apical secretory vesicles; basal cells are the stem cells from which the columnar cells are derived 
SYN: abnormal gonecyst epithelium morphology 
SYN: abnormal seminal gland epithelium morphology

DEF COMPILED FROM: 
https://books.google.com/books?id=mhy0BQAAQBAJ&pg=PA399&lpg=PA399&dq=seminal+vesicle+epithelium+and+pseudostratified&source=bl&ots=aW4HEbNUzF&sig=stPpe9yVgp0_Vzo7ZYnV92aygoM&hl=en&sa=X&ved=0CFUQ6AEwCmoVChMI5-38rJTGxwIVyaCACh1XzACN#v=onepage&q=seminal%20vesicle%20epithelium%20and%20pseudostratified&f=false

https://books.google.com/books?id=FoSiGTXn6BUC&pg=PA751&lpg=PA751&dq=seminal+vesicle+epithelium+and+pseudostratified&source=bl&ots=H82lEPtUZZ&sig=v_26-bTOtlf6Qnw9npBtUme6rcg&hl=en&sa=X&ved=0CF4Q6AEwDGoVChMI5-38rJTGxwIVyaCACh1XzACN#v=onepage&q=seminal%20vesicle%20epithelium%20and%20pseudostratified&f=false

Then add:

seminal vesicle epithelium degeneration 
DEF: a retrogressive impairment of function or destruction of the pseudostratified columnar epithelium that normally lines the seminal vesicles and consists of tall, non-ciliated columnar cells and short, rounded basal (stem) cells that rest on the basal lamina 
SYN: gonecyst epithelium degeneration 
SYN: seminal gland epithelium degeneration 
From J:130791

Thanks

Anna

**Comment by cindyJax** [comment]
New terms added:
abnormal seminal vesicle epithelium morphology MP:0013899
seminal vesicle epithelium degeneration MP:0013900
