### ISSUE TITLE
absent female preputial gland

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2096]
Please add:

absent female preputial gland 
DEF: absence of the paired, lobulated, modified sebaceous glands located on the side of the clitoris in female rodents; in contrast to the preputial glands in male rodents, clitoral glands are a minor source of olfactory stimuli contributing to sexual attractivity; unlike other sebaceous glands, they undergo progressive atrophy of the glandular portion with marked ductal ectasia as rodents age; there is no true anatomical equivalent in humans 
SYN: absent clitoral gland

From J:47974 

Thanks

Anna

**Comment by cindyJax** [comment]
New term added:
absent female preputial gland  MP:0013901
