### ISSUE TITLE
abnormal seminal vesicle fluid composition

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2097]
Please consider adding:

abnormal seminal vesicle fluid composition
DEF: any alteration in the expected chemical makeup or appearance of the whitish yellow alkaline fluid secreted by the seminal vesicles that constitutes 60-70 % of the ejaculate in humans; the secretory product of the columnar epithelial cell, which may be seen in the lumen of seminal vesicles, is strongly acidophilic; it contains large amounts of fructose (used by spermatozoa as an energy source for motility) in addition to water, K+ ions, phosphorylcholine, prostaglandins, flavins, citrate, ascorbic acid, and several amino acids and enzymes; seminal vesicle fluid is responsible for coagulation of the ejaculate, can alter sperm motility and capacitation, and acts as an immunosuppressant in the female reproductive tract

From J:130791, J:68075
SOURCES:

http://www.lab.anhb.uwa.edu.au/mb140/corepages/malerepro/malerepro.htm#LabSeminal

https://books.google.com/books?id=FoSiGTXn6BUC&pg=PA751&lpg=PA751&dq=seminal+vesicle+epithelium+and+pseudostratified&source=bl&ots=H82lEPtUZZ&sig=v_26-bTOtlf6Qnw9npBtUme6rcg&hl=en&sa=X&ved=0CF4Q6AEwDGoVChMI5-38rJTGxwIVyaCACh1XzACN#v=onepage&q=seminal%20vesicle%20epithelium%20and%20pseudostratified&f=false

https://books.google.com/books?id=mhy0BQAAQBAJ&pg=PA399&lpg=PA399&dq=seminal+vesicle+epithelium+and+pseudostratified&source=bl&ots=aW4HEbNUzF&sig=stPpe9yVgp0_Vzo7ZYnV92aygoM&hl=en&sa=X&ved=0CFUQ6AEwCmoVChMI5-38rJTGxwIVyaCACh1XzACN#v=onepage&q=seminal%20vesicle%20epithelium%20and%20pseudostratified&f=false

https://en.wikipedia.org/wiki/Seminal_vesicle#Function

Thanks

Anna

**Comment by cindyJax** [comment]
New term added:
abnormal seminal vesicle fluid composition  MP:0013903
