### ISSUE TITLE
seminal vesicle muscle layer

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2098]
Please add:

abnormal seminal vesicle muscle layer morphology
DEF: any structural anomaly of the thick muscular layer of the seminal vesicle consisting of an inner circular and outer longitudinal layer of smooth muscle which contracts during the emission phase of ejaculation to expel seminal vesicle fluid into the prostatic urethra 
From J:137429, J:82767

Thanks

Anna

**Comment by cindyJax** [comment]
New term added:
abnormal seminal vesicle muscle layer morphology MP:0013904
