### ISSUE TITLE
abnormal seminal vesicle physiology

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2099]
Please add:

abnormal seminal vesicle physiology
DEF: any functional anomaly of the  sac-like glandular structures situated posterolateral to the urinary bladder in the male and functioning as part of the reproductive system; seminal vesicles secrete a whitish yellow alkaline fluid that constitutes 60-70 % of the ejaculate in humans; seminal vesicle fluid secretion is androgen-dependent, fructose-rich, and important for semen coagulation, sperm motility, and stability of sperm chromatin and suppression of the immune activity in the female reproductive tract
SYN: abnormal gonecyst physiology
SYN: abnormal seminal gland physiology

See also new issue #2097 

Thanks

Anna

**Comment by cindyJax** [comment]
New term added: 
abnormal seminal vesicle physiology  MP:0013902
