### ISSUE TITLE
abnormal cerebrospinal fluid flow

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2101]
Please add:

abnormal cerebrospinal fluid flow
SUGGESTED DEF: any anomaly in the dynamic process by which CSF circulates from the sites of secretion to the sites of absorption according to a unidirectional rostrocaudal flow in ventricular cavities and a multidirectional flow in subarachnoid spaces; CSF produced by the choroid plexuses in the lateral ventricles travels through interventricular foramina to the third ventricle, and then the fourth ventricle via the cerebral aqueduct and finally to the subarachnoid spaces via the median aperture (foramen of Magendie) of the fourth ventricle; in the cranial subarachnoid space, CSF circulates rostrally to the villous sites of absorption or caudally to the spinal subarachnoid space; CSF circulation through the ventricular system is driven by motile cilia on ependymal cells of the brain; CSF flow is pulsatile, corresponding to the systolic pulse wave in choroidal arteries; additional factors such as respiratory waves, the subject's posture, jugular venous pressure and physical effort also modulate CSF flow dynamics and pressure
SYN: abnormal cerebrospinal fluid circulation
SYN: abnormal CSF circulation
SYN: abnormal CSF flow
From J:211061

DEF SOURCES:

http://www.sciencedirect.com/science/article/pii/S1879729611001013

http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3848805/

Thanks

Anna

**Comment by cindyJax** [comment]
New term added:
abnormal cerebrospinal fluid flow MP:0013907
