### ISSUE TITLE
preputial gland inflammation

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2103]
Please add:

preputial gland inflammation
DEF: local accumulation of fluid, plasma proteins, and leukocytes in any of the paired, lobulated, modified sebaceous glands located in the inguinal region adjacent to the penis and vagina, with pheromonal functions in male rodents; in males, the preputial gland empties into the preputial cavity and in females, the preputial (aka clitoral) gland duct empties into the clitoral fossa
SYN: preputial inflammation

From J:211266 

Thanks

Anna

**Comment by cindyJax** [comment]
New term added:
preputial gland inflammation  MP:0013905
