### ISSUE TITLE
abnormal utricle hair cell morphology

### ISSUE THREAD

**Issue by sbello** [obophenotype/mammalian-phenotype-ontology#2104]
Consider adding a term for 
abnormal utricle hair cell morphology
child of abnormal utricle morphology (MP:0006090)
def: any structural anomaly of the sensory epithelial cells of the utricle
Phenotype in J:216288 and 3 existing annotations to the proposed parent.

**Comment by cindyJax** [comment]
These should be annotated to abnormal vestibular hair cell morphology [MP:0002623] and children.
