### ISSUE TITLE
abnormal blood–retinal barrier function

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2109]
Please add:

abnormal blood–retinal barrier function
DEF: anomaly in the function of the part of the blood-ocular barrier that consists of cells that are joined tightly together to prevent certain substances from entering the tissue of the retina; the BRB consists of non-fenestrated capillaries of the retinal circulation and tight-junctions between retinal epithelial cells preventing passage of large molecules from choriocapillaris into the retina; the BRB barrier becomes more leaky in patients with diabetic retinopathy
SYN: abnormal BRB function
From J:199483 

DEF SOURCE: https://en.wikipedia.org/wiki/Blood%E2%80%93retinal_barrier

Thanks

Anna

**Comment by cindyJax** [comment]
[GitHub]obophenotype/mammalian-phenotype-ontology/issues/1848

**Comment by cindyJax** [comment]
Per 1848, investigate relationship to MP:0010236 ! abnormal retina outer
limiting membrane morphology

**Comment by cindyJax** [comment]
Was previously added
MP:0014179
