### ISSUE TITLE
costovertebral joint and sternocostal joint

### ISSUE THREAD

**Issue by cindyJax** [obophenotype/mammalian-phenotype-ontology#2111]
Need terms for these joints [UBERON:0002292] and [UBERON:0001998], and need to consider whether existing terms 'abnormal rib-vertebral column attachment' [MP:0008149] and 'abnormal rib-sternum attachment' [MP:0008148] refer to the same entity

**Comment by sbello** [comment]
Looking at http://teachmeanatomy.info/thorax/bones/ribcage/ and http://www.scientificspine.com/spinal-anatomy/thoracic-spine-anatomy.html it appears that UBERON:0002292 is equivalent to  'rib-vertebral column attachment' in the MP term. The first source lists costotransverse joint and costovertebral joint as separate types of joints but UBERON has the costotransverse joint as a child of costovertebral joint.

**Comment by sbello** [comment]
Changed terms to joint terms from UBERON as is appears to me that rib attachment = rib joint in each case, added logical definitions to terms, 
new term:
abnormal costotransverse joint morphology MP:0020375
