### ISSUE TITLE
plasmablast

### ISSUE THREAD

**Issue by sbello** [obophenotype/mammalian-phenotype-ontology#2112]
We have at least 12 alleles that mention "plasmablast" in the notes. Most seem to be annotated to an immature B cell term (mostly number related terms from what I checked). I suggest adding a terms for plasmablasts, at the least a morphology term.
Plasmablast is in the Cell ontology (CL:0000980). The description includes that these develop from mature B cells so the current MGI annotations are incorrect. 

CL definition "An activated mature (naive or memory) B cell that is secreting immunoglobulin, typified by being CD27-positive, CD38-positive, CD138-negative."

Sue

**Comment by cindyJax** [comment]
New terms added:
abnormal plasmablast morphology MP:0013939
abnormal plasmablast number  MP:0013940
