### ISSUE TITLE
Problem with equivalence axiom for 'abnormal pterygoid muscle morphology'

### ISSUE THREAD

**Issue by cmungall** [obophenotype/mammalian-phenotype-ontology#2113]
```
'has part' some 
(morphology and ('inheres in' some 'medial pterygoid muscle') and ('inheres in' some 'lateral pterygoid muscle') and ('has modifier' some abnormal))
```

the abnormality can't be in both places at the same time (the latest version of uberon makes these two classes spatially distinct, so we're catching it)

**Comment by cmungall** [comment]
Same for absent:

```
'has part' some 
('lacks all parts of type' and ('inheres in' some mouth) and (towards some 'medial pterygoid muscle') and (towards some 'lateral pterygoid muscle') and ('has modifier' some abnormal))
```

just use [UBERON:0006720](http://purl.obolibrary.org/obo/UBERON_0006720) ! pterygoid muscle

**Comment by cindyJax** [comment]
Very odd.  I thought you can't make a double 'inheres in' ...
Fixed axiom for 'abnormal...' and also revised axiom for 'absent....', which had additional problems as well.
