### ISSUE TITLE
enthesitis

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2114]
Please add:

enthesitis

DEF: inflammation of the entheses, the sites where tendons or ligaments insert into the bone; the entheses are any point of attachment of skeletal muscles to the bone, where recurring stress or inflammatory autoimmune disease can cause inflammation or occasionally fibrosis and calcification
SYN: enthesopathy
SYN: pathologic condition involving the entheses

From  J:217720

DEF SOURCE: 
https://en.wikipedia.org/wiki/Enthesitis

Thanks

Anna

**Comment by cindyJax** [comment]
New term added
enthesitis MP:0013942
