### ISSUE TITLE
increased acute lymphoblastic leukemia incidence MP:0010336 children

### ISSUE THREAD

**Issue by sbello** [obophenotype/mammalian-phenotype-ontology#2115]
Consider adding B cell and T cell specific children for this term:
increased T cell acute lymphoblastic leukemia incidence
syn: increased T-ALL incidence
(8 annotations, with the ones I'm adding from J:216983) 

increased B cell acute lymphoblastic leukemia incidence
syn: increased B-ALL incidence
(3 annotations)

**Comment by cindyJax** [comment]
New terms added:

increased T cell acute lymphoblastic leukemia incidence MP:0014049

increased B cell acute lymphoblastic leukemia incidence  MP:0014050
