### ISSUE TITLE
error in OWL axioms for "absent trigeminal nerve connections to hindbrain"

### ISSUE THREAD

**Issue by cmungall** [obophenotype/mammalian-phenotype-ontology#2116]
this is wrong:

```
'has part' some 
    (absent
     and ('inheres in' some 
        ('trigeminal nerve'
         and ('part of' some hindbrain)))
     and ('has modifier' some abnormal))
```

nerves are part of the PNS, and the hindbrain is in the CNS

Also, it is wrong because the OWL says the nerve is absent. However, the nerves are present with this phenotype - it is the *connection* that is missing.

This is an interesting one to model. We don't represent "connections" as an entity as such in the AO. Would nerve roots do? In any case the golden rule is: if in doubt about axiomatization, leave the axiom off. Especially if it looks like it doesn't conform to a standard pattern. (maybe this is a v old axiom, I don't know)

this ticket originated here:
https://github.com/obophenotype/upheno/issues/147

**Comment by cindyJax** [comment]
This is likely a very old axiom, and one I don't recognize - and I agree it is wrong in several respects. Actually, the term itself is rather questionable.  I think it would be more appropriate to call this concept something like 'abnormal TG nerve innervation pattern to hindbrain' or something like that...
For now I will delete the axiom and then I will review this term for revision or obsolescence.
