### ISSUE TITLE
bad OWL axiom for absent trigeminal nerve

### ISSUE THREAD

**Issue by cmungall** [obophenotype/mammalian-phenotype-ontology#2117]
```
'has part' some 
    (absent
     and ('inheres in' some 
        ('trigeminal nerve'
         and ('part of' some cranium)))
     and ('has modifier' some abnormal))
```

nerves are not part of the cranium, the cranium is bone (nerves may pass through conduits in the cranium).

I'm not sure why this one isn't causing an incoherency in reasoning, I just noticed it because of #2116

**Comment by cindyJax** [comment]
Hmm- I think this is another v. old one, not sure.  I corrected this one and also for several other 'absent cranial nerve' terms.
