### ISSUE TITLE
increased/decreased length for intestines

### ISSUE THREAD

**Issue by mnk77** [obophenotype/mammalian-phenotype-ontology#2119]
Consider adding increased/decreased length terms for small intestines, large intestines and colon.

**Comment by cindyJax** [comment]
New terms added:

[Term]
id: MP:0013916
name: decreased intestine length

[Term]
id: MP:0013954
name: increased intestine length

[Term]
id: MP:0013955
name: increased colon length

[Term]
id: MP:0013956
name: decreased colon length

[Term]
id: MP:0013957
name: increased small intestine length

[Term]
id: MP:0013958
name: decreased small intestine length

[Term]
id: MP:0013959
name: increased large intestine length

[Term]
id: MP:0013960
name: decreased large intestine length
