### ISSUE TITLE
abnormal mitophagy

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2120]
Please add:

abnormal mitophagy as a child of "abnormal autophagy [MP:0008260]" and "abnormal mitochondrial physiology [MP:0006036]"
DEF: any anomaly in the autophagic process in which mitochondria are delivered to the vacuole and degraded in response to changing cellular conditions
SYN: abnormal mitochondrial autophagy
SYN: abnormal mitochondrion autophagy
J:214528 

Note: The definition above is based on GO:0000422
See below for additional information.

"Selective autophagy of mitochondria, known as mitophagy, is an important mitochondrial quality control mechanism that eliminates damaged mitochondria. Mitophagy also mediates removal of mitochondria from developing erythrocytes, and contributes to maternal inheritance of mitochondrial DNA through the elimination of sperm-derived mitochondria". 
SOURCE: Cell Death Differ. 2013 Jan; 20(1): 31–42. (http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3524633/)

Thanks

Anna

**Comment by cindyJax** [comment]
New term added:

abnormal mitophagy MP:0014046
