### ISSUE TITLE
Hensen stripe 

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2122]
Please add:

abnormal Hensen stripe morphology
DEF: any structural anomaly of the dark, nonstriated, V-shaped band (ridge) found on the underside of the tectorial membrane (TM) in the basal region of the cochlea, from which fine gelatinous trabeculae extend to fix the TM to the border cells, i.e. cells directly adjacent to the inner phalangeal cells; Hensen’s stripe is continuous with a more external homogeneous basal layer, from which a marginal band of an amorphous substance originates; the marginal net extends from the marginal band and attaches the lateral border of the TM to Hensen’s cells of the organ of Corti. Hensen’s stripe and the homogeneous basal layers display interruptions through which the fibrillar structure of the TM is visible
SYN: abnormal Hensen’s stripe morphology
 From J:203482 

absent Hensen stripe
DEF: absence of the dark, nonstriated, V-shaped band (ridge) that is normally found on the underside of the tectorial membrane (TM) in the basal region of the cochlea, from which fine gelatinous trabeculae extend to fix the TM to the border cells, i.e. cells directly adjacent to the inner phalangeal cells
SYN: absent Hensen’s stripe

From J:192263,  J:120765,  J:101691, J:215775

Definition compiled from J:215775 and https://books.google.com/books?id=AMzsCAAAQBAJ&pg=PA550&lpg=PA550&dq=hensen+cell+and+stripe&source=bl&ots=uF4zNiLWsV&sig=G70NJgzbaGluQAeXWusoqjB3aGI&hl=en&sa=X&ved=0CDQQ6AEwBGoVChMI8Omt7eq-yAIVwdKACh3JWAQs#v=onepage&q=hensen%20cell%20and%20stripe&f=false

Note: in  J:192263, absent Hensen’s stripe is incorrectly annotated to "abnormal Hensen cell morphology [MP:0004303]"

Thanks

Anna

**Comment by cindyJax** [comment]
New terms added:
abnormal Hensen stripe morphology MP:0013961
absent Hensen stripe  MP:0013962
