### ISSUE TITLE
NTR: abnormal submucosal gland secretion

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/mammalian-phenotype-ontology#2124]
NTR: abnormal submucosal gland secretion
Parent: MP_0013559 abnormal exocrine gland physiology
def: abnormal secretion of fluid secretion from the submucosal gland
logical def: 
'has part' some 
(quality
and ('inheres in' some 
('fluid secretion'
and ('part of' some 'submucosal gland')))
and ('has modifier' some abnormal))

NTR: decreased submucosal gland secretion
parent: abnormal submucosal gland secretion
def: decreased secretion of fluid secretion from the submucosal gland
logical def: 
'has part' some 
('decreased rate'
and ('inheres in' some 
('fluid secretion'
and ('part of' some 'submucosal gland')))
and ('has modifier' some abnormal))

**Comment by cindyJax** [comment]
Submucosal glands secrete mucus, not fluid, so better to use GO term 'mucus secretion' on logical def and use 'mucus' instead of 'fluid' in text definition

**Comment by nicolevasilevsky** [comment]
sounds good!

**Comment by cindyJax** [comment]
New terms added:
abnormal submucosal gland secretion MP_0014034
decreased submucosal gland secretion MP_0014035
