### ISSUE TITLE
NTR: Meconium ileus

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/mammalian-phenotype-ontology#2125]
Parent: MP_0011082 abnormal gastrointestinal motility
def: Obstruction of the intestine due to abnormally thick meconium.
def xref: orcid.org/0000-0001-5208-3432, HPO:probinson
has_related_synonym: Distal intestinal obstruction syndrome
has_related_synonym: Meconium ileus on ultrasonography

(note- this the same as the HPO term, HP_0004401)

**Comment by cindyJax** [comment]
New term added:
meconium ileus	MP_0014036
