### ISSUE TITLE
abnormal peroxisome morphology

### ISSUE THREAD

**Issue by sbello** [obophenotype/mammalian-phenotype-ontology#2128]
Please consider adding the term 
abnormal peroxisome morphology
child of  abnormal cell morphology	MP:0000358
phenotype in J:217065 and 8 existing annotations
see GO:0005777 for peroxisome definition

**Comment by sbello** [comment]
J:217065 also reports this phenotype for a human patient

**Comment by cindyJax** [comment]
New term added:
abnormal peroxisome morphology MP:0014010
