### ISSUE TITLE
absent cardiac outflow tract

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2131]
Please consider adding:

absent cardiac outflow tract

DEF: absence of or complete failure to form the common arterial trunk that normally forms the aorta and pulmonary artery and the ventricular outflow regions
SYN: absent fetal outflow tract 
SYN: absent heart outflow tract 

From J:215128, J:109474, J:95093

Also, consider adding "cardiac" to existing term label "abnormal outflow tract development [MP:0006126]"

Thanks

Anna

**Comment by cindyJax** [comment]
New term added:
absent cardiac outflow tract	MP:0014044
