### ISSUE TITLE
New Term Request: Bone Mineral Content

### ISSUE THREAD

**Issue by Vancollie** [obophenotype/mammalian-phenotype-ontology#2132]
Hello,

Could we please get 2 new terms added somewhere around the branch 'abnormal bone mineral content' (MP:0010122)? The 2 we'd like are:
increased subchondral bone mineral content = elevation in subchondral bone mineral content
decreased subchondral bone mineral content = reduction in subchondral bone mineral content

Both are going to be looked at by a collaborator of the Sanger MGP.

Cheers,
Valerie

**Comment by cindyJax** [comment]
New terms added:
increased subchondral bone mineral content   MP:0014024
increased subchondral bone mineral content  MP:0014025
