### ISSUE TITLE
Possible New Term: Mallory Body

### ISSUE THREAD

**Issue by MonikaTomczuk** [obophenotype/mammalian-phenotype-ontology#2134]
I've come across Mallory body several times (and found five annotations with Mallory) and am wondering if it should be a new term. Based on the wiki definition:
Mallory body: damaged intermediate filaments within the hepatocytes. They are inclusions in the cytoplasm of liver cells.
synonym: Mallory-Denk body, Mallory's hyaline
child under maybe abnormal hepatocyte morphology? or under abnormal liver morphology? I'm not sure if they are limited to only the hepatocytes. 
Reference: J:90905

Thanks,
Monika

**Comment by cindyJax** [comment]
New term added:
Mallory bodies MP:0014045
