### ISSUE TITLE
tectorial membrane terms

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2141]
Please add:

abnormal Kimura membrane morphology as a child of "abnormal tectorial membrane morphology [MP:0003149]"
DEF: any structural anomaly of the thickening of the lower surface of the tectorial membrane into which the hair bundles of the outer hair cells are imbedded
J:160851, J:203482, J:101691

abnormal tectorial membrane marginal band morphology
DEF: any structural anomaly of the dense thickening of the lateral edge of the tectorial membrane

abnormal tectorial membrane covernet morphology
DEF: any structural anomaly of the anastomosing network of large caliber fibrils that run predominantly longitudinally over the upper surface of the tectorial membrane; in mice, the covernet fibrils are continuous with the underlying striated-sheet matrix of the TM, and appear as electron-dense rods that can be a micron or more in diameter

abnormal tectorial membrane striated-sheet matrix morphology
DEF: any structural anomaly of the laminated, striated-sheet matrix within which collagen fibrils of the TM are imbedded; the striated sheet matrix is formed by two types of fine-diameter collagen filaments, a light and a dark staining type that lie in parallel within the plane of each sheet and are extensively linked along their length by staggered cross bridges; it originates medially within the sulcal zone, extends to the marginal band and is particularly evident in apical regions of the cochlea, where it has a less compressed appearance
J:215775 

DEF SOURCES
Hum Mol Genet. 2014 May 15;23(10):2551-68. doi: 10.1093/hmg/ddt646. Epub 2013 Dec 20.

Curr Opin Otolaryngol Head Neck Surg. 2008 Oct;16(5):458-64. doi: 10.1097/MOO.0b013e32830e20c4.

Thanks

Anna

**Comment by cindyJax** [comment]
New terms added
abnormal Kimura membrane morphology  MP:0014088
abnormal tectorial membrane marginal band morphology MP:0014089
abnormal tectorial membrane covernet morphology MP:0014090
abnormal tectorial membrane striated-sheet matrix morphology MP:0014091

-----
PMID:24363064
PMID:18797289
