### ISSUE TITLE
chondrocyte physiology terms

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2142]
Please consider adding the following:

abnormal chondrocyte proliferation (plus increased and decreased child terms thereof)

abnormal chondrocyte apoptosis (plus increased and decreased child terms thereof )

abnormal chondrocyte differentiation (plus delayed AND premature chondrocyte differentiation child terms thereof)

Consult GO for term definitions.

NOTE: remove "abnormal chondrocyte differentiation" from the list of synonyms for "abnormal osteoclast differentiation [MP:0008396]"

Thanks

Anna

**Comment by cindyJax** [comment]
1) 'chondrocyte' was removed as a synonym from several 'osteoclast' terms, and replaced with 'chondroclast' in most cases.
2) New terms added:
abnormal chondrocyte proliferation  MP:0014099
increased chondrocyte proliferation  MP:0014100
decreased chondrocyte proliferation  MP:0014101
abnormal chondrocyte apoptosis  MP:0014102
increased chondrocyte apoptosis  MP:0014103
decreased chondrocyte apoptosis  MP:0014104
abnormal chondrocyte differentiation MP:0014105
delayed chondrocyte differentiation  MP:0014106
premature chondrocyte differentiation MP:0014107
