### ISSUE TITLE
behavioral inflexibility

### ISSUE THREAD

**Issue by aliciavalenzuela** [obophenotype/mammalian-phenotype-ontology#2143]
J229005 - behavioral inflexibility/flexibility - I've come across this before and googling the term brings in lots of references in mice.  In this reference, inflexibility is determined by the no alterations T maze.
Wiki defines cognitive flexibility as the mental ability to switch between thinking about two different concepts, and to think about multiple concepts simultaneously. In the meantime, I'm putting it under abnormal emotion/affect behavior.

**Comment by cindyJax** [comment]
Added new term:
cognitive inflexibility  MP:0014115
