### ISSUE TITLE
tear production synonyms

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2146]
Please consider adding the following as synonyms of "abnormal tear production [MP:0020218]"

NEW SYN: abnormal lacrimation
NEW SYN: abnormal lachrymation
NEW SYN: abnormal tear secretion
NEW SYN: lacrimation abnormality
NEW SYN: lachrymation abnormality

increased tear production [MP:0020219]
NEW SYN: increased lacrimation
NEW SYN: increased lachrymation
NEW SYN: increased tear secretion
NEW SYN: hyperlacrimation
NEW SYN: hyperlachrymation

decreased tear production [MP:0020220]
NEW SYN: decreased lacrimation
NEW SYN: decreased lachrymation
NEW SYN: decreased tear secretion
NEW SYN: reduced lacrimation
NEW SYN: reduced lachrymation
NEW SYN: reduced tear production
NEW SYN: reduced tear secretion
NEW SYN: hypolacrimation
NEW SYN: hypolachrymation

**NOTE:** excessive tearing [MP:0001349] should be a child of increased tear production [MP:0020219]
NEW SYN: excessive lacrimation
NEW SYN: excessive lachrymation
NEW SYN: watering eye

Thanks

Anna

**Comment by cindyJax** [comment]
Added synonyms
