### ISSUE TITLE
alacrima

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2147]
Please add:

alacrima
DEF: absence of tear production; may occur in association with other disorders or as an isolated congenital defect
SYN: absence of lacrimal fluids
SYN: absence of lachrymal fluids
SYN: absence of tear secretion
SYN: absence of tears

Thanks

Anna

**Comment by cindyJax** [comment]
alacrima MP:0014157
