### ISSUE TITLE
lacrimal gland hypo- and hyperplasia

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2148]
Please add:

lacrimal gland hypoplasia
DEF: underdevelopment or reduced size, usually due to a decreased number of cells, of the glands that secrete tears
SYN: hypoplastic lachrymal glands
SYN: hypoplastic lacrimal glands
SYN: lachrymal gland hypoplasia

lacrimal gland hyperplasia
DEF: overdevelopment or increased size, usually due to an increased number of cells, of the glands that secrete tears
SYN: hyperplastic lachrymal glands
SYN: hyperplastic lacrimal glands
SYN: lachrymal gland hyperplasia

Thanks

Anna

**Comment by cindyJax** [comment]
lacrimal gland hyperplasia   MP:0014150
lacrimal gland hypoplasia   MP:0014151
