### ISSUE TITLE
circulating cortisol levels

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2149]
Please add:

abnormal circulating cortisol level
DEF: any anomaly in the blood concentration of the principal glucocorticoid produced by the zona fasciculata of the adrenal cortex within the adrenal gland; cortisol is released in response to stress and a low level of blood glucose; it functions to increase blood sugar through gluconeogenesis, to suppress the immune system, and to aid the metabolism of fat, protein, and carbohydrate; it also decreases bone formation

increased circulating cortisol level
DEF: greater than the normal blood concentration of the principal glucocorticoid produced by the zona fasciculata of the adrenal cortex within the adrenal gland and released in response to stress and a low level of blood glucose
 SYN: increased plasma cortisol level 
SYN: increased serum cortisol level 
J:57493

decreased circulating cortisol level
DEF: less than the normal blood concentration of the principal glucocorticoid produced by the zona fasciculata of the adrenal cortex within the adrenal gland and released in response to stress and a low level of blood glucose
 SYN: decreased plasma cortisol level 
SYN: decreased serum cortisol level 
J:97284

DEF: SOURCE: https://en.wikipedia.org/wiki/Cortisol

Thanks

Anna

**Comment by cindyJax** [comment]
abnormal circulating cortisol level   MP:0014160
increased circulating cortisol level   MP:0014161
decreased circulating cortisol level   MP:0014162
