### ISSUE TITLE
ciliary body, muscle and processes

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2150]
Please consider modifying the definition of "abnormal ciliary body morphology [MP:0005099]" to read as:

"abnormal ciliary body morphology [MP:0005099]"
DEF: any structural anomaly of the thickened portion of the vascular tunic, which lies between the choroid and the iris, and is made up of the ciliary muscle and the ciliary processes; the processes radiate from the ciliary muscle and give attachments to ligaments supporting the lens of the eye

Then add:

abnormal ciliary muscle morphology
DEF: any structural anomaly of the ring of smooth muscle in the eye's vascular layer that forms the main part of the ciliary body, controls accommodation for viewing objects at varying distances, and regulates the flow of aqueous humor into the canal of Schlemm
SYN: abnormal musculus ciliaris morphology
SYN: abnormal Bowman muscle morphology
SYN: abnormal ciliary ligament morphology
J:178103

SOURCE: 
https://en.wikipedia.org/wiki/Ciliary_muscle
http://medical-dictionary.thefreedictionary.com/ciliary+muscle

abnormal ciliary process morphology
DEF: any structural anomaly of any of the pigmented processes that radiate from the ciliary muscle and give attachments to ligaments supporting the lens of the eye; these processes increase in thickness as they advance from the orbiculus ciliaris to the external border of the iris, and together with the folds (plicae) in the furrows between them, constitute the corona ciliaris; ciliary processes produce aqueous humor
SYN: abnormal processus ciliaris morphology
J:194085,  J:144313, J:61775, J:37067

SOURCE: http://www.medilexicon.com/medicaldictionary.php?s=processus+ciliaris

absent ciliary process
DEF: absence or loss of any of the pigmented processes that radiate from the ciliary muscle and give attachments to ligaments supporting the lens of the eye; ciliary processes produce aqueous humor
J:52989, J:101707

Thanks

Anna

**Comment by cindyJax** [comment]
abnormal ciliary muscle morphology  MP:0014163
abnormal ciliary process morphology  MP:0014164
absent ciliary process MP:0014165
