### ISSUE TITLE
Meibomian gland degeneration

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2151]
Please add:

Meibomian gland degeneration
DEF: a retrogressive impairment of function or destruction of the meibum-secreting modified lobulated sebaceous glands located at the rim of the eyelids inside the tarsal plate
SYN: tarsal gland degeneration
J:194073

Thanks

Anna

**Comment by cindyJax** [comment]
Meibomian gland degeneration   MP:0014154
