### ISSUE TITLE
lacrimal gland degeneration

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2152]
Please add:

lacrimal gland degeneration
DEF: a retrogressive impairment of function or destruction of the tubuloacinar exocrine glands that secrete the aqueous layer of the tear film (tears); mice have two lacrimal glands (intra- and exorbital)
SYN: lachrymal gland degeneration
J:194073

Thanks

Anna

**Comment by cindyJax** [comment]
MP:0014148
