### ISSUE TITLE
absent intra- and exorbital lacrimal gland

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2153]

**Comment by anna-anagnostop** [comment]
Please add:

absent exorbital lacrimal gland
DEF: absence of the large extra-orbital lacrimal gland that, in mice, is normally located subcutaneously at the anteroventral base of the ear adjacent to the parotid gland
SYN: absent exorbital lachrymal gland
SYN: absent extra-orbital lachrymal gland
SYN: absent extra-orbital lacrimal gland
J:72517

absent intraorbital lacrimal gland 
DEF: absence of the small intra-orbital lacrimal gland that, in mice, is normally located superficially at the lateral canthus, where both the lacrimal gland and Harderian gland ducts open
SYN: absent intraorbital lachrymal gland 
SYN: absent intra-orbital lachrymal gland
SYN: absent intra-orbital lacrimal gland
J:107208

Thanks

Anna

**Comment by cindyJax** [comment]
absent exorbital lacrimal gland   MP:0014152
absent intraorbital lacrimal gland    MP:0014153
