### ISSUE TITLE
abnormal lacrimal gland innervation

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2154]
Please add:

abnormal lacrimal gland innervation
DEF: any structural anomaly of the supply of nerve fibers that connect to the tubuloacinar exocrine glands that secrete the aqueous layer of the tear film (tears)
J:53261

For detail see: https://en.wikipedia.org/wiki/Lacrimal_gland

Thanks

Anna

**Comment by cindyJax** [comment]
abnormal lacrimal gland innervation pattern   MP:0014149
