### ISSUE TITLE
logical def of 'ectopic cranial bone growth'

### ISSUE THREAD

**Issue by drseb** [obophenotype/mammalian-phenotype-ontology#2159]
```
'has part' some 
(mislocalised 
 and ('inheres in' some 'organ growth') 
 and ('has modifier' some abnormal) 
 and ('occurs in' some cranium))
```

*organ growth* is a process, but mislocalised is a *physical quality*

**Comment by cindyJax** [comment]
This is a very old term and it is not clear what this means textually or logically...
In the MGI annotation usage, it is always used to mean 'ectopic cranial bone'
I will create a new term and deprecate this one.

NT:
'ectopic cranial bone'    MP:0014166

'has part' some 
(mislocalised 
 and ('inheres in' some 'cranial bone')
 and ('has modifier' some abnormal))

**Comment by cindyJax** [comment]
'ectopic cranial bone growth' has been deprecated.
