### ISSUE TITLE
fatty acid oxidation

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2160]
Please consider adding both increased and decreased children terms for "abnormal fatty acid oxidation [MP:0010953]" and "abnormal fatty acid beta-oxidation [MP:0010952]".

Thanks

Anna

**Comment by cindyJax** [comment]
New terms added:
increased fatty acid oxidation  MP_0014171
decreased fatty acid oxidation  MP_0014172
increased fatty acid beta-oxdation  MP_0014173
decreased fatty acid beta-oxdation  MP_0014174
