### ISSUE TITLE
ciliary epithelium 

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2161]
Please add:

abnormal ciliary epithelium morphology
DEF: any structural anomaly of the double layer lining the inner surfaces of the ciliary processes and the pars plana (i.e. the posterior portion of the ciliary body, aka orbicularis ciliari); the outer layer is the pigmented epithelium, which is composed of low cuboidal cells and is adjacent to the stroma and continuous with the retinal pigmented epithelium; the inner layer is formed by non-pigmented epithelium, a columnar epithelium, adjacent to the aqueous humor in the posterior chamber and continuous with the retina; these two layers of the epithelium are appositioned in their apical surfaces

DEFINITION SOURCE: http://cdn.intechopen.com/pdfs-wm/41830.pdf

Thanks

Anna

**Comment by cindyJax** [comment]
New term added: 
abnormal ciliary epithelium morphology   MP:0014175
