### ISSUE TITLE
ciliary zonule 

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2162]
Please add:

SUGGESTED DEF: any structural anomaly of the circumferential suspensory ligaments that anchor the lens to the ciliary process and are made of bundles of fibrillin microfibrils, an elaborate system of fibers that spans the gap between the lens and the adjacent nonpigmented ciliary epithelium; this fibrous rigging ensures lens centration; in species that accommodate, the zonule transmits the forces that flatten the lens, allowing the eye to focus on distant objects
J:214736

SYNONYMS
abnormal apparatus suspensorius lentis morphology
abnormal suspensory ligament of lens morphology
abnormal Zinn zonule morphology
abnormal Zinn's zonule morphology
abnormal  zonula ciliaris morphology

Definition compiled from http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3621578/ and J:214736 (page 5674)

Synonyms obtained from http://www.medilexicon.com/medicaldictionary.php?t=100545

NOTE: UBERON:0006762 uses “suspensory ligament of lens” as the primary term name and includes “zinn's membrane” as a synonym. Wiktionary also includes Zinn's membrane as a synonym (https://en.wiktionary.org/wiki/ciliary_zonule); however, Zinn's membrane is defined as “the anterior layer of the iris” (http://www.medilexicon.com/medicaldictionary.php/?t=54035)

Thanks

Anna

**Comment by cindyJax** [comment]
New term added 
abnormal ciliary zonule morphology MP:0014176
