### ISSUE TITLE
increased brain apoptosis

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2163]
Please add:

increased brain apoptosis
DEF: increase in the number of cells of the brain undergoing programmed cell death
J:225666 
Thanks
Anna

**Comment by cindyJax** [comment]
MP:0014178  but modified to 'increased brain cell apoptosis' 
Looked at the reference to see if this term could be made more specific, but apparently not.

**Comment by cindyJax** [comment]
Actually, on second thought, modified the label back to 'increased brain apoptosis'
