### ISSUE TITLE
epididymis hypertrophy

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2166]
Please add:

epididymis hypertrophy
DEF: increase in the bulk size of the elongated structure connected to the posterior surface of the testis that transports, stores, and matures spermatozoa between testis and vas deferens due to cell enlargement
SYN: epididymal hypertrophy
SYN: hypertrophic epididymis
J:220689

Thanks

Anna

**Comment by cindyJax** [comment]
MP:0014186
