### ISSUE TITLE
spermatocele

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2167]
Please add:

spermatocele
DEF: a retention cyst of a tubule of the rete testis or the head of the epididymis distended with barely watery fluid that contains spermatozoa
SYN: spermatocyst

J:220689

DEF SOURCES:

https://en.wikipedia.org/wiki/Spermatocele

http://medical-dictionary.thefreedictionary.com/spermatocyst

Thanks

Anna

**Comment by cindyJax** [comment]
MP:0014187
