### ISSUE TITLE
testis and epididymis fibrosis

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2168]
Please add:

1. testis fibrosis
DEF: invasion of fibrous connective tissue into the testis, often resulting from inflammation or injury
SYN: testicular fibrosis

2. epididymis fibrosis
DEF: invasion of fibrous connective tissue into the epididymis, often resulting from inflammation or injury
SYN: epididymal fibrosis
J:220689

Thanks

Anna

**Comment by cindyJax** [comment]
1. MP:0014189  testis fibrosis
2. MP:0014188  epididymis fibrosis
