### ISSUE TITLE
epididymis physiology terms

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2169]
Please add:

abnormal epididymis physiology
DEF: any functional anomaly of the elongated structure connected to the posterior surface of the testis that transports, stores, and matures spermatozoa between testis and vas deferens
SYN: abnormal epididymal physiology

abnormal epididymal cell proliferation
DEF: anomaly in the expansion rate of any epididymal cell population by cell division

increased epididymal cell proliferation
DEF: increase in the expansion rate of any epididymal cell population by cell division
J:220689

decreased epididymal cell proliferation
DEF: decrease in the expansion rate of any epididymal cell population by cell division
SYN: reduced epididymal cell proliferation

increased epididymal epithelium cell proliferation
DEF: increase in the expansion rate of the cells of the epididymal epithelium by cell division
J:220689

Thanks

Anna

**Comment by cindyJax** [comment]
abnormal epididymis physiology   MP:0014190
abnormal epididymal cell proliferation   MP:0014191
increased epididymal cell proliferation   MP:0014192
decreased epididymal cell proliferation   MP:0014193
increased epididymal epithelium cell proliferation   MP:0014194
