### ISSUE TITLE
abnormal Sertoli cell barrier morphology 

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2170]

**Comment by anna-anagnostop** [comment]
I FORGOT TO PROVIDE THE DESCRIPTION!!!

Please add:

abnormal Sertoli cell barrier morphology
DEF: any structural anomaly of the physical barrier found between adjacent Sertoli cells within the seminiferous tubules; the SCB barrier consists of several types of cellular junctions including tight junctions, gap junctions and adhesion junctions, and divides the seminiferous tubules into the basal and apical (adluminal) compartments; meiosis, spermiogenesis and spermiation take place in the apical compartment; whereas, spermatogonial cell division and differentiation to preleptotene spermatocytes occur in the basal compartment; thus, SCB creates a unique microenvironment for meiotic and postmeiotic cells by forming an immunological barrier that separates meiotic and postmeiotic germ cells from blood circulation

SYN: abnormal BTB morphology
SYN: abnormal blood-testis barrier morphology
SYN: abnormal SCB morphology

J:213588

SOURCE: http://www.ajandrology.com/article.asp?issn=1008-682X;year=2014;volume=16;issue=4;spage=572;epage=580;aulast=Jiang

Thanks

Anna

**Comment by sbello** [comment]
MP:0020355
