### ISSUE TITLE
abnormal Sertoli cell barrier function

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2171]
Please add:

abnormal Sertoli cell barrier function
DEF: any functional anomaly of the physical barrier found between the blood vessels and the seminiferous tubules of the testes; the presence of SCB allows Sertoli cells to control the adluminal environment in which germ cells (spermatocytes, spermatids and sperm) develop by influencing the chemical composition of the luminal fluid; SCB also prevents passage of cytotoxic agents into the seminiferous tubules, protects germ cells from blood-borne noxious agents, and prevents antigenic products of germ cell maturation from entering the circulation; altered permeability of the SCB may result in the release of germ cells in the bloodstream, leading to the mounting of an autoimmune response and the production of anti-sperm antibodies
SYN: abnormal BTB function 
SYN: abnormal blood-testis barrier function
SYN: abnormal SCB function

J:213588

SOURCE: https://en.wikipedia.org/wiki/Blood%E2%80%93testis_barrier

Thanks

Anna

**Comment by sbello** [comment]
MP:0020356
Current annotations I could find are under Sertoli cell morphology
