### ISSUE TITLE
increased antisperm antibody level 

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2172]
Please add: 

increased antisperm antibody level 
DEF: elevated level of antibodies to sperm antigens, usually due to compromised Sertoli cell barrier (blood-testis barrier) function; ASAs may be found in the circulation, either free or as immune complexes, in seminal fluid and/or attached to various antigenic sites on the sperm surface (head, midpiece or tail)
SYN: increased anti-sperm antibody level 
SYN: increased ASA level

J:213588

Thanks

Anna

**Comment by sbello** [comment]
MP:020142
