### ISSUE TITLE
brain external capsule terms

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2174]
Please add:

abnormal brain external capsule morphology
DEF: any structural anomaly of the series of white matter fiber tracts in the brain that run between the most lateral segment of the lentiform nucleus and the claustrum; the white matter of the external capsule contains fibers known as corticocortical association fibers which are responsible for connecting the cerebral cortex to another cortical area; the capsule appears as a thin white sheet of white matter and provides a route for cholinergic fibers from the basal forebrain to the cerebral cortex; it eventually joins the internal capsule around the lentiform nucleus

DEF SOURCE: https://en.wikipedia.org/wiki/External_capsule

Then, add terms for (i) increased (J:214959) and (ii) decreased brain external capsule size.

Thanks

Anna

**Comment by sbello** [comment]
abnormal MP:0020139
increased MP:0020140
decreased MP:0020141

**Comment by cmungall** [comment]
Add MP:0020139 is_a MP:0008026 ! abnormal brain white matter morphology

(inference from Uberon)

**Comment by sbello** [comment]
Done, thanks for catching this Chris. We're still working on getting the reasoner set up for me.
