### ISSUE TITLE
abnormal vascular endothelial cell physiology terms

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2177]
Please consider adding the following as child terms of "abnormal vascular endothelial cell physiology [MP:0004003]"

1. abnormal vascular endothelial cell proliferation
1a. increased vascular endothelial cell proliferation
1b. decreased vascular endothelial cell proliferation

2. abnormal vascular endothelial cell adhesion
2a. increased vascular endothelial cell adhesion
2b. decreased vascular endothelial cell adhesion

3. abnormal vascular endothelial cell apoptosis
3a. increased vascular endothelial cell apoptosis
3b. decreased vascular endothelial cell apoptosis

Thanks

Anna

**Comment by sbello** [comment]
1 MP:0020146
1a MP:0020161
1b MP:0020316

2 MP:0020317
2a MP:0020318
2b MP:0020319

3 MP:0020320
3a MP:0020321
3b MP:0020322
