### ISSUE TITLE
jejunum polyps

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2179]
Please add:

jejunum polyps as a child of "intestine polyps [MP:0008011]"
DEF: development of numerous growths that are connected to and protrude from the mucous membrane of the jejunum
SYN: jejunal polyposis
SYN: jejunal polyps
SYN: jejunum polyposis

J:220874 

Thanks

Anna

**Comment by sbello** [comment]
MP:0020324
