### ISSUE TITLE
altered/defective glymphatic system

### ISSUE THREAD

**Issue by aliciavalenzuela** [obophenotype/mammalian-phenotype-ontology#2182]
Suppression of glymphatic fluid transport in a mouse model of Alzheimer's disease.
Peng W, Achariyar TM, Li B, Liao Y, Mestre H, Hitomi E, Regan S, Kasper T, Peng S, Ding F, Benveniste H, Nedergaard M, Deane R.
Neurobiol Dis. 2016 May 24. pii: S0969-9961(16)30109-7. doi: 10.1016/j.nbd.2016.05.015. [Epub ahead of print]
PMID: 27234656 [PubMed - as supplied by publisher]

**Comment by sbello** [comment]
see http://rd.springer.com/article/10.1007%2Fs11064-015-1581-6
https://www.urmc.rochester.edu/labs/Nedergaard-Lab/projects/glymphatic_system

**Comment by sbello** [comment]
request submitted to UBERON for a new anatomy term

**Comment by sbello** [comment]
UBERON:0036145
MP:0020365 - morphology
MP:0020366 - physiology
waiting for UBERON release to create logical definition

**Comment by sbello** [comment]
Due to some build issues I had to remove and replace these terms. New IDs are:
MP:0020370 - morphology
MP:0020371 - physiology

**Comment by cmungall** [comment]
in http://uberon.github.io/release/2016/09/07/release.html

```
id: UBERON:0036145
name: glymphatic system
```

note: the ontology purl will not be updated til ~midnight. OLS etc 
should follow in a few days

Additional notes here:
https://github.com/obophenotype/uberon/issues/1260
