### ISSUE TITLE
Toward vs. towars

### ISSUE THREAD

**Issue by mnk77** [obophenotype/mammalian-phenotype-ontology#2184]
Just a consistency issue... 

Sometimes we use toward:
aggression toward inanimate objects
increased aggression toward humans

Sometimes towards:
decreased aggression towards males
decreased aggression towards mice
increased aggression towards females
increased aggression towards males
increased aggression towards males in competition for females
increased aggression towards mice
submission towards male mice

My understanding is that American English favors toward while British English favors towards (see http://www.quickanddirtytips.com/education/grammar/toward-versus-towards)

**Comment by sbello** [comment]
As all but one MP term used "towards" I changed "increased aggression toward humans" to "increased aggression towards humans"
