### ISSUE TITLE
new synonyms: increased/decreased femur length

### ISSUE THREAD

**Issue by cindyJax** [obophenotype/mammalian-phenotype-ontology#2186]
Please add as synonyms:

increased femur length to [MP:0004348] long femur

decreased femur length to [MP:0003109] short femur

May also want to add similar synonyms to other bone terms (fibula, tibia, radius, ulna, etc)

**Comment by sbello** [comment]
Done for femur, ulna, radius, humerus, fibula, tibia, incisors, outer ears, gestation, hair, limb, mandible, maxilla, nasal bone, zygomatic bone, malleus, nails, rib, sternum, snout, toenails, sperm flagellum, vertebral body, vertebral column
