### ISSUE TITLE
obsolete MP:0005395, 	MP:0002168

### ISSUE THREAD

**Issue by cindyJax** [obophenotype/mammalian-phenotype-ontology#2193]
obsolete MP:0005395, 	MP:0002168
No longer needed.

**Comment by sbello** [comment]
Done

**Comment by sbello** [comment]
This is causing issues with the MP load so I'm putting the other system header back in until we can put a TR in to remove 'Other' from the system completely. 
The term 'Other' is coded in:
system selection pick list

**Comment by sbello** [comment]
Obsoleted again. Causing some issues in the HMDC but nothing too severe
