### ISSUE TITLE
Decreased vocalization

### ISSUE THREAD

**Issue by MonikaTomczuk** [obophenotype/mammalian-phenotype-ontology#2197]
I'd like to request a 'decreased or reduced vocalization" term. Def. producing sound from the vocal organs less frequently or less loudly than expected (based on the definition for excessive vocalization). Parent term is MP:0001529, abnormal vocalization. In J:228203, mice emit fewer ultrasonic calls than wild-type mice. 
Thanks,
Monika

**Comment by sbello** [comment]
MP:0020351
