### ISSUE TITLE
 intestinal iron level terms

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2204]
Please consider splitting abnormal intestinal iron level [MP:0008740] into increased and decreased child terms

increased intestinal iron level
DEF: increase in the amount of iron present in the large or small intestinal tissue

decreased intestinal iron level
DEF: reduction in the amount of iron present in the large or small intestinal tissue
SYN: reduced intestinal iron level

Thanks!

Anna

**Comment by sbello** [comment]
MP:0020369 - increased
MP:0020385 - decreased
