### ISSUE TITLE
heart iron level terms

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2205]
Please consider splitting abnormal heart iron level [MP:0008741] into increased and decreased child terms

increased heart iron level
DEF: increase in the amount of iron present in the heart tissue
SYN: increased cardiac iron level

decreased heart iron level
DEF: reduction in the amount of iron present in the heart tissue
SYN: decreased cardiac iron level
SYN: reduced cardiac iron level
SYN: reduced heart iron level

Thanks!

Anna

**Comment by sbello** [comment]
MP:0020367 - increased
MP:0020368 - decreased
