### ISSUE TITLE
brain iron level terms

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2206]
Please consider splitting abnormal brain iron level [MP:0008811] into increased and decreased child terms

increased brain iron level
DEF: increase in the amount of iron present in the brain tissue

decreased brain iron level
DEF: reduction in the amount of iron present in the brain tissue
SYN: reduced brain iron level

Thanks!

Anna

**Comment by sbello** [comment]
MP:0020366 decreased
MP:0020365 increased
