### ISSUE TITLE
abnormal pancreas iron level [MP:0013301]

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2207]
Amend definition of abnormal pancreas iron level [MP:0013301] to read as:

anomaly in the amount of iron present in the pancreas tissue
NEW SYN: abnormal pancreatic iron level

Thanks!

Anna

PS. definition currently reads as "anomaly in the amount of iron present in the liver tissue"

**Comment by sbello** [comment]
the synonym suggested was already present, definition fixed
