### ISSUE TITLE
placental thrombosis

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2209]
Please add:

placental thrombosis as a child of both "thrombosis [MP:0005048]" and "abnormal placenta vasculature [MP:0003231]"
DEF: formation or presence of a thrombus within the blood vessel network of the placenta

Thanks!

Anna

**Comment by sbello** [comment]
MP:0020407 - abnormal placental thrombosis
MP:0020408 - altered susceptibility to induced thrombosis
MP:0020409 - abnormal cardiac thrombosis
