### ISSUE TITLE
cerebellum atrophy [MP:0014185] placement

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2210]
cerebellum atrophy [MP:0014185] currently exists as a child of "brain atrophy [MP:0012506]".

Consider making "cerebellum atrophy [MP:0014185]" a child of both "abnormal cerebellum morphology [MP:0000849]" and "hindbrain atrophy [MP:0014184]" 

Anna

**Comment by sbello** [comment]
made cerebellum atrophy a child of hindbrain atrophy and small cerebellum
