### ISSUE TITLE
split abnormal neuronal precursor proliferation 

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2215]
Consider splitting "abnormal neuronal precursor proliferation [MP:0004948]" into "increased" and "decreased" child terms:

increased neuronal precursor proliferation
DEF: increase in the ability of a neuroblast population to undergo rapid expansion by cell division
SYN: increased neuroblast proliferation
SYN: increased neuronal progenitor proliferation

decreased neuronal precursor proliferation
DEF: reduction in the ability of a neuroblast population to undergo rapid expansion by cell division
SYN: decreased neuroblast proliferation
SYN: decreased neuronal progenitor proliferation
SYN: reduced neuroblast proliferation
SYN: reduced neuronal precursor proliferation
SYN: reduced neuronal progenitor proliferation

Anna

**Comment by sbello** [comment]
MP:0020393
MP:0020394
