### ISSUE TITLE
abnormal fibroblast physiology

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2230]
Currently, we annotate abnormal mouse embryonic fibroblast (MEF) physiology to "abnormal cell physiology [MP:0005621]". 

Consider adding:

**abnormal fibroblast physiology**
DEF: any functional anomaly in the cellular physiological processes carried out by a fibroblast cell population

**abnormal fibroblast chemotaxis** (as a child of "abnormal fibroblast physiology")
DEF: any anomaly in the directed movement of a fibroblast cell population guided by a specific chemical concentration gradient; movement may be towards a higher concentration (positive chemotaxis) or towards a lower concentration (negative chemotaxis)
SYN: abnormal directed fibroblast migration

- **decreased fibroblast chemotaxis**
DEF: reduction in the directed movement response of a fibroblast cell population guided by a specific chemical concentration gradient; movement may be towards a higher concentration (positive chemotaxis) or towards a lower concentration (negative chemotaxis)
SYN: impaired directed fibroblast migration
SYN: impaired fibroblast chemotaxis
SYN: reduced directed fibroblast migration
SYN: reduced fibroblast chemotaxis
From J:159873,  J:185040,  J:134719,  J:104701,  J:106243 plus more

- **increased fibroblast chemotaxis**
DEF: 	increase in the directed movement response of a fibroblast cell population guided by a specific chemical concentration gradient; movement may be towards a higher concentration (positive chemotaxis) or towards a lower concentration (negative chemotaxis)
SYN: enhanced directed fibroblast migration
SYN: enhanced fibroblast chemotaxis
SYN: increased directed fibroblast migration
 J:146617

**NOTE: Existing terms "abnormal fibroblast proliferation [MP:0011702]", "abnormal fibroblast migration [MP:0011706]", "abnormal fibroblast apoptosis [MP:0013500]" and ALL children thereof should be placed under new term "abnormal fibroblast physiology".** 

Thanks

Anna

**Comment by sbello** [comment]
abnormal chemotaxis MP:0020415
increased - MP:0020417
decreased - MP:0020416
