### ISSUE TITLE
amnion terms

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2237]
Please consider adding:

abnormal amnion physiology
DEF: any functional anomaly of the thin innermost layer of the extraembryonic membranes that contains the amniotic fluid; the membrane forms a closed sac in which the embryo and later, the fetus, is suspended and protected

increased amnion apoptosis 
DEF: increase in the number of cells of the amnion undergoing programmed cell death
From J:237614

Thanks

Anna

**Comment by sbello** [comment]
abnormal - MP:0020412
increased - MP:0020413
