### ISSUE TITLE
small Meckel's cartilage

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2265]
New term:

small Meckel's cartilage (parent of short Meckel's cartilage MP:0013933)

DEF: reduced size of the cartilage bar in the mandibular arch that forms a temporary supporting structure in the embryonic mandible and gives rise to middle ear bones and sphenomandibular and anterior malleolar ligaments
SYN: small Meckel cartilage
SYN:  small mandibular cartilage
SYN: decreased Meckel's cartilage size
SYN: decreased Meckel cartilage size
SYN: decreased mandibular cartilage size
SYN: reduced Meckel's cartilage size
SYN: reduced Meckel cartilage size
SYN: reduced mandibular cartilage size

Anna

**Comment by anna-anagnostop** [comment]
Added small Meckel's cartilage MP:0030026 but was unable to make it a parent of short Meckel's cartilage MP:0013933
Anna

**Comment by cmungall** [comment]
This should be inferred provided axioms are in place, but I'm curious as 
to why you were unable to assert this?

**Comment by sbello** [comment]
I believe the issue is the 's in the term label. I've run into the same thing with other terms with 's. I believe this is also why Anna was unable to create axioms for the Meckel's cartilage terms as well. There are existing terms with 's in the axioms but my guess is these were put in using a different version of Protege.

**Comment by sbello** [comment]
According to Cindy she had to create these axioms by making modifications in a text editor. @cmungall Is there anyway to work with terms containing apostrophes in the label without resorting to a text editor?

**Comment by cmungall** [comment]
We ran into the same issue:

https://github.com/geneontology/go-ontology/issues/13881

We discussed the solution on a call but I don't remember what it was! You could pop over to @ukemi's office and ask him.

**Comment by sbello** [comment]
The solution is to change the View to 'render by entity IRI short name (Id)' then make the edit or add the axiom. You do need to have the IDs of the terms you want to use noted down but this works. (David popped up to show me how)
