### ISSUE TITLE
Wormian bones 

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2269]
New term:
Wormian bones 
DEF: presence of extra bones within a cranial suture; Wormian bones are irregular isolated bones which appear in addition to the usual centers of ossification of the cranium
SYN: extra bones within cranial sutures
SYN: intra sutural bones 
SYN: intrasutural bones 
SYN: islands of bone within cranial sutures
J:158635 J:56557

def from HP:0002645 https://en.wikipedia.org/wiki/Wormian_bones

Anna

**Comment by anna-anagnostop** [comment]
Added Wormian bones MP:0030030
Anna

**Comment by cmungall** [comment]
Is this always an abnormality? FMA has Wormian bone

**Comment by anna-anagnostop** [comment]
It appears that some consider them abnormal (pathological) only when greater than 10 in number or large. Wormian bones can also be idiopathic (anatomical variant). 
see https://radiopaedia.org/articles/wormian-bones
http://learningradiology.com/archives2010/COW%20432-Wormian/wormiancorrect.htm
