### ISSUE TITLE
New term: enlarged astrocytes

### ISSUE THREAD

**Issue by LaurensWilming** [obophenotype/mammalian-phenotype-ontology#2273]
>this is a request for a new term

>1. Preferred term label

**enlarged astrocytes**

>2. Synonyms

**increased astrocyte size**

>3. Textual definition 

**increased size of astrocytes**

>5. Suggested parent term

**MP:0002182**

**Comment by sbello** [comment]
increased astrocyte size - MP:0020434
decreased astrocyte size - MP:0020435
