### ISSUE TITLE
new term: decreased papilloma incidence

### ISSUE THREAD

**Issue by LaurensWilming** [obophenotype/mammalian-phenotype-ontology#2278]
#>If this is a request for a new term, please provide us with the following information.

>1. Preferred term label
**decreased papilloma incidence**

>3. Textual definition 
**fewer than the expected number of benign tumors consisting of villous or arborescent outgrowths of fibrovascular stroma covered by neoplastic epithelial cells occurring in a specific population in a given time period**

>4. Any additional notes to clarify the meaning or use of the term. Please provide a PubMed ID or URL(s) for the source of this information.
**J:241062 describes reduced incidence of chemically induced skin papilloma in MGI:5906161 heterozygous KOs.**

>5. Suggested parent term
**MP:0010283**

**Comment by sbello** [comment]
MP:0020438
