### ISSUE TITLE
new term: abnormal front foot hair pigmentation

### ISSUE THREAD

**Issue by LaurensWilming** [obophenotype/mammalian-phenotype-ontology#2279]
>1. Preferred term label 
**abnormal front foot hair pigmentation**

>3. Textual definition 
**an anomaly in the expected color gradient of hair covering the metatarsals and phalanges** 

>4. Any additional notes to clarify the meaning or use of the term. Please provide a PubMed ID or URL(s) for the source of this information.
**J:241031 describes un-pigmented digits and front and hind paws. Also, the definition of existing sister term MP:0009934 needs to be improved.**

>5. Suggested parent term 
**MP:0002075**

**Comment by sbello** [comment]
modified definition to:
an anomaly in the expected color gradient of hair covering the metacarpals and phalanges 
difference between term definitions hinges on the metatarsal/metacarpal bone specification to hind and front feet respectively

**Comment by sbello** [comment]
MP:0020440
