### ISSUE TITLE
helix

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2311]
Add:
abnormal helix morphology ( a child of abnormal outer ear morphology MP:0002177)
DEF: any structural anomaly of the outer rim of the ear that extends from the insertion of the ear on the scalp (root) to the termination of the cartilage at the earlobe
DEF SOURCE: HP:0011039 

J:237903 
Anna

**Comment by sbello** [comment]
I would suggest making the primary term name more specific, so that it is clear from the label that this refers to the helix of the outer ear. Maybe abnormal outer ear helix morphology.

**Comment by anna-anagnostop** [comment]
Added:
abnormal outer ear helix morphology MP:0030092
