### ISSUE TITLE
microdontia

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2315]
Add:
microdontia (child of abnormal tooth morphology MP:0002100)
DEF: abnormal reduction in the size of one or more teeth
SYN: decreased tooth size
SYN: reduced tooth size
SYN: decreased tooth width
SYN: reduced tooth width
SYN: small teeth
SYN: small tooth
SYN: microdontism
SYN: microdont
Anna

**Comment by anna-anagnostop** [comment]
microdontia MP:0030088

**Comment by sbello** [comment]
Anna, I changed the tooth width synonyms to narrow synonyms since you could have short teet that would also be considered to be 'small teeth' even though they have normal width. Same thing for macrodontia and increased tooth width synonym.
