### ISSUE TITLE
absent teeth synonyms

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2318]
Add new synonyms to absent teeth MP:0000124 
NEW SYN: tooth agenesis
NEW SYN: dental agenesis
NEW SYN: toothless
NEW SYN: anodontia
NEW SYN: missing teeth
NEW SYN: tooth aplasia
NEW SYN: edentulous
Anna

NOTE: In humans, hypodontia refers to the absence of one to six teeth, excluding third molars, whereas oligodontia refers to the absence of more than six teeth, excluding third molars. Third molars are excluded, as these are missing in up to 20% of patients, making this a very common finding. Anodontia is the complete absence of teeth in one or both dentitions. Together, these are referred to as tooth agenesis.
See:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3844689/
Anodontia HP:0000674
Hypodontia HP:0000668 
Oligodontia HP:0000677

**Comment by sbello** [comment]
We want absent to mean missing all of X. Need to obsolete existing absent teeth term which currently specifies 'some or all'

**Comment by anna-anagnostop** [comment]
Obsoleted MP:0000124 as suggested. 
Also added new term abnormal tooth number MP:0030611 as a parent term of supernumerary teeth MP:0004033 and decreased tooth number MP:0030608
