### ISSUE TITLE
Typo in MP_0010471 supravalvar aortic stenosis?

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/mammalian-phenotype-ontology#2358]
Should this be 'supravalvular' instead of supravalvar?

**Comment by anna-anagnostop** [comment]
This is not a typo as supravalvar and supravalvular appear to be synonymous; see http://medical-dictionary.thefreedictionary.com/supravalvular

See also:

http://emedicine.medscape.com/article/892252-overview
https://www.uptodate.com/contents/supravalvar-aortic-stenosis
http://www.mottchildren.org/conditions-treatments/ped-heart/conditions/aortic-stenosis

I will add "supravalvular aortic stenosis" as a synonym to MP:0010471

Anna

**Comment by anna-anagnostop** [comment]
I have added "supravalvular aortic stenosis" as a synonym to MP:0010471

**Comment by nicolevasilevsky** [comment]
Thanks, @anna-anagnostop!
