### ISSUE TITLE
new term: increased megakaryocyte progenitor cell number

### ISSUE THREAD

**Issue by LaurensWilming** [obophenotype/mammalian-phenotype-ontology#2380]
>1. Preferred term label (e.g., asplenia)
**increased megakaryocyte progenitor cell number**

>3. Textual definition (the definition should be understandable even for non-specialists. 
**increase in the number of a progenitor cell committed to the megakaryocyte lineage**

>4. Any additional notes to clarify the meaning or use of the term. Please provide a PubMed ID or URL(s) for the source of this information.
**J:241724**

>5. Suggested parent term.
**MP:0002413 abnormal megakaryocyte progenitor cell morphology**
(note that the comparable MP:0013704 (increased megakaryocyte-erythroid progenitor cell number) has an intermediate parent MP:0013703 (abnormal megakaryocyte-erythroid progenitor cell number), whereas the comparable MP:0013891 (increased common myeloid progenitor cell number) does not).

Laurens

**Comment by sbello** [comment]
added
abnormal megakaryocyte progenitor cell number MP:0020462
increased megakaryocyte progenitor cell number MP:0020463
decreased megakaryocyte progenitor cell number MP:0020464
abnormal megakaryocyte progenitor cell physiology MP:0020465
increased megakaryocyte progenitor cell proliferation MP:0020466
