### ISSUE TITLE
new term: increased/decreased perigenital adipose tissue amount

### ISSUE THREAD

**Issue by LaurensWilming** [obophenotype/mammalian-phenotype-ontology#2503]
>1. Preferred term label 
**increased perigenital adipose tissue amount**
**decreased perigenital adipose tissue amount**

>3. Textual definition
**increase in amount of adipose tissue around the genitals**
**decrease in amount of adipose tissue around the genitals**

>4. Any additional notes to clarify the meaning or use of the term. Please provide a PubMed ID or URL(s) for the source of this information.
**PMID:27199455 mentions that this is normal in their transgenic mice. These depots/deposits are  different from subcutaneous WAT depots and I guess from abdominal ones too** 

>5. Suggested parent term (Please look in the hierarchy of the MP using the [MP Browser]
**MP:0001781 abnormal white adipose tissue amount**

**Comment by sbello** [comment]
Is this different from MP:0005335 (abnormal gonadal fat pad morphology)? Or is this a new synonym for that term? The reference above does not appear to define what they mean by perigenital.

**Comment by anna-anagnostop** [comment]
Genitalia are defined as the male or female reproductive organs and include both internal and external structures (https://www.medicinenet.com/script/main/art.asp?articlekey=11372). However, “genitals” is also a commonly used lay term for the **visible, external** male and female genitalia (https://medical-dictionary.thefreedictionary.com/genitals)

The term abnormal gonadal fat pad morphology MP:0005335 (syn: abnormal perigonadal fat pad morphology) refers specifically to any structural anomaly of the encapsulated adipose tissue associated with the gonads, i.e. ovaries or testes (which are considered **internal** female and male genital organs, respectively).

Thus, I would not assign perigenital as a new synonym for perigonadal. Rather, perigenital is more like a higher-level (parent) term of perigonadal. For example, increased fat accumulation in the labia majora (external female structure) would be annotated to "increased perigenital adipose tissue amount".

**Comment by sbello** [comment]
Seems reasonable Anna. The authors in the paper give no description of what they mean by perigenital. Laurens decided to use the existing term. I'll close this.
