### ISSUE TITLE
abnormal metopic suture morphology MP:0003842 - synonym/term label change?

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2505]
abnormal metopic suture morphology MP:0003842
ADD NEW SYNONYM: abnormal median frontal suture morphology 
(SOURCE: https://radiopaedia.org/articles/metopic-suture)
**CORRECT EXISTING SYNONYM**: abnormal intrafrontal suture morphology should be corrected to abnormal **interfrontal** suture morphology (see GO:0060364)

NOTE: In mice and rats, the posterior frontal (PF) suture, situated between the frontal bones, is analogous to the human metopic suture; the anterior landmark for the PF suture is the jugum limitans; the posterior landmark for the PF suture is the bregma
SOURCE: PMID:15882577

QUESTION: 
A persistent frontal suture is referred to as a "metopic suture" (https://en.wikipedia.or/wiki/Frontal_suture, HP:0005556).

Should the primary term label for "abnormal metopic suture morphology" MP:0003842 be changed to "**abnormal frontal suture morphology**" using metopic suture as a _related_ synonym for frontal suture?
GO, UBERON and MA use frontal suture; HP, MP, and VT use metopic suture.

**Comment by sbello** [comment]
I think the line in the HP definition is an error. See http://austinpublishinggroup.com/anatomy/fulltext/Anatomy-v3-id1049.php a persistent unfused suture is referred to as 'metopism'. The literature consistently refers to the normal suture as a metopic suture.

**Comment by anna-anagnostop** [comment]
Sue, I think you are right. See also, http://austinpublishinggroup.com/anatomy/fulltext/Anatomy-v3-id1049.php, in humans, "the metopic suture generally fuses between 1 and 8 years of life. If it remains after that time it is known as metopism"

**Comment by anna-anagnostop** [comment]
Left the primary term label as is: abnormal metopic suture morphology MP:0003842.

Added new synonym (abnormal median frontal suture morphology) and changed 'intrafrontal" to 'interfrontal' in existing synonym.

Amended definition to reflect that, in mice and rats, the posterior frontal (PF) suture is analogous to the human metopic suture.
