### ISSUE TITLE
abnormal interfrontal bone morphology - placement question

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2506]
abnormal interfrontal bone morphology (MP:0008818) is currently defined as:
DEF: any structural anomaly or presence of a bone between the frontal bones in the skull; an extra bony plate within the anterior fontanelle that is not usually present

QUESTION:
In mice, the interfrontal bone (IF) is a minor skeletal trait in mice.  **When present the IF bone resides between the frontal bones along the interfrontal (metopic) suture** (http://www-personal.umich.edu/~sbayne/DMG/DMG-Publications/IADR-AADR-Meeting-Program-Books/2012-AADR-Tampa/2012-AADR-Tampa-CD/AADR12/Paper157606.html).

Does this make the interfrontal bone a Wormian bone MP:0030030 (see issue #2269)?

Thanks!

Anna

**Comment by anna-anagnostop** [comment]
In PMID:28069589 (Analysis of the Fgfr2C342Y mouse model shows condensation defects due to misregulation of Sox9 expression in prechondrocytic mesenchyme. Biol Open. 2017 Feb 15;6(2):223-231), Peskett E, et al. refer to the interfrontal bone as “a small Wormian bone located between the anterior frontal bones (Fig. 2G,H). This interfrontal bone is common in some wild-type strains but rare in CD1 mice and is absent from wild-type controls”.

However, in PMID:3396633 (Appearance of interfrontal bone in chimeric mouse. Jikken Dobutsu. 1988 Apr;37(2):165-70), Fukuta K et al. state that “this bone in the mouse is not considered a wormian bone, but an independent entity, because of the regularity of its appearance and location”.

**Comment by sbello** [comment]
No,
