### ISSUE TITLE
Unsatisfiable interleukin levels

### ISSUE THREAD

**Issue by balhoff** [obophenotype/mammalian-phenotype-ontology#2535]
Hi @sbello here are six more unsatisfiable classes that I wasn't sure about:

[abnormal circulating interleukin-12 level](http://purl.obolibrary.org/obo/MP_0008616) and [abnormal circulating interleukin-23 level](http://purl.obolibrary.org/obo/MP_0008619) (and also the increased and decreased versions of each)

These both reference "receptor binding" processes instead of proteins. For example 'abnormal circulating interleukin-12 level' is defined as:

```
'has part' some 
    (amount
     and ('inheres in' some 
        ('interleukin-12 receptor binding'
         and ('part of' some blood)))
     and ('has modifier' some abnormal))
```

Most of the similar classes are defined like 'abnormal circulating interleukin-10 level':

```
'has part' some 
    (amount
     and ('inheres in' some 
        (interleukin-10
         and ('part of' some blood)))
     and ('has modifier' some abnormal))
```

I'm guessing that appropriate terms need to be found for 'interleukin-12' and 'interleukin-23' proteins.

**Comment by sbello** [comment]
Looks like we need to change these to use PRO terms, see PR:000001471

**Comment by matentzn** [comment]
Since our [pipeline](https://github.com/obophenotype/upheno/issues/254) relies on MP being consistent and coherent at the moment, do you have an estimate for how long it takes to fix this?

**Comment by cmungall** [comment]
@nicolevasilevsky can you make a PR for this?

**Comment by nicolevasilevsky** [comment]
For MP_0008616 abnormal circulating interleukin-12 level (and it's children), I think we can use GO:0043514	
interleukin-12 complex (the protein ontology uses the GO ID in their ontology.) 

For MP_0008619 abnormal circulating interleukin-23 level (and it's children), I think we can use GO:0070743 interleukin-23 complex

Both terms need to be MIREOTed. @sbello, what do you do when you need to MIREOT a term? Can you add it or should I ask someone else? I usually ask Seb for help with MIREOTing in HPO.

**Comment by sbello** [comment]
I can mireot these in but then I think Seb will need to run the make file to update this. I'm working on this today. 
Thanks for suggesting terms @nicolevasilevsky
