### ISSUE TITLE
Missing label for MP:0030017

### ISSUE THREAD

**Issue by LLTommy** [obophenotype/mammalian-phenotype-ontology#2553]
The term http://purl.obolibrary.org/obo/MP_0030017 (Description: reduced ability of adipocytes to take in glucose, Synonyms: reduced fat cell glucose uptake, reduced adipocyte glucose uptake, decreased fat cell glucose uptake, impaired adipocyte glucose uptake, impaired fat cell glucose uptake) does not seem to have a label in the current owl version (http://purl.obolibrary.org/obo/mp/releases/2017-11-17/mp.owl).

@simonjupp: This leads to akward display e.g. in the  [(Ontology Lookup Service)](https://www.ebi.ac.uk/ols/ontologies/mp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMP_0030017)

**Comment by anna-anagnostop** [comment]
Fixed. Missing label has been added.
