### ISSUE TITLE
split abnormal spatial learning, add inhibitory learning 

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#256]
Hi,
Please consider splitting the term abnormal spatial learning by adding enhamced and impaired child terms.
Also please consider adding the term:
abnormal inhibitory learning
syn - abnormal latent inhibition of learned behavior
def - anomaly in the process by which a subject learns to suppress a prior learned response
This phenotype appears in J:147275 in the context of mice learning to search a different quadrant of a Morris water maze after the platform has been moved. For now I've put the annotation under abnormal learning/ memory. This phenotype also appears in J:51147 which is currently annotated to abnormal spatial learning.
Thanks,
Sue

Reported by: sbello

Original Ticket: "obo/mammalian-phenotype-requests/256":https://sourceforge.net/p/obo/mammalian-phenotype-requests/256

**Comment by sbello** [comment]
added MP:0020340 abnormal inhibitory learning
