### ISSUE TITLE
Broken definitions?

### ISSUE THREAD

**Issue by matentzn** [obophenotype/mammalian-phenotype-ontology#2654]
I raised a ticket elsewhere (https://github.com/obophenotype/upheno/issues/254) but it might be better to discuss this here. 

In our pipeline, we found that the following definitions are unsatisfiable:

- MP:0008616 'abnormal circulating interleukin-12 level'
- MP:0008649 'abnormal circulating interleukin-23a level'
- MP:0008617 'increased circulating interleukin-12 level'
- MP:0008618 'decreased circulating interleukin-12 level'
- MP:0008619 'abnormal circulating interleukin-23 level'
- MP:0008620 'increased circulating interleukin-23 level'
- MP:0008621 'decreased circulating interleukin-23 level'
- MP:0008643 'abnormal circulating interleukin-12a level'
- MP:0008644 'increased circulating interleukin-12a level'
- MP:0008645 'decreased circulating interleukin-12a level'

The reason for this is detailed in the above referenced ticket, but it boils down to this:
The definition of these classes mention the intersection of an "interleukin receptor binding"(which is an occurrant in BFO terms) and "part of" some Blood (blood being a continuant). According to the BFO worldview, occurrents are disjoint with anything that "part of continuant". You might quick fix this by, instead of using part of here, instead use occurs in, at least I think so.

**Comment by balhoff** [comment]
This is a dup of #2535. I don't think `occurs in` is the solution, rather the wrong interleukin terms have been used.

**Comment by matentzn** [comment]
Okay, thanks! Sorry for the duplication!
