### ISSUE TITLE
Revise definition of MP_0001491 ("unresponsive to tactile stimuli")

### ISSUE THREAD

**Issue by matentzn** [obophenotype/mammalian-phenotype-ontology#2670]
According to RO, an occurrent cannot be part of a continuant. The definition of MP_0001491 states:

'has part' some 
    (absent
     and ('inheres in' some 
        ('touch related behavior'
         and ('part of' some 'multicellular organism')))
     and ('has modifier' some abnormal))

which involves the expression:

('touch related behavior'
         and ('part of' some 'multicellular organism'))

_**touch related behaviour**_ is a **_behaviour process_**, which, in my opinion perhaps rightfully so, other ontologies such as [Mental Functioning Ontology](https://github.com/jannahastings/mental-functioning-ontology) interpret as a BFO process (i.e. an occurrent). Since the _**multicellular organism**_ is a continuant, this would cause an inconsistency. Do you mind to revise the definition, or do you challenge the assertion that a behaviour process is a BFO process? If the latter, I will go and try to convince the people around Mental Functioning Ontology to change their assertion.

**Comment by sbello** [comment]
This is a hold over from when we used to include the larger containing structure for absent terms. As none of the other response to tactile stimuli have this in the definition and we are no longer including the larger structure in definitions for absent terms  I've removed this from the definition.
Thanks for the catch.
