### ISSUE TITLE
additional parent for MP:0003413 hair follicle degeneration

### ISSUE THREAD

**Issue by LaurensWilming** [obophenotype/mammalian-phenotype-ontology#2671]
I wonder if **MP:0003413 hair follicle degeneration** shouldn't have **MP:0000414 alopecia** as an additional parent (or have some other relationship).  Follicle degeneration will inevitably result in alopecia. 

Laurens

**Comment by sbello** [comment]
That relationship would make hair follicle degeneration a type of alopecia which isn't correct.
