### ISSUE TITLE
New Directional Brain Terms for Paper

### ISSUE THREAD

**Issue by Vancollie** [obophenotype/mammalian-phenotype-ontology#2682]
Hello,

Could we please get the following directional MP terms created to hang off of existing parental terms that lack direction or have only one direction at present?

1) increased cerebellar foliation
Synonyms: increased cerebellum foliation | increased folia
Textual definition: the opposite of that for existing directional term MP:0009719 (ie: the cerebellar lobules are increased in size or number)
Parental Term: abnormal cerebellar foliation; MP:0000857

2) decreased pons size
Synonyms: decreased pons Varolii morphology
Textual definition: decreased size or number of the nerve fibers in the brain connecting the medulla oblongata and the mesencephalon (based on the existing definition of the parent term)
Parental Term: abnormal pons morphology; MP:0000848

3) increased pons size
Synonyms: increased pons Varolii morphology
Textual definition: increased size or number of the nerve fibers in the brain connecting the medulla oblongata and the mesencephalon (based on the existing definition of the parent term)
Parental Term: abnormal pons morphology; MP:0000848

4) decreased subiculum size
Synonyms: decreased size of the subiculum
Textual definition: a decrease of the transitional zone between the parahippocampal gyrus and the Ammon gyrus (based on the existing definition of the parent term)
Parental Term: abnormal subiculum morphology; MP:0008287

5) increased subiculum size
Synonyms: increased size of the subiculum
Textual definition: an increase of the transitional zone between the parahippocampal gyrus and the Ammon gyrus (based on the existing definition of the parent term)
Parental Term: abnormal subiculum morphology; MP:0008287

6) decreased cerebellum fastigial nucleus size
Synonyms: decreased cerebellum roof nucleus morphology | decreased cerebellum tectal nucleus morphology | decreased medial cerebellar nucleus morphology
Textual definition: decreased size of the most medial of the cerebellar nuclei (based on the existing definition of the parent term)
Parental Term: abnormal cerebellum fastigial nucleus morphology; MP:0009983

7) increased cerebellum fastigial nucleus size
Synonyms: increased cerebellum roof nucleus morphology | increased cerebellum tectal nucleus morphology | increased medial cerebellar nucleus morphology
Textual definition: increased size of the most medial of the cerebellar nuclei (based on the existing definition of the parent term)
Parental Term: abnormal cerebellum fastigial nucleus morphology; MP:0009983

8) decreased substantia nigra size
Synonyms: decrease locus niger size | decreased nucleus niger size 
Textual definition: decreased size of the layer of grey substance that separates the posterior parts of the cerebral peduncles (tegmentum mesencephali) from the anterior parts (based on the existing definition of the parent term)
Parental Term: abnormal substantia nigra morphology; MP:0000836

9) increased substantia nigra size
Synonyms: increase locus niger size | increased nucleus niger size 
Textual definition: increased size of the layer of grey substance that separates the posterior parts of the cerebral peduncles (tegmentum mesencephali) from the anterior parts (based on the existing definition of the parent term)
Parental Term: abnormal substantia nigra morphology; MP:0000836

10) decreased hippocampal fornix size
Synonyms: decreased fornix hippocampus size
Textual definition: decreased size of the compact, white, heavily myelinated fiber bundle arising from the Ammon horn of the hippocampus in each cerebral hemisphere and projecting to the hypothalamus and the mammillary body (based on the existing definition of the parent term)
Parental Term: abnormal hippocampal fornix morphology; MP:0003006

11) increased hippocampal fornix size
Synonyms: increased fornix hippocampus size
Textual definition: increased size of the compact, white, heavily myelinated fiber bundle arising from the Ammon horn of the hippocampus in each cerebral hemisphere and projecting to the hypothalamus and the mammillary body (based on the existing definition of the parent term)
Parental Term: abnormal hippocampal fornix morphology; MP:0003006

12) decreased optic chiasm size
Synonyms: decreased optic chiasma
Textual definition: a decrease in the flattened quadrangular body that is the point of crossing of the fibers of the optic nerves (based on the existing definition of the parent term)
Parental Term: abnormal optic chiasm morphology; MP:0009770

13) increased optic chiasm size
Synonyms: increased optic chiasma
Textual definition: an increase in the flattened quadrangular body that is the point of crossing of the fibers of the optic nerves (based on the existing definition of the parent term)
Parental Term: abnormal optic chiasm morphology; MP:0009770

Cheers,
Valerie

**Comment by sbello** [comment]
increased cerebellar foliation MP:0020531
decreased pons size MP:0020533
increased pons size MP:0020534
abnormal pons size MP:0020532
abnormal subiculum size MP:0020535
increased subiculum size MP:0020536
decreased subiculum size MP:0020537

**Comment by sbello** [comment]
decreased cerebellum fastigial nucleus size MP:0020540
increased cerebellum fastigial nucleus size MP:0020539
abnormal cerebellum fastigial nucleus size MP:0020538
decreased substantia nigra size MP:0020543
increased substantia nigra size MP:0020542
abnormal substantia nigra size MP:0020541

**Comment by sbello** [comment]
decreased hippocampal fornix size MP:0020545
increased hippocampal fornix size MP:0020546
abnormal hippocampal fornix size MP:0020544
decreased optic chiasm size MP:0020548
increased optic chiasm size MP:0020549
abnormal optic chiasm size MP:0020547
