### ISSUE TITLE
piliary cannal and hair folicle terms

### ISSUE THREAD

**Issue by sbello** [obophenotype/mammalian-phenotype-ontology#2684]
From Melissa:

Abnormal pilary canal
“the pilary canal in the HF infundibulum region was wider and morphologically irregular in Acer1-/- mice"
Child of 377, abnormal hair follicle morphology

Decreased hair follicle stem cells

**Comment by sbello** [comment]
PMID:29056331

**Comment by anna-anagnostop** [comment]
Add: 
abnormal piliary canal morphology (a child of abnormal hair follicle morphology MP:0000377)
DEF: any structural anomaly of the tubular connection that is found between the epidermal surface and the most distal part of the hair follicle inner root sheath and contains the hair shaft; the infundibulum is the opening of the hair canal to the skin surface
SYN: abnormal hair canal morphology
SYN: abnormal pilary canal morphology (see PMID:20882038 and PMID:29056331)
DEF SOURCE: PMID:19211055, UBERON:0035610

NOTE: Per UBERON, “hair canal” (UBERON:0035610) is_part of “zone of skin” (UBERON:0000014)

dilated piliary canal 
DEF: stretched or widened aperture of the luminal space of the tubular connection that is found between the epidermal surface and the most distal part of the hair follicle inner root sheath and contains the hair shaft; the infundibulum is the opening of the hair canal to the skin surface
SYN: dilatation of the piliary canal
SYN: dilated hair canal
SYN: dilated pilary canal
DEF SOURCE: PMID:11171393

**Comment by anna-anagnostop** [comment]
Added:
abnormal piliary canal morphology MP:0030570
dilated piliary canal MP:0030571
