### ISSUE TITLE
New Directional Brain Terms for Paper Part 2

### ISSUE THREAD

**Issue by Vancollie** [obophenotype/mammalian-phenotype-ontology#2685]
Hello,

Could we please get the following parental & directional MP terms created? They are similar to ones that already exist, but are for different brain areas not yet on the tree.

1) abnormal stria medullaris morphology
Synonyms: abnormal stria medullaris of thalamus
Textual definition: any structural anomaly of a bundle of afferent fibers that form a ridge over the thalamus and project to the habenular nucleus
Parental Term: abnormal epithalamus morphology, MP:0000840

2) decreased stria medullaris size
Synonyms: decreased stria medullaris of thalamus size
Textual definition: a decraese in size of the bundle of afferent fibers that form a ridge over the thalamus and project to the habenular nucleus
Parental Term: abnormal stria medullaris morphology (#1)

3) increased stria medullaris size
Synonyms: increased stria medullaris of thalamus size
Textual definition: an incraese in size of the bundle of afferent fibers that form a ridge over the thalamus and project to the habenular nucleus
Parental Term: abnormal stria medullaris morphology (#1)

4) abnormal ventromedial hypothalamic nucleus morphology
Synonyms: ventromedial hypothalamic nucleus dysplasia
Textual definition: any structural anomaly of a circumscript ovoid group of small neurons in the medial zone of the tuberal region of the hypothalamus delineated by a narrow, cell-sparse zone; this region regulates feeding, fear, thermoregulation and sexual activity
Parental Term: abnormal hypothalamus morphology, MP:0000837 

5) decreased ventromedial hypothalamic nucleus size
Synonyms: decreased ventromedial hypothalamic nucleus size
Textual definition: a decrease of the circumscript ovoid group of small neurons in the medial zone of the tuberal region of the hypothalamus delineated by a narrow, cell-sparse zone; this region regulates feeding, fear, thermoregulation and sexual activity
Parental Term: abnormal ventromedial hypothalamic nucleus morphology (#4)

6) increased ventromedial hypothalamic nucleus size
Synonyms: increased ventromedial hypothalamic nucleus size
Textual definition: an increase of the circumscript ovoid group of small neurons in the medial zone of the tuberal region of the hypothalamus delineated by a narrow, cell-sparse zone; this region regulates feeding, fear, thermoregulation and sexual activity
Parental Term: abnormal ventromedial hypothalamic nucleus morphology (#4)

7) abnormal pontine nuclei morphology
Synonyms: abnormal griseum pontis
Textual definition: any structural anomaly of nuclei located in the ventral pons involved in motor activity
Parental Term: abnormal pons morphology, MP:0000848

8) decreased pontine nuclei size
Synonyms: decreased griseum pontis size
Textual definition: a decrease of nuclei located in the ventral pons involved in motor activity
Parental Term: abnormal pontine nuclei morphology (#7)

9) increased pontine nuclei size 
Synonyms: increased griseum pontis size
Textual definition: an increase of nuclei located in the ventral pons involved in motor activity
Parental Term: abnormal pontine nuclei morphology (#7)

10) abnormal fibre of pons
Synonyms: abnormal pontocerebellar fibers
Textual definition: any structual anomaly of  fibers of the pontocerebellar tracts that project from the pons to the contralateral cerebellum
Parental Term: abnormal pons morphology, MP:0000848

11) decreased fibre of pons size
Synonyms: decreased pontocerebellar fibers size
Textual definition: a decrease of  fibers of the pontocerebellar tracts that project from the pons to the contralateral cerebellum
Parental Term: abnormal fibre of pons (#10)

12) increased fibre of pons size
Synonyms: increased pontocerebellar fibers size
Textual definition: an increase of  fibers of the pontocerebellar tracts that project from the pons to the contralateral cerebellum
Parental Term: abnormal fibre of pons (#10)

13) abnormal secondary motor cortex morphology 
Synonyms: motor cortex
Textual definition: any structural anomaly of the part of the cerebral cortex that receives projections from the motor thalamus and which projects to motor neurons in the brainstem and spinal cord; the secondary motor cortex, or M2, influences movements of the face, neck and trunk, and upper and lower extremities
Parental Term: abnormal cerebral cortex morphology, MP:0000788 

14) decreased secondary motor cortex size 
Synonyms: decreased motor cortex size
Textual definition: a decrease of the part of the cerebral cortex that receives projections from the motor thalamus and which projects to motor neurons in the brainstem and spinal cord; the secondary motor cortex, or M2, influences movements of the face, neck and trunk, and upper and lower extremities
Parental Term: abnormal secondary motor cortex morphology (#13)

15) increased secondary motor cortex size 
Synonyms: increased motor cortex size
Textual definition: an increase of the part of the cerebral cortex that receives projections from the motor thalamus and which projects to motor neurons in the brainstem and spinal cord; the secondary motor cortex, or M2, influences movements of the face, neck and trunk, and upper and lower extremities
Parental Term: abnormal secondary motor cortex morphology (#13)

Cheers,
Valerie

**Comment by Vancollie** [comment]
Sorry, I did not realize that putting the number in with a hashtag would create a link, I just wanted refer to which of the other requested terms would be the parental MP term!

**Comment by sbello** [comment]
Sorry for the delay, I've been having github issues but things seem to be working now.

**Comment by sbello** [comment]
@Vancollie Would you please provide references for your definitions. I would like to add these to the MP term entries.
Thanks, 
Sue

**Comment by sbello** [comment]
Terms added
abnormal stria medullaris morphology MP:0020552
abnormal stria medullaris size MP:0020553
increased stria medullaris size MP:0020555
decreased stria medullaris size MP:0020554

abnormal ventromedial hypothalamic nucleus morphology MP:0020556
abnormal ventromedial hypothalamic nucleus size MP:0020557
increased ventromedial hypothalamic nucleus size MP:0020559
decreased ventromedial hypothalamic nucleus size MP:0020558

abnormal pontine nuclei morphology MP:0020560
abnormal pontine nuclei size MP:0020561
increased  pontine nuclei size MP:0020563
decreased pontine nuclei size MP:0020562

abnormal pontocerebellar fibers morphology MP:0020564 (used pontocerebellar fibers as the primary term name as this matches BrainInfo anf fibers of pons best match was often the wrong structure)
abnormal pontocerebellar fibers size MP:0020565
increased pontocerebellar fibers size MP:0020567
decreased pontocerebellar fibers size MP:0020566

abnormal premotor cortex morphology MP:0020568 (used premotor cortex as the primary term name as this matches BrainInfo and Uberon)
abnormal premotor cortex size MP:0020569
decreased premotor cortex size MP:0020570
increased premotor cortex size MP:0020571

**Comment by sbello** [comment]
add term: 
absent pontine nuclei

**Comment by Vancollie** [comment]
Hello Sue,

First off thanks for adding these and the previous ticket's terms. I have been in contact with our collaborator for the additional information and received this:

_for stria medullaris
- http://atlas.brain-map.org/atlas?atlas=1#atlas=1&plate=100960252&structure=802&x=5280&y=3744.1904994419647&zoom=-3&resolution=11.97&z=5 
- https://en.wikipedia.org/wiki/Stria_medullaris_of_thalamus

for ventromedial hypothalamus
- http://atlas.brain-map.org/atlas?atlas=1#atlas=1&plate=100960252&structure=693&x=5280&y=3744.1904994419647&zoom=-3&resolution=11.97&z=5
- https://en.wikipedia.org/wiki/Ventromedial_nucleus_of_the_hypothalamus

for pontine nuclei
- http://atlas.brain-map.org/atlas?atlas=2#atlas=2&plate=100883888&structure=931&x=7800&y=4024&zoom=-3&resolution=16.75&z=5
- https://en.wikipedia.org/wiki/Pontine_nuclei

for pontocerebellar fibers
- https://en.wikipedia.org/wiki/Pontocerebellar_fibers

for secondary motor cortex 
- http://atlas.brain-map.org/atlas?atlas=2#atlas=2&plate=100883888&structure=500&x=7800&y=4024&zoom=-4&resolution=16.75&z=5
- https://en.wikipedia.org/wiki/Motor_cortex

NB: In the Allen Brain Atlas links, the region of interest is highlighted in purple_ 

Is this sufficient?

Cheers,
Valerie

**Comment by sbello** [comment]
That's great. Thanks! I'll add these to the entries soon.
