### ISSUE TITLE
new synonym request: endotheliosis

### ISSUE THREAD

**Issue by LaurensWilming** [obophenotype/mammalian-phenotype-ontology#2689]
For **MP:0011433 glomerular capillary congestion** I'd like to suggest adding _endotheliosis_ or _glomerular capillary endotheliosis_ as a synonym. According to https://medical-dictionary.thefreedictionary.com/endotheliosis, 

> glomerular capillary endotheliosis a renal lesion typical of eclampsia; it is characterized by deposition of fibrous material in and beneath the cells of the grossly swollen glomerular capillary endothelium, resulting in near total or total occlusion of the capillaries.

 Which sounds like MP:0011433. If you think it is different, endotheliosis should be added as a new term.

Thanks,
Laurens

**Comment by anna-anagnostop** [comment]
I would rather add "glomerular capillary endotheliosis" as a new term ( a child of abnormal glomerular capillary endothelium morphology MP:0011453)
SUGGESTED DEF: a renal lesion characterized by glomerular endothelial swelling with glomerular hypertrophy, obliteration of endothelial fenestrae, and narrowing or occlusion of the capillary lumens 
see PMID:17634433; https://obgyn.onlinelibrary.wiley.com/doi/pdf/10.1111/j.1471-0528.2003.02162.x

**Comment by sbello** [comment]
I would also prefer the separate term. Seems like glomerular capillary endotheliosis may cause capillary congestion but not necessarily and it isn't the only way you could end up with congestion.

**Comment by LaurensWilming** [comment]
Fine by me!

Laurens

**Comment by anna-anagnostop** [comment]
I will create a new term. I just assigned myself.

**Comment by anna-anagnostop** [comment]
Added:
glomerular capillary endotheliosis MP:0030569
SYN: glomerular endotheliosis
