### ISSUE TITLE
New term request: increased ceramide level

### ISSUE THREAD

**Issue by LaurensWilming** [obophenotype/mammalian-phenotype-ontology#2690]
>1. Preferred term label 

**increased ceramide level**

>4. Any additional notes to clarify the meaning or use of the term. 

**This is just one example of a term where there exists an abnormal term but not _increased_ and decreased child terms. Wouldn't it make sense to create those child terms by default? Currently it's a mishmash with some terms having those children (_abnormal sphingosine level_, for example) and others not. There are even terms that only have one of the _increased_/_decreased_ children!**

>5. Suggested parent term 

**MP:0012232 abnormal ceramide level**

**Comment by sbello** [comment]
In the past, we created only the term that was needed/requested. This is why there may be only an increased/decreased child or no children. The current policy is to create the reciprocal term but we have not gone back to clean up all the existing terms.
