### ISSUE TITLE
New synonyms request: various

### ISSUE THREAD

**Issue by LaurensWilming** [obophenotype/mammalian-phenotype-ontology#2691]
>2. Synonyms 

**MP:0010163: haemolysis.** Basically any term that has the word **_hem_** in it should have a synonym that replaces hem with **_haem_**.

**MP:0001577: anemia.** Basically any term that has the word **_anemia_** in it should have a synonym that replaces anemia with **_anaemia_**.

Of course that goes for any other term where American English drops out the _a_ from the British English _ae_.

**MP:0002531: anaphylactic shock.**

**Comment by anna-anagnostop** [comment]
This includes a LOT of hematopoiesis/hemoglobin/hemangioblast/hemangioma terms plus any term that has the word hemorrhage (British spelling haemorrhage).

**Comment by anna-anagnostop** [comment]
Similarly, all terms containing the word **esophagus/esophageal** should have a synonym that replaces "es" with "oes" e.g., Oesophagus, oesophageal inflammation

**Comment by LaurensWilming** [comment]
Indeed. Tumor <> Tumour, etc. But thankfully you can largely automate that. You can write an SQL to extract all the terms that require the British synonyms and write a simple PERL script that generates the synonyms and generates an SQL that uploads them.

**Comment by anna-anagnostop** [comment]
Another one would be fiber (US spelling) versus fibre (British spelling).

**Comment by LaurensWilming** [comment]
Ah, yes. There will be others we haven't thought of yet. There must be websites that list all these alternative spellings...
The reason I think these should be in there is that some papers use one spelling and other papers the other. And the MPO users shouldn't have to know which is which for them to successfully search the ontology.

**Comment by anna-anagnostop** [comment]
Yes, see **Spelling differences in medical terms in British and American English** (http://translation-clinic.com/spelling-medical-terms-british-american-english/)

**Comment by LaurensWilming** [comment]
There you go. You can use that to generate the synonyms!
