### ISSUE TITLE
New term request: abnormal neuronal polarity

### ISSUE THREAD

**Issue by LaurensWilming** [obophenotype/mammalian-phenotype-ontology#2693]
>1. Preferred term label 
**abnormal neuronal polarity**

>2. Synonyms (e.g., absent spleen)
**apolar neurons
multipolar neurons
loss of neuronal polarity**

>3. Textual definition 
**an anomaly in the polarity of the neurons; polarity is determined by the single axon a neuron normally projects**

>4. Any additional notes to clarify the meaning or use of the term. 
**PMID:29089386 describes a KO that results in neurons growing multiple dendrites. Normally they're only supposed to grow one axon, giving the cell polarity. When it grows multiple it becomes multipolar or apolar, depending on your definition.** 

>5. Suggested parent term 
**MP:0002882 abnormal neuron morphology**

**Comment by sbello** [comment]
reference PMID:26133936 - axon-dendrite polarity
MP:0020581
