### ISSUE TITLE
new term request: abnormal pancreatic alpha/beta cell number

### ISSUE THREAD

**Issue by LaurensWilming** [obophenotype/mammalian-phenotype-ontology#2694]
>1. Preferred term label (e.g., asplenia)

**abnormal pancreatic alpha cell number**
**abnormal pancreatic beta cell number**

>3. Textual definition (the definition should be understandable even for non-specialists.

**anomaly in the number of the cells of the pancreas that secrete glucagon**
**anomaly in the number of the cells of the pancreas that secrete insulin**

>4. Any additional notes to clarify the meaning or use of the term. 

**A recent paper described a phenotype where the alpha cell hyperplasia, seen in WT after a certain treatment or seen in a single knockout of a certain gene, was reduced when another gene under study was knocked out and treated with that certain treatment or made into a double-KO with that certain gene. So you can't say it's an increase in alpha cells, nor can you say it's a decrease.**

>5. Suggested parent term 

**MP:0005216 abnormal pancreatic alpha cell morphology
with MP:0009177 and MP:0009176 to become child terms**

**MP:0005217 abnormal pancreatic beta cell morphology
with MP:0003339 and MP:0003645 to become child terms**

**Comment by sbello** [comment]
MP:0020577 - alpha
MP:0020578 - beta
MP:0020579 - delta
MP:0020580 - epsilon
