### ISSUE TITLE
New term request: abnormal cortical subventricular zone

### ISSUE THREAD

**Issue by LaurensWilming** [obophenotype/mammalian-phenotype-ontology#2696]
>1. Preferred term label
**abnormal cortical subventricular zone**

>2. Synonyms
**abnormal cortical SVZ**

>3. Textual definition 
**any structural anomaly of the region of the developing mammalian cortex that extends between the ventricular zone and the intermediate zone (IZ) that developed from the IZ**

>4. Any additional notes to clarify the meaning or use of the term. Please provide a PubMed ID or URL(s) for the source of this information.
**Paper PMID:29033352 discusses goings-on in the SVZ**

>5. Suggested parent term 
**MP:0008457 abnormal cortical intermediate zone morphology**

**Comment by sbello** [comment]
How is this different from MP:0004274 'abnormal embryonic/fetal subventricular zone morphology'?
