### ISSUE TITLE
Inconsistent hierarchy, terminology and granularity between adenomas and adenocarcinomas

### ISSUE THREAD

**Issue by LaurensWilming** [obophenotype/mammalian-phenotype-ontology#2697]
For adenocarcinomas:
```
parent: MP:0002957 increased intestinal adenocarcinoma incidence
   child: MP:0009309 increased small intestine adenocarcinoma incidence
   child: MP:0009310 increased large intestine adenocarcinoma incidence
      grandchild: MP:0009314 increased colon adenocarcinoma incidence
```
For adenomas:
```
parent: MP:0010383 increased adenoma incidence
   child: MP:0002044 increased colonic adenoma incidence
   child: MP:0002404 increased intestinal adenoma incidence

```
Note how _colon adenocarcinoma_ is a child of _large intestine adenocarcinoma_, itself a child of _intestinal adenocarcinoma_, but _colonic adenoma_ is a sibling of _intestinal adenoma_ which has no _small_ and _large intestine_ children. Also note how _adenocarcinomas_ are **colon**, but _adenomas_ are **colonic**.

Thanks,
Laurens

**Comment by sbello** [comment]
Fixed thanks.
