### ISSUE TITLE
logical definitions use ChEBI roles as chemical entities

### ISSUE THREAD

**Issue by balhoff** [obophenotype/mammalian-phenotype-ontology#2698]
When you use MP and Uberon together with a reasoner, some additional axioms imported into Uberon from ChEBI cause unsatisfiable classes in MP. Mostly the logical definitions of these classes have references to levels of circulating hormones. ChEBI defines hormone as a `biological role`, which is a subclass of `specifically dependent continuant` and disjoint with `independent continuant`.

For example, `abnormal circulating androgen level` has this definition:

```
'has part' some 
    (amount
     and ('inheres in' some 
        (androgen
         and ('part of' some blood)))
     and ('has modifier' some abnormal))
```

To make this logically sound I would rewrite it like this:

```
'has part' some 
    (amount
     and ('inheres in' some 
        (('chemical entity' and ('has role' some androgen))
         and ('part of' some blood)))
     and ('has modifier' some abnormal))
```

I would be happy to update these and make a pull request, if you will be okay with these changes. I did this for HPO: https://github.com/obophenotype/human-phenotype-ontology/pull/2646

**Comment by sbello** [comment]
This looks good to me. Thanks for the help Jim. I probably won't be able to get to the pull request until Monday though.

**Comment by balhoff** [comment]
Great, no problem, I still need to actually make the edits.

**Comment by sbello** [comment]
Sounds good. Would you please let me know when you start so I can make sure I don't alter any of the terms you are working on.

**Comment by balhoff** [comment]
I'm working on these:

- 'abnormal circulating adrenaline level'
- 'abnormal circulating aldosterone level'
- 'abnormal circulating androgen level'
- 'abnormal circulating antidiuretic hormone level'
- 'abnormal circulating atrial natriuretic factor level'
- 'abnormal circulating corticosterone level'
- 'abnormal circulating cortisol level'
- 'abnormal circulating dihydrotestosterone level'
- 'abnormal circulating erythropoietin level'
- 'abnormal circulating estradiol level'
- 'abnormal circulating estrogen level'
- 'abnormal circulating gastrin level'
- 'abnormal circulating ghrelin level'
- 'abnormal circulating glucagon level'
- 'abnormal circulating glucocorticoid level'
- 'abnormal circulating gonadotropin level'
- 'abnormal circulating hormone level'
- 'abnormal circulating insulin level'
- 'abnormal circulating insulin-like growth factor I level'
- 'abnormal circulating leptin level'
- 'abnormal circulating mineralocorticoid level'
- 'abnormal circulating noradrenaline level'
- 'abnormal circulating osteocalcin level'
- 'abnormal circulating pancreatic peptide level'
- 'abnormal circulating parathyroid hormone level'
- 'abnormal circulating pituitary hormone level'
- 'abnormal circulating progesterone level'
- 'abnormal circulating testosterone level'
- 'abnormal circulating thyroxine level'
- 'abnormal circulating triiodothyronine level'
- 'absent circulating adrenaline'
- 'absent circulating noradrenaline'
- 'decreased circulating adrenaline level'
- 'decreased circulating adrenocorticotropin level'
- 'decreased circulating aldosterone level'
- 'decreased circulating antidiuretic hormone level'
- 'decreased circulating atrial natriuretic factor'
- 'decreased circulating corticosterone level'
- 'decreased circulating cortisol level'
- 'decreased circulating dihydrotestosterone level'
- 'decreased circulating erythropoietin level'
- 'decreased circulating estradiol level'
- 'decreased circulating estrogen level'
- 'decreased circulating follicle stimulating hormone level'
- 'decreased circulating gastrin level'
- 'decreased circulating ghrelin level'
- 'decreased circulating glucagon level'
- 'decreased circulating glucocorticoid level'
- 'decreased circulating gonadotropin level'
- 'decreased circulating growth hormone level'
- 'decreased circulating insulin level'
- 'decreased circulating insulin-like growth factor I level'
- 'decreased circulating leptin level'
- 'decreased circulating levels of thyroid hormone'
- 'decreased circulating luteinizing hormone level'
- 'decreased circulating mineralocorticoid level'
- 'decreased circulating noradrenaline level'
- 'decreased circulating parathyroid hormone level'
- 'decreased circulating pituitary hormone level'
- 'decreased circulating progesterone level'
- 'decreased circulating prolactin level'
- 'decreased circulating testosterone level'
- 'decreased circulating thyroid-stimulating hormone level'
- 'decreased circulating thyroxine level'
- 'decreased circulating triiodothyronine level'
- 'increased circulating adrenaline level'
- 'increased circulating adrenocorticotropin level'
- 'increased circulating aldosterone level'
- 'increased circulating antidiuretic hormone level'
- 'increased circulating atrial natriuretic factor'
- 'increased circulating corticosterone level'
- 'increased circulating corticotropin-releasing hormone level'
- 'increased circulating cortisol level'
- 'increased circulating dihydrotestosterone level'
- 'increased circulating erythropoietin level'
- 'increased circulating estradiol level'
- 'increased circulating estrogen level'
- 'increased circulating follicle stimulating hormone level'
- 'increased circulating gastrin level'
- 'increased circulating ghrelin level'
- 'increased circulating glucagon level'
- 'increased circulating glucocorticoid level'
- 'increased circulating gonadotropin level'
- 'increased circulating growth hormone level'
- 'increased circulating insulin level'
- 'increased circulating insulin-like growth factor I level'
- 'increased circulating leptin level'
- 'increased circulating levels of thyroid hormone'
- 'increased circulating luteinizing hormone level'
- 'increased circulating mineralocorticoid level'
- 'increased circulating noradrenaline level'
- 'increased circulating parathyroid hormone level'
- 'increased circulating pituitary hormone level'
- 'increased circulating progesterone level'
- 'increased circulating prolactin level'
- 'increased circulating testosterone level'
- 'increased circulating thyroid-stimulating hormone level'
- 'increased circulating thyroxine level'
- 'increased circulating triiodothyronine level'
- 'suppressed circulating follicle stimulating hormone level'
- acidemia
- alkalemia
- taurodontia
