### ISSUE TITLE
new terms request: acute myeloid leukemia, acute undifferentiated leukemia

### ISSUE THREAD

**Issue by LaurensWilming** [obophenotype/mammalian-phenotype-ontology#2701]
>1. Preferred term label 

**1. acute myeloid leukemia incidence** or **acute myelogenous leukemia incidence
2. acute undifferentiated leukemia incidence**
>2. Synonyms 

**1. acute myelogenous** or **myeloid leukemia, acute nonlymphocytic leukemia, ANLL, AML, acute myeloblastic leukemia, acute granulocytic leukemia
2. AUL, stem cell leukemia**

>3. Textual definition 

**1. higher than normal incidence of cancer characterized by rapid onset of abnormal leukocyte proliferation, manifesting as a severe bleeding disorder from coagulation abnormalities, and bone marrow infiltration of abnormal myelocytes
2. higher than normal incidence of cancer characterized by rapid onset of abnormal leukocyte proliferation where the leukocytes are too immature to be able to be classified; manifesting as a severe bleeding disorder from coagulation abnormalities, and bone marrow infiltration of abnormal myelocytes**

>4. Any additional notes to clarify the meaning or use of the term. Please provide a PubMed ID or URL(s) for the source of this information.

**Any paper or textbook that describes AML. PMID:23583447 describes AUL induced by infection. So I wouldn't be able to use the term, but it does exist. https://medical-dictionary.thefreedictionary.com/acute+undifferentiated+leukemia** 

>5. Suggested parent term 

**1. MP:0002026 increased leukemia incidence
2. MP:nnnnnnn acute myelogenous/myeloid leukemia incidence
And _MP:0004049 increased acute promyelocytic leukemia incidence_ should become a child of _MP:nnnnnnn acute myelogenous/myeloid leukemia incidence_. There are more AML subtypes to consider (myeloblastic, monocytic, etc.)**

**Comment by sbello** [comment]
MP:0020838
MP:0020839
