### ISSUE TITLE
new synonym for abnormal platelet shape: platelet dysplasia

### ISSUE THREAD

**Issue by LaurensWilming** [obophenotype/mammalian-phenotype-ontology#2702]
>1. term label 
MP:0003405 abnormal platelet shape

>2. Synonyms 
platelet dysplasia

**Comment by anna-anagnostop** [comment]
We generally use dysplasia as a synonym for abnormal morphology terms (in this case, abnormal platelet morphology MP:0004720). Dysplasia refers to the abnormal shape and appearance, or morphology, of a cell/tissue/organ.

**Comment by anna-anagnostop** [comment]
Added "platelet dysplasia" as a new synonym for abnormal platelet morphology MP:0004720 (NOT as a synonym for abnormal platelet shape MP:0003405).
