### ISSUE TITLE
new terms request: abnormal A, I, H, M lines

### ISSUE THREAD

**Issue by LaurensWilming** [obophenotype/mammalian-phenotype-ontology#2704]
>1. Preferred term label (e.g., asplenia)

**abnormal A lines/bands
abnormal I lines/bands
abnormal H lines/bands
abnormal M lines/bands**

>2. Synonyms (e.g., absent spleen)

**abnormal A bands/lines
abnormal I bands/lines
abnormal H bands/lines
abnormal M bands/lines**

>3. Textual definition 

**whatever the definition of those bands/lines is...**

>4. Any additional notes to clarify the meaning or use of the term.

**Paper PMID:26526197 describes A-band phenotype for one of the genotypes.**

>5. Suggested parent term 

**MP:0004087 abnormal muscle fiber morphology**

**Comment by anna-anagnostop** [comment]
ADD:
abnormal A band ( a child of abnormal sarcomere morphology MP:0004090)
DEF: any structural anomaly of the dark-staining region of a sarcomere in which myosin thick filaments are present; an A band is anisotropic to polarized light and contains the entire length of a single thick filament; its center is traversed by the paler H zone, which in turn contains the M line.
SYN: abnormal A-band
SYN: abnormal A disc 
SYN: abnormal A disk
SYN: abnormal anisotropic disc
SYN: abnormal anisotropic band
SYN: abnormal anisotropic disk 
 SYN: abnormal Q disc
SYN: abnormal Q disk 
SYN: abnormal transverse disc
SYN: abnormal transverse disk
SOURCE: GO:0031672, https://en.wikipedia.org/wiki/Sarcomere

abnormal I band (a child of abnormal sarcomere morphology MP:0004090)
DEF: any structural anomaly of the light band on each side of the Z disc, comprising a region of the sarcomere where thin (actin) filaments are not overlapped by thick (myosin) filaments; the I band is isotropic to polarized light and contains actin, troponin, and tropomyosin; each sarcomere includes half of an I band at each end
SYN: abnormal I-band 
SYN: abnormal I disc 
SYN: abnormal I disk
SYN: abnormal isotropic disc
SYN: abnormal isotropic band
SYN: abnormal isotropic disk
SYN: abnormal J disc
SYN: abnormal J disk
SOURCE: GO:0031674, https://en.wikipedia.org/wiki/Sarcomere

NOTE: abnormal abnormal Z lines MP:0004091 should be made a child of abnormal I band.
Additional synonyms for abnormal abnormal Z lines MP:0004091 should include: abnormal Z-line; abnormal Z-lines; abnormal Z line; abnormal intermediate disc;  abnormal Z disc

abnormal H zone (a child of abnormal A band)
DEF: any structural anomaly of the relatively pale zone traversing the center of the A band of a sarcomere, visible in relaxed muscle fibers; it consists of the central portion of thick (myosin) filaments that are not overlapped by thin (actin) filaments; within the H-zone is a thin dark M line, the attachment site for the thick filaments in the center of the sarcomere
SYN: abnormal H-zone 
SYN: abnormal H band
SYN:  abnormal H disc
SYN:  abnormal H disk

We already have a term for abnormal M lines MP:0004094. This should be made an additional child of abnormal A band. Additional synonyms for abnormal M lines MP:0004094 (and children of) should include: abnormal M line; abnormal M-line;  abnormal M-lines; abnormal M band; abnormal M disc; abnormal M disk; abnormal mesophragma

**Comment by sbello** [comment]
Anna, I'm wondering if we should add 'morphology' to all of these terms? I think it would be more in keeping with the way we usually create terms and be appropriate for the definitions you entered.

**Comment by anna-anagnostop** [comment]
ADDED:
abnormal A band morphology MP:0030566
abnormal I band morphology MP:0030567
abnormal H zone morphology MP:0030568
Changed primary term label for MP:0004094 to abnormal M line morphology
Changed primary term label for MP:0004091 to abnormal Z line morphology
