### ISSUE TITLE
abnormal cardiac muscle tissue morphology MP:0010630 

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2706]
Requested by Michelle Perry April 18, 2018 2:29 PM: 
"I noticed that abnormal cardiac muscle tissue morphology MP:0010630 (and all its children term) are only located under the muscle phenotype tree. This looks odd. I annotated to a child term, cardiac muscle necrosis, and was surprised to see it wasn’t under the cardiovascular phenotype tree".

Consider making the following changes:

abnormal cardiac muscle tissue morphology MP:0010630 (and all its children term) should be made an additional child of abnormal heart morphology MP:0000266.

abnormal myocardium layer morphology MP:0005329 (currently only a child of abnormal abnormal heart layer morphology MP:0005329) should be made an additional child of abnormal cardiac muscle tissue morphology MP:0010630.

Also, it looks like

myocardial necrosis MP:0006085 should be made a child of cardiac muscle necrosis MP:0010632

myocardial hypertrophy MP:0010633 should be made a child of cardiac hypertrophy MP:0001625

myocardium hypoplasia MP:0010500 should be made a child of heart hypoplasia MP:0002740

calcified myocardium MP:0010534 should be made a child of dystrophic cardiac calcinosis MP:0002837

**Comment by cindyJax** [comment]
Cardiac muscle is also found in the pulmonary veins and superior vena cava (sinoatrial node), not exclusively the heart.  Perhaps it is better placed as a child of "cardiovascular system phenotype"

https://onlinelibrary.wiley.com/doi/full/10.1002/jmor.1051170202

https://onlinelibrary.wiley.com/doi/pdf/10.1002/jmor.1051450403

https://www.physiology.org/doi/abs/10.1152/ajpheart.00256.2009

https://www.ncbi.nlm.nih.gov/pubmed/8562136
