### ISSUE TITLE
Hair Loss

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#273]
I'm wondering if it would be useful to have a higher parent term: Hair loss. Alopecia, partial hair loss, premature hair loss and progressive hair loss would all be children. I was annotating J:87589 and all they say is the mice exhibit hair loss and I wasn't sure which term to use. I ended up using partial hair loss \(as they don't state that they completely lose their hair \(but then again, they don't state that they only lose some of their hair\) and if you give them an amino acid restricted-diet, they grow their hair out\) but I don't really know that this is the best term to use. Would have been helpful to have a higher level term to use when they don't specify any details. 

Reported by: monikat

Original Ticket: [obo/mammalian-phenotype-requests/273](https://sourceforge.net/p/obo/mammalian-phenotype-requests/273)

**Comment by cindyJax** [comment]
Previously addressed.
