### ISSUE TITLE
Bifid vs bifurcated tongue

### ISSUE THREAD

**Issue by sbello** [obophenotype/mammalian-phenotype-ontology#2742]
Not sure why we have both bifid tongue (MP:0009909) and bifurcated tongue (MP:0009910). The logical definition for bifid tongue uses the PATO term bifurcated. Also https://www.ncbi.nlm.nih.gov/medgen/82731 has bifurcated tongue as a synonym for bifid tongue.

**Comment by anna-anagnostop** [comment]
I always thought a bifid tongue refers to a tongue divided into two lobes by a median cleft running along the length of the tongue (see Rajendran R (1 January 2009). [Shafer's Textbook Of Oral Pathology](https://books.google.com/books?id=Spk0V6TrCggC&pg=PA27#v=onepage&q&f=false) (6th ed.). Elsevier India. p. 27. ISBN 978-81-312-1570-8, Figure 1-19 and Figure 1-20). Synonyms would include glossoschisis (https://quizlet.com/94042813/mouth-tongue-and-teeth-embryo-flash-cards/; http://www.chop.edu/conditions-diseases/rare-craniofacial-clefts ) although this term is not commonly used. A bifurcated tongue thus refers to a tongue that is split into two halves (specifically) at its anterior tip.
Perhaps the logical definition for bifid tongue (MP:0009909) should use the PATO term “cleft” (see HP:0010297, http://purl.obolibrary.org/obo/HP_0010297). Actually, the MP uses “cleft” in the logical definitions for bifid scrotum, vagina, uterus, nose etc.
Having said that, many resources including HP, MedGen etc use the concepts bifid and bifurcated tongue interchangeably as exact synonyms.

**Comment by sbello** [comment]
bifid= fully split down the middle
bifurcated - just the tip of the tongue is split
review use of cleft vs bifurcated in axioms
PATO cleft def. says groove or fissure and is under concave
bifurcated -is split in 2 parts and is under branched

**Comment by sbello** [comment]
need to refine definition of bifid, and make 2 terms siblings

**Comment by sbello** [comment]
changed bifid tongue to use cleft rather than bifurcated in the axiom
modified definition to make clearer the distinction between bifid and bifurcated tongue terms
made bifurcated tongue a child of abnormal tongue morphology
