### ISSUE TITLE
OWL def for situs ambiguus

### ISSUE THREAD

**Issue by cmungall** [obophenotype/mammalian-phenotype-ontology#2762]
http://purl.obolibrary.org/obo/MP_0002767
has part some (position and (inheres in some anatomical system) and (has modifier some abnormal))

Seems too broad for the text def: An abnormality in which the thoracic and abdominal organs are positioned in such a way with respect to each other and the left-right axis as to be not clearly lateralised and thus have neither the usual, or normal (situs solitus), nor the mirror-imaged (situs inversus) arrangements

**Comment by sbello** [comment]
Thanks Chris. I'll take a look at this.

**Comment by sbello** [comment]
I've removed this definition for now. There are not really good PATO or UBERON terms to accurately reflect the definition of this term.
