### ISSUE TITLE
new term request: increased trans-epidermal water loss

### ISSUE THREAD

**Issue by LaurensWilming** [obophenotype/mammalian-phenotype-ontology#2771]
>1. Preferred term label
**increased trans-epidermal water loss**

>2. Synonyms 

>3. Textual definition 
**Increased loss of water through the skin.**

>4. Any additional notes to clarify the meaning or use of the term. Please provide a PubMed ID or URL(s) for the source of this information.
**PMID:26967477 describes this phenotype.**

>5. Suggested parent term (Please look in the hierarchy of the MP using the [MP Browser]
**MP:0010771 integument phenotype**

**Comment by sbello** [comment]
Would you consider this different from MP:0002796 "impaired skin barrier function"?

**Comment by sbello** [comment]
add this as a synonym to MP:0002796

**Comment by anna-anagnostop** [comment]
Added the following as related synonyms of impaired skin barrier function (MP:0002796)
NEW SYN: increased trans-epidermal water loss
NEW SYN: increased transepidermal water loss
NEW SYN: increased TEWL
NEW SYN: increased TWL
