### ISSUE TITLE
heart rate and RR interval

### ISSUE THREAD

**Issue by tkonopka** [obophenotype/mammalian-phenotype-ontology#2775]
A few levels under abnormal cardiovascular system physiology, there are terms for increased and decreased heart rate (MP:0002626 and MP:0005333) and separate terms for prolonged and shortened RR interval (MP:0010506 and MP:0010507). The term definitions state that RR interval is the inverse of the heart rate, so these two sets of terms describe the same underlying phenotype. However, as far as I can tell, the equivalence is not recorded formally in the ontology. Would it be possible to join these terms? 

One possibility would be to turn two of these terms obsolete (thus reduce the overall number of terms) and then adjust the other two terms and their parents accordingly.

**Comment by sbello** [comment]
I have made shortened and prolonged RR interval children of increased and decreased heart rate, respectively. I don't think we want to merge the terms since you can measure heart rate without using an ECG but I agree that these should be related.
