### ISSUE TITLE
review MP:0005311  (amino acid levels)

### ISSUE THREAD

**Issue by sbello** [obophenotype/mammalian-phenotype-ontology#2777]
Review MP:0005311  (abnormal circulating amino acid level) to see if additional child terms are needed

**Comment by sbello** [comment]
Seems likes we could use additional children here but waiting on an answer in https://github.com/obophenotype/upheno/issues/273 to make sure the CHEBI terms are added correctly.

**Comment by anna-anagnostop** [comment]
Need new terms:

abnormal circulating glutathione level (a child abnormal circulating amino acid level MP:0005311 and abnormal glutathione level MP:0012603 )
DEF: aberrant concentration in the blood of glutathione, a tripeptide compound consisting of glutamic acid attached via its side chain to the N-terminus of cysteinylglycine

increased circulating glutathione level (child of abnormal circulating glutathione level and increased glutathione level MP:0012606 )
DEF: increase in the amount per unit of blood of glutathione, a tripeptide compound consisting of glutamic acid attached via its side chain to the N-terminus of cysteinylglycine
SYN: glutathionemia
SYN: glutathionaemia
Annotations in J:55222

**Comment by anna-anagnostop** [comment]
Added new terms:

abnormal circulating glutathione level MP:0030652
increased circulating glutathione level MP:0030653

abnormal circulating glycine level MP:0030654
increased circulating glycine level MP:0030655
decreased circulating glycine level MP:0030656
Also added: 
abnormal glycine level MP:0030657
increased glycine level MP:0030658
decreased glycine level MP:0030659

abnormal circulating arginine level MP:0030660
increased circulating arginine level MP:0030661
decreased circulating arginine level MP:0030662
Also added: 
abnormal arginine level MP:0030663
increased arginine level MP:0030664
decreased arginine level MP:0030665

abnormal circulating proline level MP:0030666
increased circulating proline level MP:0030667
decreased circulating proline level MP:0030668

abnormal circulating phenylalanine level MP:0030669
increased circulating phenylalanine level MP:0030670
decreased circulating phenylalanine level MP:0030671

abnormal circulating alanine level MP:0030672
increased circulating alanine level MP:0030673
decreased circulating alanine level MP:0030674
