### ISSUE TITLE
ECM

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#278]
Hi Cindy,

When I search “extracellular” or “ECM” or “matrix” I do not find abnormal extracellular matrix component or anything like that which will fit with my Fret1 mutant.  Maybe I should be using the “abnormal basement membrane morphology” term.  If so, would you please put in some synonyms for extracellular matrix and ECM.  Thanks\! Melissa

Reported by: cindyJax

Original Ticket: [obo/mammalian-phenotype-requests/278](https://sourceforge.net/p/obo/mammalian-phenotype-requests/278)

**Comment by cindyJax** [comment]
Already addressed.
