### ISSUE TITLE
renal pelvis not part of ureter

### ISSUE THREAD

**Issue by cmungall** [obophenotype/mammalian-phenotype-ontology#2936]
http://purl.obolibrary.org/obo/MP_0004194

![image](https://user-images.githubusercontent.com/50745/47886325-95d11100-ddf6-11e8-94ee-8873057b7314.png)

I'm not sure KP should be treated as part of the ureter, and hence abnormalities of the KP are not necessarily abnormalities of the ureter.

I think in FMA, KP used to be part_of ureter, but no longer, now it is explicitly continuous_with. 

Uberon used to follow FMA and MP, but will likely change

**Comment by cmungall** [comment]
Some ontologies use upper urinary tract for whole kidney (which includes KP) plus the ureters

**Comment by cmungall** [comment]
Discussion on similar structures in NCIT https://github.com/NCI-Thesaurus/thesaurus-obo-edition/issues/43

**Comment by sbello** [comment]
I've removed the connection to ureter and updated the definition to reflect the revised definition on the NCIT site. This is also in keeping with the EMAP structure where renal pelvis is a child of metanephros.
