### ISSUE TITLE
typo in MP:0020551 definition

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#2961]
Correct typo in definition for abnormal postsynaptic density morphology MP:0020551
DEF: any structural anomaly of the electron dense network of proteins within and adjacent to the postsynaptic membrane of an **asymetric**, neuron-neuron synapse

**asymetric** should be asymmetric

**Comment by sbello** [comment]
fixed, and submitted ticket to GO to fix their definition
