### ISSUE TITLE
New QC: Trailing whitespace

### ISSUE THREAD

**Issue by matentzn** [obophenotype/mammalian-phenotype-ontology#2976]
There are some trailing whitespace violations, which are spaces or tabs in the end of definitions or labels. If you feel like you want to fix them! Certainly pedantic, but in a useful way!

**Comment by matentzn** [comment]
New version for the diligent: 
[trailing-whitespace-violation.txt](https://github.com/obophenotype/mammalian-phenotype-ontology/files/3231955/trailing-whitespace-violation.txt)

**Comment by anna-anagnostop** [comment]
Working on #2976

**Comment by matentzn** [comment]
Amazing guys! All sorted. QC passed!

**Comment by anna-anagnostop** [comment]
Great Nico! Thanks!
