### ISSUE TITLE
New term: decreased lymphocyte chemotaxis

### ISSUE THREAD

**Issue by LaurensWilming** [obophenotype/mammalian-phenotype-ontology#2984]
>1. Preferred term label 
**decreased lymphocyte chemotaxis**

>3. Textual definition 
**reduction in the directed movement of a lymphocyte in response to an external stimulus**

>4. Any additional notes to clarify the meaning or use of the term. 
**There exists the MP:0011826 increased lymphocyte chemotaxis term. Its description should be changed to _increase in the directed movement of a lymphocyte in response to an external stimulus_**

>5. Suggested parent term 
**MP:0003156 abnormal leukocyte migration**

**Comment by anna-anagnostop** [comment]
Not allowed to change the textual definition for increased lymphocyte chemotaxis MP:0011826; therefore, changed the primary term label to _abnormal lymphocyte chemotaxis_ to accurately reflect its description ("any anomaly in the directed movement of a lymphocyte in response to an external stimulus"). This will also provide the missing parent term.

Then added new child terms:

decreased lymphocyte chemotaxis MP:0031207
increased lymphocyte chemotaxis (new) MP:0031208
