### ISSUE TITLE
Migrate MP to ODK 1.2.10

### ISSUE THREAD

**Issue by matentzn** [obophenotype/mammalian-phenotype-ontology#2993]
Just for reference. Next steps required:

- [x] Understand one last oddity in the obo file diff (Nico)
- [x] @sbello checking three remaining subsumptions (Sue)
- [x] Make sure new OBO jenkins server generates the right files for Sue (Nico)
- [x] Remove all GitHub release products (they are already too big) and add them to .gitignore
- [x] Merge pull request

**Comment by matentzn** [comment]
I think we are done with [phase 1](https://stars-app.renci.org/owldiff/diff?left=http://purl.obolibrary.org/obo/mp.obo&right=https://raw.githubusercontent.com/monarch-ebi-dev/ontologies/master/mp.obo&loadimports=true)

**Comment by matentzn** [comment]
@sbello Are you happy with ignoring the three subsumptions for now, and moving forward?

**Comment by sbello** [comment]
@matentzn Have you done another run since I made changes on Friday? I modified the parentage of abnormal common myeloid progenitor cell morphology and I would like to know if that fixed the subsumption.
I'm fine with ignoring the other 2. Eventually I'll fix the biological issue with their placement, once I figure out what that fix should be.

**Comment by matentzn** [comment]
I just ran it! check the diff in the link above (phase 1)

**Comment by sbello** [comment]
I think we had overlapping comments there @matentzn I did check the phase one link and the myeloid one is gone.

**Comment by matentzn** [comment]
Hey @sbello While I am trying to get the new Jenkins to run: Do you have any news on your Laptop :P Hhaaha sorry, just so I can prioritise more effectively.

**Comment by sbello** [comment]
Just got back the bid estimates, so things are moving :)

**Comment by matentzn** [comment]
Were we ok with losing this subsumption:

```
+ SubClassOf(<http://purl.obolibrary.org/obo/MP_0030960> <http://purl.obolibrary.org/obo/MP_0003156>)
```

That is the last remaining issue in the diff I think

**Comment by matentzn** [comment]
This is done now!
