### ISSUE TITLE
eyelid retraction definition and EQ statement

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#3004]
The current textual definition for eyelid retraction MP:0006166 is:

DEF: eyelids open abnormally wide
(is-a abnormal eyelid aperture)

The EQ statement is:'

has part' some 
    ('increased size'
     and ('inheres in' some 'palpebral fissure')
     and ('has modifier' some abnormal))

HP defines eyelid retraction (http://purl.obolibrary.org/obo/HP_0500043) as:
With the eyes in primary position, the sclera is visible above the superior corneal limbus. [ https://www.aao.org/bcscsnippetdetail.aspx?id=03ad3eb3-3445-4be2-9470-2c4845169b75 http://www.ncbi.nlm.nih.gov/pubmed/8719687 ] 

NCIT defines Lid Retraction (http://purl.obolibrary.org/obo/NCIT_C118866) as:
Abnormal superior displacement of resting upper lid margin or abnormal inferior displacement of resting lower lid margin

I think we should consider changing the textual def and EQ for MP:0006166. 
However, is the PATO term for 'retracted' (http://purl.obolibrary.org/obo/PATO_0001477) appropriate in this case?

**Comment by sbello** [comment]
modify def to use NCIT, remove EQ

**Comment by anna-anagnostop** [comment]
modified def to use NCIT and removed EQ
