### ISSUE TITLE
New QC: Duplicate labels

### ISSUE THREAD

**Issue by matentzn** [obophenotype/mammalian-phenotype-ontology#3007]
The following classes have duplicate labels according to new QC:

```	
ERROR	duplicate_label	http://purl.obolibrary.org/obo/mp/mp-equivalent-axioms-subq#has_central_participant	rdfs:label	results_in_change_to	
ERROR	duplicate_label	http://purl.obolibrary.org/obo/mp/mp-equivalent-axioms-subq#results_in_change_to	rdfs:label	results_in_change_to	
ERROR	duplicate_label	MP:0000355	rdfs:label	obsolete Increased Purkinje Cell Size	
ERROR	duplicate_label	MP:0000882	rdfs:label	obsolete Increased Purkinje Cell Size	
ERROR	duplicate_label	MP:0000357	rdfs:label	obsolete Decreased Purkinje Cell Size	
ERROR	duplicate_label	MP:0000883	rdfs:label	obsolete Decreased Purkinje Cell Size	
```

**Comment by sbello** [comment]
fixed the labels for the obsolete terms so they are not exact duplicates
In the future could we ignore the obsolete terms?
Not sure how to find the first example. When I search for results in change to I only get one result in the label category

**Comment by matentzn** [comment]
Great! What do you mean by "ignore obsolete terms?" Unfortunately, this exact part of the QC is OBO Foundry standard and baked into ROBOT, and changing this will not be easily possible :P 

Anyways, I fixed the last one, so: 0 errors on all the QC tests! MP is clean as a whistle :P good job @sbello @anna-anagnostop

**Comment by sbello** [comment]
Mostly just I don't care if two obsolete terms have the same label, they are obsolete and ought not to be used. But if it is difficult to not QC this information for obsolete terms then that is fine, especially since they are all fixed now.
