### ISSUE TITLE
display issue on public MP broswer

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#3009]
When you search the public MGI MP browser for immature B cell (or immature B-cell), the 12 terms returned (see below) appear as follows in the **Phenotype Search** section:

abnormal immature**b>** B cell morphology
absent immature**b>** B cells
increased immature**b>** B cell number
decreased immature**b>** B cell number
abnormal immature**b>** B cell number
increased nucleated erythrocyte cell number (increased immature**b>** red blood cell number)
increased DN2 thymocyte number (increased DN2 alpha-beta immature**b>** T-cell number)
decreased DN2 thymocyte number (decreased DN2 alpha-beta immature**b>** T-cell number)
increased DN3 thymocyte number (increased DN3 alpha-beta immature**b>** T-cell number)
decreased DN3 thymocyte number (decreased DN3 alpha-beta immature**b>** T-cell number)
increased DN4 thymocyte number (matches across multiple synonyms)
decreased DN4 thymocyte number (matches across multiple synonyms)

The incorrect display becomes apparent as soon as you start typing and the autocomplete menu is activated. However, these terms display properly in the Term Detail section.

If you type just immature or B cell or B-cell, then all returned immature B cell terms display normally in the Phenotype Search section:

abnormal immature B cell morphology
absent immature B cells
increased immature B cell number
decreased immature B cell number
abnormal immature B cell number

**Comment by sbello** [comment]
This is known autocomplete bug. There is a TR to fix close.
