### ISSUE TITLE
fasting glucose in stead of fasted MP:0013277?

### ISSUE THREAD

**Issue by LaurensWilming** [obophenotype/mammalian-phenotype-ontology#3017]
MP:0013277 abnormal fasted circulating glucose level
MP:0013278 decreased fasted circulating glucose level
MP:0013279 increased fasted circulating glucose level

If you google "**fasting** glucose" you get 65 million hits. 
If you google "**fasted** glucose" you get 6.6 million hits (and you don't actually see the word "fasted" in any of the previews; just fasting!). I've personally never seen it referred to as **fasted**: it's always **fasting**. So I'd like to suggest changing it accordingly and create a synonym to fasted.

Thanks,
Laurens

**Comment by anna-anagnostop** [comment]
Changed the term label to fasting and added a synonym to fasted for MP:0013277, MP:0013278 and MP:0013279
