### ISSUE TITLE
New terms relating to circulating lipid level

### ISSUE THREAD

**Issue by LaurensWilming** [obophenotype/mammalian-phenotype-ontology#3051]
>If this is a request for a new term, please provide us with the following information.

>1. Preferred term label

**1. Hypolipidemia
2. Decreased circulating phytosterol level**

>2. Synonyms

**1. hypolipidaemia | hypolipaemia | hypolipemia
2. decreased circulating phytosterol concentration | decreased circulating plant sterol concentration | decreased circulating plant sterol level**

>3. Textual definition (the definition should be understandable even for non-specialists. 

**1. abnormally low concentration of lipids in the circulating blood
2. decrease in the amount of phytosterols in the blood; commonly ingested phytosterols include beta-sitosterol, campesterol, and stigmasterol**

>4. Any additional notes to clarify the meaning or use of the term. 

**1. PMID:30991053 only mentions "reduced blood lipid levels" without specifying which ones. Also, hyperlipidemia exists as standalone term, so why not hypolipidemia?
2. I have no input on the phytosterol level, other than that I noticed that was the only term in this branch that does not have an increased-decreased pair!**

>5. Suggested parent term

**1. MP:0003949 abnormal circulating lipid level
2. MP:0010075 abnormal circulating phytosterol level**

**Comment by anna-anagnostop** [comment]
Added new terms:

hypolipidemia MP:0031206 [Annotations from PMID:30991053 (J:277247)]

decreased circulating phytosterol level MP:0031205
