### ISSUE TITLE
New IMPC behavior terms

### ISSUE THREAD

**Issue by sbello** [obophenotype/mammalian-phenotype-ontology#3059]
IMPC has requested a number of new behavior terms (see attached spreadsheet)
[IMPC_New_MP_terms_required_2019-08-21.xlsx](https://github.com/obophenotype/mammalian-phenotype-ontology/files/3525716/IMPC_New_MP_terms_required_2019-08-21.xlsx)

**Comment by sbello** [comment]
also requests decreased thigmotaxis

**Comment by matentzn** [comment]
Many seem to immediately apply to the default abnormalBehaviour pattern and increased/decreased rate of behaviour? Shall we try and curate them as patterns?

**Comment by sbello** [comment]
Seems reasonable. I'll take a look at the patterns when I start working on these.

**Comment by sbello** [comment]
Spoke with the IMPC team most of the parameters would fall under existing activity or exploration terms. We need to change the parentage of the thigmotaxis terms  from anxiety to locomotor behavior as the current placement requires more factors than just 'thigmotaxic' behavior to make the relationship to anxiety correct.
