### ISSUE TITLE
MP:0009848 and MP:0009849 descriptions swapped?

### ISSUE THREAD

**Issue by LaurensWilming** [obophenotype/mammalian-phenotype-ontology#3060]
MP:0009848 "increased horizontal stereotypic behavior" and MP:0009849 "increased vertical stereotypic behavior" descriptions seem to have been swapped?
"increased **horizontal** stereotypic behavior" - **increase in the frequency of repetitive rearings (greater than one per second)**
"increased **vertical** stereotypic behavior" - **increase in the frequency of vertical crossings (greater than one per second)**
Surely rearing is a vertical behavior, and crossing a horizontal behavior? As it is in MP:0020167, MP:0002757 and MP:0002574.

Laurens

**Comment by sbello** [comment]
Yes the horizontal definition was wrong, I've corrected this. The vertical one is okay, since it refers to vertical crossings, that is crossing a set of lines in the vertical plane not the horizontal one.
