### ISSUE TITLE
Review axiom for impaired ossification of basisphenoid bone 

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#3072]
impaired ossification of basisphenoid bone MP:0000105  currently uses:

'has part' some 
    ('decreased rate'
     and ('inheres in' some ossification)
     and ('**inheres in**' some 'basisphenoid bone')
     and ('has modifier' some abnormal))

Second 'inheres in" should be deleted; replace with 'part of'

**Comment by matentzn** [comment]
inheres in should never appear more than once; I cant tell you about what is correct here, but inheres in is conceptual **functional**, so it means that it can be only referring to exactly one thing. Thanks for catching that!

**Comment by anna-anagnostop** [comment]
"'has_part' some ('decreased rate' and ('inheres_in' some (ossification and ('occurs_in' some 'basisphenoid bones'))) and  ('has_modifier' some 'abnormal'))"
