### ISSUE TITLE
replace which with that

### ISSUE THREAD

**Issue by LaurensWilming** [obophenotype/mammalian-phenotype-ontology#3145]
MP:0003731 and its children: ...the retinal layer **that** contains... _[correct]_
MP:0003732 and its children: ...the retinal layer **that** is the site of... _[correct]_
MP:0003733 and its children: ...the retinal layer **which** contains... _[wrong]_

There may of course be other instances that use **which** in stead of **that**. (No, not "There may of course be other instances which use **which** in stead of **that**." But "There may of course be other instances, which are unknown to me, that use **which** in stead of **that**.")

> **That** is used in defining clauses. A defining clause (also called an essential clause or a restrictive clause) gives information essential to the meaning of the sentence. 
> **Which** is used in non-defining clauses. Unlike defining clauses, non-defining clauses (also called nonessential or nonrestrictive clauses) don’t limit the meaning of the sentence. You might lose interesting details if you remove them, but the meaning of the sentence wouldn’t change. Sometimes, these phrases are set off by commas.

**Comment by anna-anagnostop** [comment]
Replaced which with that for MP:0003733 and its children.

**Comment by anna-anagnostop** [comment]
Other instances that use "which" in stead of "that":

abnormal telomere length MP:0003155 
def: abnormal length of the terminal  repetitive DNA section of a chromosome which is involved in chromosomal  replication and senescence, and which protects the end of the chromosome  from deterioration; normal length is a few hundred base pairs
(plus its decreased and increased child terms)

**Comment by anna-anagnostop** [comment]
Replaced 'which' with 'that' in the txtual definition for abnormal telomere length MP:0003155 and its child terms MP:0030927 and MP:0030928.
