### ISSUE TITLE
new term request: retinal inner nuclear layer degeneration

### ISSUE THREAD

**Issue by LaurensWilming** [obophenotype/mammalian-phenotype-ontology#3146]
>1. Preferred term label
**retinal inner nuclear layer degeneration**

>3. Textual definition 
**a retrogressive impairment or destruction of the retinal layer that contains the cell bodies of bipolar, horizontal, and amacrine cells**

>4. Any additional notes to clarify the meaning or use of the term. 
**there are terms for retinal _outer nuclear layer degeneration_, _retinal photoreceptor degeneration_, _retinal ganglion cell degeneration_.**

>5. Suggested parent term 
**MP:0003733 abnormal retinal inner nuclear layer morphology**

**Comment by anna-anagnostop** [comment]
Added new term:
retinal inner nuclear layer degeneration MP:0031198
