### ISSUE TITLE
lowered ear position MP:0000024

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#3163]
lowered ear position MP:0000024

Remove "protruding ears" (currently a broad synonym)

ADD exact synonyms: low-set ears; low set ears; lowset ears
ADD melotia as a related synonym

DB cross-reference: HP:0000369

Current EQ:

has part some (decreased position and (inheres in some external ear) and (has modifier some abnormal))

Why decreased position not lowered? 

Review PATO definition and organization
    
EQ in PATO for decreased position PATO:0001476 seems odd

position and (decreased_in_magnitude_relative_to some normal)

**Comment by matentzn** [comment]
Note also this:
https://github.com/obophenotype/upheno/pull/615#issuecomment-592962208

@nicolevasilevsky maybe coordinate with @anna-anagnostop on this one!

**Comment by anna-anagnostop** [comment]
Made "protruding ears" a related synonym of prominent ears MP:0000021.

Did not change EQ for lowered ear position MP:0000024 for now; added exact synonyms (low-set ears; low set ears; lowset ears) and related synonym (melotia = congenital displacement of the auricle of the ear onto the cheek)
