### ISSUE TITLE
New term: increased mammary duct terminal end bud number

### ISSUE THREAD

**Issue by LaurensWilming** [obophenotype/mammalian-phenotype-ontology#3180]
>If this is a request for a new term, please provide us with the following information.

>1. Preferred term label
**increased mammary duct terminal end bud number**

>3. Textual definition 
**increase in the number of unique club-shaped epithelial structures normally formed at the tip of the mammary duct at the onset of puberty (approximately 3 weeks of age in mouse) under the action of circulating hormones; normally, TEBs proliferate, ramify, and actively invade the fad pad to allow the formation of a complex branching structure; this process of branching morphogenesis concludes at about 10-12 weeks of age in mouse, when TEBs have traversed the length of the fat pad and a fully developed ductal tree has formed; increase in TEBs is often associated with increased ductal outgrowth and branching morphogenesis**

>4. Any additional notes to clarify the meaning or use of the term. Please provide a PubMed ID or URL(s) for the source of this information.
**PMID:29326438: Phenotypic characterization of the Nmi knockout mice revealed significantly enhanced ductal extension during pubertal mammary development, as well as increased terminal end bud number (Fig. 2a).** 

>5. Suggested parent term 
**MP:0013782 abnormal mammary duct terminal end bud morphology**

**Comment by anna-anagnostop** [comment]
Added new terms:

decreased mammary duct terminal end bud number MP:0031174
increased mammary duct terminal end bud number MP:0031175

Also, made absent mammary duct terminal end bud MP:0013783 a child of decreased mammary duct terminal end bud number MP:0031174
