### ISSUE TITLE
Synonym requests for 'altered metastatic potential' and children

### ISSUE THREAD

**Issue by LaurensWilming** [obophenotype/mammalian-phenotype-ontology#3181]
>2. Synonyms 
_MP:0000858 altered metastatic potential_
**change in metastasis potential
change in potential to create metastases**
_MP:0001273 decreased metastatic potential_
**reduction in metastasis potential
reduction in potential to create metastases**
_MP:0001272 increased metastatic potential_
**increase in metastasis potential
increase in potential to create metastases**

Because when I searched on "metastas" I found nothing!

Thanks,
Laurens

**Comment by anna-anagnostop** [comment]
Added synonyms; used "develop" instead of "create"
