### ISSUE TITLE
misspellings

### ISSUE THREAD

**Issue by slaulederkind** [obophenotype/mammalian-phenotype-ontology#3190]
The spellings in many MP terms (for example: "abnormal renal reabsorbtion" (MP:0010107) that have "reabsorbtion" need to be corrected to "reabsorption".

RGD:sjwang

**Comment by anna-anagnostop** [comment]
It appears that most MP atrophy terms still include "reabsorbtion" in their definition or synonyms. 
I am re-opening this issue to review these terms and correct the typo which was largely propagated by cutting+pasting part of the definition when a new term was created.

**Comment by slaulederkind** [comment]
Thank you, Anna.

**Comment by anna-anagnostop** [comment]
You are very welcome.
