### ISSUE TITLE
hemiparesis and hemiplegia

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#3248]
hemiparesis (a child of paresis MP:0000754) 
DEF: mild loss of strength in the arm, leg, and sometimes face on one side of the body
SYN: unilateral paresis
SOURCE: https://www.healthline.com/health/hemiparesis-vs-hemiplegia, [HP:0001269 ](http://purl.obolibrary.org/obo/HP_0001269)
Annotations: J:215446 and J:97932 (annotated to weakness),  J:89215 (annotated to head tilt)

hemiplegia (a child of paralysis MP:0000753)
DEF: severe or complete loss of muscle function (paralysis) in the arm, leg, and in some cases the face on one side of the body
SYN: paralysis on one side of body 
SOURCE: https://www.healthline.com/health/hemiparesis-vs-hemiplegia, [HP:0002301 ](http://purl.obolibrary.org/obo/HP_0002301)

Need to adjust definitions to make them more broadly applicable. What is the relationship to paralysis MP:0000753 (amend def complete or severe loss?), paresis MP:0000754 and paraparesis MP:0009434? 

Does paraparesis involve **both** legs?

Also, check paresis MP:0000754 (SYN: partial paralysis synonym) amend def to "**mild** or partial loss of power of voluntary movement in a muscle through injury or disease of it or its nerve supply"? split into hindlimb and forelimb paresis?

**Comment by sbello** [comment]
hemiparesis
DEF: mild loss of strength in the limb(s) and sometimes face on one side of the body

hemiplegia
DEF: severe or complete loss of muscle function (paralysis) in the limb(s) and in some cases the face on one side of the body

looking at multiple sources it appears that paraparesis impacts both limbs (Taber's, online sources)

**Comment by anna-anagnostop** [comment]
Added new terms:

hemiparesis MP:0031201
hemiplegia MP:0031202
forelimb paresis MP:0031203
hindlimb paresis MP:0031204

Made paraparesis MP:0009434 a child of hindlimb paresis MP:0031204

**Comment by anna-anagnostop** [comment]
Following further discussion with Sue, I reopened the issue to:

- Amend definition for paraparesis MP:0009434; now reads as "a weakness affecting **both** lower or hind limbs"

- Remove all synonyms of paraparesis MP:0009434 (hind limb weakness | hindlimb weakness | lameness | leg weakness) and place them under hindlimb paresis MP:0031204 - make all synonyms exact except for lameness (related synonym)

- Remove EQ from paraparesis MP:0009434 (see below) and add it to hindlimb paresis MP:0031204
'has part' some 
    ('decreased strength'
     and ('inheres in' some hindlimb)
     and ('has modifier' some abnormal))
