### ISSUE TITLE
enlarged liver sinusoidal spaces MP:0000602 

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#3251]
For enlarged liver sinusoidal spaces MP:0000602, the EQ uses:

has part some (increased
      size and (inheres
      in some 
      liver perisinusoidal space) and (has
      modifier some 
      abnormal))
    
EQ should be using "hepatic sinusoidal space" UBERON:0014400, not "liver perisinusoidal space" UBERON:0006729. 

Also, the textual def seems a little off: larger than normal sized blood-filled cavities in the liver

Per PMID:15361506 and PMID:29844855, hepatic sinusoidal dilatation is defined as sinusoidal space (lumen) more than one hepatocyte plate in width. 

Per PMID:29392360 Hepatic sinusoidal dilatation refers to the enlargement of the hepatic capillaries 

A number of annotations to MP:0000602 specifically refer to dilated sinusoids or sinusoidal spaces. 

Should we change the term label to dilated based on def above? or obsolete and add new term hepatic sinusoidal dilatation?

**Comment by sbello** [comment]
Agree should use "hepatic sinusoidal space" UBERON:0014400

**Comment by sbello** [comment]
Lets change the label to dilated 
retain enlarged as a synonym
add hepatic sinusoidal dilation as a synonym
clarify the definition to better define sinusoidal space

**Comment by anna-anagnostop** [comment]
SUGGESTED DEF: an expansion in the volume or area of the lumen (space) that is enclosed by a liver sinusoid

**Comment by anna-anagnostop** [comment]
Changed primary label to dilated.
Used definition suggested above.
Changed EQ to use **dilated** (instead of _increased size_) and **hepatic sinusoidal space**" UBERON:0014400
Added hepatic sinusoidal dilation as an exact synonym
Retained enlarged hepatic sinusoidal spaces and increased liver sinusoidal space size as exact synonyms (deleted enlarged sinusoidal spaces as a broad synonym).

CHECK ALSO: dilated respiratory conducting tubes MP:0010856
