### ISSUE TITLE
child terms naming inconsistency: MP:0008836 abnormal transforming growth factor beta level

### ISSUE THREAD

**Issue by LaurensWilming** [obophenotype/mammalian-phenotype-ontology#3257]
Hi,

_MP:0008836 abnormal transforming growth factor beta level_ has two children that don't mention **beta**:
_MP:0008838 decreased transforming growth factor level
MP:0008837 increased transforming growth factor level_

Could you rename those children 
_MP:0008838 decreased transforming growth factor **beta** level_
_MP:0008837 increased transforming growth factor **beta** level_

Thanks,
Laurens

**Comment by anna-anagnostop** [comment]
Renamed child terms MP:0008838 and MP:0008837 to include "beta" in the term label.
