### ISSUE TITLE
respiratory distress versus dyspnea

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#3264]
In the MP Ontology respiratory distress MP:0001954 _is-a_ abnormal breathing pattern currently defined as follows:

respiratory distress MP:0001954
DEF: physical difficulty or inability to breathe; shortness of breath
**Exact synonyms include**: dyspnea | dyspnoea |  gasping |  labored breathing | laboured breathing | shortness of breath

In the HPO, Dyspnea HP:0002094 and Respiratory distress HP:0002098 have very similar definitions but appear to be different. Respiratory distress HP:0002098 is a child of Dyspnea HP:0002094 but there is some overlap of synonyms as well.

See HPO GitHub issue https://github.com/obophenotype/human-phenotype-ontology/issues/6058

It appears that dyspnea (shortness of breath) is a subjective experience (i.e. _symptom_) reported by the patient, whereas respiratory distress is a term used by clinicians, combining the patient’s subjective sensation of dyspnea with other signs indicating difficulty breathing.

See definition below from OnlineMedicine Notebook https://www.timeofcare.com/respiratory-distress-failure-arrest/

**Respiratory distress is a clinical state characterized by abnormal (increased or decreased) respiratory rate or effort. It encompasses a spectrum of signs from tachypnea with retractions to agonal gasps. Respiratory distress includes increased work of breathing, inadequate respiratory effort (e.g. hypoventilation or bradypnea), and irregular breathing**.

Do we still need to differentiate between these two in the MP, bearing in mind that a mouse/rat cannot communicate (self report) the feeling of difficult (labored) breathing?

**Comment by sbello** [comment]
Suggest clarifying definition to "physical difficulty or impaired ability to breathe; signs include: shortness of breath, labored breathing, gasping"

**Comment by anna-anagnostop** [comment]
Amended def to read as: "physical difficulty or impaired ability to breathe; signs include: shortness of breath, labored breathing, gasping, increased work of breathing, inadequate respiratory effort, and/or irregular breathing", as suggested above.

Changed all exact synonyms dyspnea | dyspnoea | gasping | labored breathing | laboured breathing | shortness of breath to **NARROW** synonyms
