### ISSUE TITLE
abnormal liver sinusoidal endothelial cell morphology

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#3289]
Add new term:
abnormal liver sinusoidal endothelial cell morphology (a child of abnormal liver sinusoid morphology MP:0008989 and abnormal abnormal vascular endothelial cell morphology MP:0006055)
DEF: any structural anomaly of the endothelial cells that line the hepatic sinusoids, constituting the sinusoidal wall (aka sinusoidal endothelium or endothelial lining); LSECs are exposed to blood originating from both the gut and the systemic circulation and are thus ideally situated to remove and recycle blood-borne proteins and lipids; LCECs represent the most abundant non-parenchymal hepatic cell population and are characterized by the presence of open pores (fenestrae) that lack a diaphragm or basal lamina and are grouped into organized sieve plates, rendering LSECs highly permeable; LSECs play vital physiological and immunological functions, including filtration, endocytosis, antigen presentation and leukocyte recruitment, and in combination with Kupffer cells, constitute the most powerful scavenger system in the body
SOURCE: PMID:29844586, PMID:12437787
SYN: abnormal hepatic sinusoidal endothelial cell morphology
SYN: abnormal LSEC morphology
SYN: abnormal HSEC morphology

**Comment by sbello** [comment]
any structural anomaly of the endothelial cells that line the hepatic sinusoids, constituting the sinusoidal wall; these are the most abundant non-parenchymal hepatic cell population, characterized by the presence of sieve plates consisting of grouped fenestrae lacking a diaphragm or basal lamina, and play roles in filtration, endocytosis, antigen presentation and leukocyte recruitment, and in combination with Kupffer cells, constitute a scavenger system in the body

**Comment by anna-anagnostop** [comment]
Added new term:
abnormal liver sinusoidal endothelial cell morphology MP:0031148
Suggested placement is correct.
