### ISSUE TITLE
comments field will go public - check display of database_cross_references

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#3300]
Examples of MP terms with a rdfs:comment that has a database_cross_reference (from http://bhmgiapp14ld.jax.org/~lec/mgi/dbutils/mgidbmigration/tr12571/tr12571.csh.log).

Once the comments field goes public, we need to check if the annotations on comments are displayed properly and decide whether we want them displayed or excluded.

- abnormal circulating cystathionine level                             |  841634665 |          1000 | cystathionine can be directly interconverted to cysteine; cystathionine is not normally detectable in plasma {xref="HP:0003286"}

- abnormal freezing behavior                                           |  645487667 |          1000 | In most prey animals this is part of a predator avoidance response, with the individual assuming a hunched posture {xref="PMID:12837573"}

- abnormal tooth placode morphology                                    |  735813266 |          1000 | The term placode has not been universally adopted in the field of tooth development research; in mouse, stages prior to bud (E11–E12.5) have often been collectively referred to as the epithelial thickening, dental lamina, or simply initiation stage {xref="PMID:24487243"}

- dry gangrene                                                         | 1176674925 |          1000 | The term dry is used only when referring to a limb or to the gut; in other locations, this same type of necrosis is called an infarction, such as myocardial infarction {xref="https://en.wikipedia.org/wiki/Gangrene#Dry_gangrene"}

**Comment by sbello** [comment]
Need to submit request to MGI to fix display

**Comment by anna-anagnostop** [comment]
New [TR # 13427](http://wts.informatics.jax.org/searches/tr.detail.cgi?TR_Nr=13427) put in.
