### ISSUE TITLE
serum zinc level terms

### ISSUE THREAD

**Issue by sbello** [obophenotype/mammalian-phenotype-ontology#3308]
currently we have tissue specific zinc terms but no term for serum zinc levels, we should add terms for abnormal/increased/decreased serum zinc 

relates to COVID comorbid - see https://www.medrxiv.org/content/10.1101/2020.10.07.20208645v1.full.pdf

**Comment by anna-anagnostop** [comment]
abnormal circulating zinc level
DEF: any anomaly in the blood concentration of zinc

decreased circulating zinc level
DEF: less than the normal concentration of zinc in the blood
SYN: reduced circulating zinc level

increased circulating zinc level
DEF: greater than the normal concentration of zinc in the blood
SYN: elevated circulating zinc level

**Comment by anna-anagnostop** [comment]
Added new terms:
abnormal circulating zinc level MP:0031171
decreased circulating zinc level MP:0031172
increased circulating zinc level MP:0031173
