### ISSUE TITLE
term cleanup

### ISSUE THREAD

**Issue by sbello** [obophenotype/mammalian-phenotype-ontology#3313]
From a user
In a few places it might be possible to standardize it a bit more ?!?

For example:

increased circulating free fatty acid level
abnormal circulating free fatty acids level
(with and without "s")
or
decreased mitochondrial fission
increased mitochondria size
(with and without "l")

We need to review the fatty acid and mitochondrial branches to standardize this.

use free fatty acids and mitochondrial as the primary term labels use the other as a synonym

**Comment by anna-anagnostop** [comment]
Reviewed the entire fatty acid branch (everything under abnormal fatty acid level MP:0005280).

Used fatty acids and mitochondrial as the primary term labels; used fatty acid and mitochondria as a synonym, where needed.

Also, added EQ for abnormal mitochondrial shape MP:0011633 (missing).
