### ISSUE TITLE
cataract versus cataracts clean-up

### ISSUE THREAD

**Issue by LaurensWilming** [obophenotype/mammalian-phenotype-ontology#3314]
The cataract family terms should be made consistent with regards to singular/plural.

MP:0001304 cataract
MP:0010255 cortical cataract**s** (children also plural)
MP:0013731 immature cataract
MP:0010262 lamellar cataract**s**
MP:0013732 mature cataract
MP:0010254 nuclear cataract**s**
MP:0010258 polar cataracts (children also plural)
MP:0010251 subcapsular cataract**s** (children also plural)
MP:0010261 sutural cataract**s**
MP:0010263 total cataract**s**

**Comment by anna-anagnostop** [comment]
use singular in the primary term labels; use plural as an exact synonym
