### ISSUE TITLE
Synonym request: Vitreous body

### ISSUE THREAD

**Issue by LaurensWilming** [obophenotype/mammalian-phenotype-ontology#3315]
MP:0002699 abnormal vitreous body morphology (and all relevant children) synonyms for **vitreous body**:
**vitreous humor**
**vitreous humour** 
**vitreous chamber**

**Comment by anna-anagnostop** [comment]
These terms are not sysnonymous. See UBERON hierarchy below:
![image](https://user-images.githubusercontent.com/13942924/97166316-6e9a4980-175b-11eb-9c42-bad6c02640f7.png)
