### ISSUE TITLE
Synonym request: increased bone marrow cellularity

### ISSUE THREAD

**Issue by LaurensWilming** [obophenotype/mammalian-phenotype-ontology#3321]
MP:0000321 increased bone marrow cell number
**synonym:  increased bone marrow cellularity**

PMID:31295380

**Comment by anna-anagnostop** [comment]
Following discussion with Sue, we decided to:

- Remove absent common myeloid progenitor cells MP:0000239 from under absent bone marrow cell MP:0000175 

- Amend textual def of absent bone marrow cell MP:0000175 to clarify "lack of **all** cells that make up the core cavities of bones"

- Change primary term label for decreased bone marrow cell number MP:0000333 to _"bone marrow hypoplasia"_

Add synonyms: hypocellular bone marrow | decreased bone marrow cellularity | reduced bone marrow cellularity | bone marrow      hypocellularity | hypoplastic bone marrow | decreased bone marrow cell number |  reduced bone marrow cell number

Questions: 

Do we designate all above synonyms as "exact"?

Do we need to change the EQ to use _hypoplastic_ or keep the EQ as is ['has part' some ('decreased amount' and ('inheres in' some 'bone marrow cell') and ('has modifier' some abnormal))], given that the textual definition remains "decreased number of cells that make up the core cavities of bones when compared to the normal state"? 

See discrepancy in EQs for mesangial cell hyperplasia MP:0011427 and mesangial cell hypoplasia MP:0011428; Sertoli cell hyperplasia MP:0002776 and Sertoli cell hypoplasia MP:0005250 - EQs need to be consistent

- Change primary term label for increased bone marrow cell number MP:0000321 to "**bone marrow hyperplasia**"
Add synonyms: hypercellular bone marrow | increased bone marrow cellularity | bone marrow hypercellularity | hyperplastic bone marrow |  increased bone marrow cell number
