### ISSUE TITLE
Synonym request for MP:0010047: axonal beading

### ISSUE THREAD

**Issue by LaurensWilming** [obophenotype/mammalian-phenotype-ontology#3325]
MP:0010047 axonal spheroids
Synonym: **axonal beading**

PMID:32330411

As far as I can tell beading and spheroids are the same.

Thanks,
Laurens

**Comment by anna-anagnostop** [comment]
NEW SYN: axonal beads
NEW SYN: axonal beading
NEW SYN: beaded axons
Additional source: PMID:31628183
