### ISSUE TITLE
New terms request: enlarged cauda epididymis + small cauda epididymis + small corpus epididymis 

### ISSUE THREAD

**Issue by LaurensWilming** [obophenotype/mammalian-phenotype-ontology#3326]
>1. Preferred term label

_enlarged cauda epididymis
small cauda epididymis
small corpus epididymis_ 

>2. Synonyms 

_increased cauda epididymis size | swollen cauda epididymis_ **<<< add similar synonym to** _enlarged caput epididymis_ **and** _enlarged corpus epididymis_ **and** _enlarged testis_
_decreased cauda epididymis size | reduced cauda
decreased corpus epididymis size | reduced corpus_

>3. Textual definition

_increase in the average size of the tail of the epididymis
decrease in the average size of the tail of the epididymis
decrease in the average size of the body of the epididymis_

>4. Any additional notes to clarify the meaning or use of the term. Please provide a PubMed ID or URL(s) for the source of this information.

**To bring it in line with existing _abnormal caput epididymis morphology_ children. PMID:31318116 describes enlarged cauda and corpus epididymis.**

>5. Suggested parent term 

_MP:0002662 abnormal cauda epididymis morphology
MP:0002662 abnormal cauda epididymis morphology
MP:0002661 abnormal corpus epididymis morphology_

**Comment by anna-anagnostop** [comment]
Added new terms:

enlarged cauda epididymis MP:0031209
small cauda epididymis MP:0031210
small corpus epididymis MP:0031211

Did not use the swollen synonym, as there is currently only one annotation to swollen proximal corpus and one annotation to swollen testes and we still need to clarify the usage of "distended" versus "dilated" and "swollen" in synonyms/EQs.
