### ISSUE TITLE
angiotensin II levels

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#3327]
Consider adding new terms for abnormal/decreased/increased angiotensin II level as well as abnormal/decreased/increased circulating angiotensin II level 

Related to COVID-19: plasma levels of Angiotensin II are increased in 2019-nCoV infected patients (see Liu Y, Yang Y, Zhang C, Huang F, Wang F, Yuan J, Wang Z, Li J,Li J, Feng C, Zhang Z, Wang L, Peng L, Chen L, Qin Y, Zhao D, TanS, Yin L, Xu J, Zhou C, Jiang C, Liu L.Clinical and biochemicalindexes from 2019-nCoV infected patients linked to viral loads and lung injury. Sci China Life Sci63: 364–374, 2020. doi:10.1007/s11427-020-1643-8).

**Comment by anna-anagnostop** [comment]
DEF: any anomaly in the concentration of angiotensin II, a vasoactive octapeptide produced by the action of angiotensin-converting enzyme on angiotensin I; angiotensin II is a potent vasoconstrictor that induces arteriolar constriction and increases blood pressure; it acts directly on the adrenal cortex, increasing aldosterone secretion, facilitating norepinephrine release by direct action on the post-ganglionic sympathetic neurons; it also acts on the brain, increasing water intake, vasopressin and ACTH secretion

**Comment by sbello** [comment]
https://www.uniprot.org/uniprot/P01019#PRO_0000032458

**Comment by anna-anagnostop** [comment]
USE:
DEF: any anomaly in the concentration of angiotensin II, a vasoactive octapeptide produced by the action of angiotensin-converting enzyme on angiotensin I; it acts directly on vascular smooth muscle as a potent vasoconstrictor, affects cardiac contractility and heart rate through its action on the sympathetic nervous system, and alters renal sodium and water absorption through its ability to stimulate the zona glomerulosa cells of the adrenal cortex to synthesize and secrete aldosterone.
SOURCE: https://www.uniprot.org/uniprot/P01019#PRO_0000032458

**Comment by anna-anagnostop** [comment]
Added new terms:

abnormal angiotensin II level MP:0031227
decreased angiotensin II level MP:0031228
increased angiotensin II level MP:0031229

abnormal circulating angiotensin II level MP:0031230
decreased circulating angiotensin II level MP:0031231
increased circulating angiotensin II level MP:0031232
