### ISSUE TITLE
Synonym request for MP:0010931 and children: trabecular number

### ISSUE THREAD

**Issue by LaurensWilming** [obophenotype/mammalian-phenotype-ontology#3334]
MP:0010931 abnormal trabecular bone connectivity density
synonym: _abnormal trabecular number_
MP:0010933 decreased trabecular bone connectivity density
synonym: _decreased trabecular number_
MP:0010932 increased trabecular bone connectivity density
synonym: _increased trabecular number_

PMID:32569872

**Comment by anna-anagnostop** [comment]
Looking at the phenotype in Fig. 4A (PMID:32569872) I would have annotated decreased trabecular number to existing term "decreased bone trabecula number" MP:0010869, NOT to abnormal trabecular bone connectivity density MP:0010931 as this term refers to an anomaly in the extent of attachments between trabeculae, not trabecular number (these terms are thus not synonymous)

Note: Also based on Fig. 4A, I would have annotated (i) observed decrease in bone volume of trabecular bone/tissue volume to "decreased trabecular bone volume" MP:0010879 (NOT to decreased bone volume MP:0010876) and (ii) increased trabecular separation to "increased bone trabecular spacing" MP:0013630

**Comment by anna-anagnostop** [comment]
Closed this issue as abnormal trabecular number is NOT a correct synonym for abnormal trabecular bone connectivity density (MP:0010931).
