### ISSUE TITLE
altered versus abnormal susceptibility or response terms

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#3339]
The MP currently uses both "altered" and "abnormal" in the primary term label of various existing susceptibility/response/tumor related etc terms

Examples using "altered":

altered response to CNS ischemic injury MP:0003075 
altered response of heart to induced stress MP:0004484 
altered tumor pathology MP:0010639 
altered tumor susceptibility MP:0002166 
altered metastatic potential MP:0000858 
altered susceptibility to infection MP:0001793 
altered position of colliculi MP:0000901 

Examples using "abnormal":

abnormal susceptibility to weight gain MP:0011117 
abnormal susceptibility to induced colitis MP:0013296 
abnormal susceptibility to aortic cartilaginous metaplasia MP:0020092 
abnormal response to vitamins MP:0003639 
abnormal response to infection MP:0005025 
abnormal physiological response to xenobiotic MP:0008872 

Consider standardizing using only "abnormal" in the primary term label, making "altered" an exact synonym???

**Comment by sbello** [comment]
Should be consistent and use abnormal make altered an exact synonym

**Comment by anna-anagnostop** [comment]
Primary term label has been changed to "abnormal".
Added "altered" as an exact synonym only to those terms that previously used "altered" in the term label.
