### ISSUE TITLE
abnormal C-X-C motif chemokine ligand 10 level 

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#3342]
Need new term:

abnormal CXCL10 level (a child of abnormal chemokine level MP:0008721)
DEF: deviation from the normal levels of this pro-inflammatory cytokine that is secreted by a wide range of cell types (including monocytes, neutrophils, endothelial cells and fibroblasts) in response to interferon-gamma, and produces its effects by binding to the cell surface chemokine receptor CXCR3; CXCL10 is a chemoattractant for monocytes/macrophages, T cells, dendritic cells, and NK cells; promotes T cell adhesion to endothelial cells; is a mitogenic and chemotactic factor for vascular smooth muscle cells; and plays roles in antitumor activity, bone marrow colony formation, and angiogenesis
SYN: abnormal C-X-C motif chemokine ligand 10 level 
SYN: abnormal IFN gamma-inducible protein 10 level
SYN: abnormal interferon gamma-induced protein 10 level
SYN: abnormal gamma-IP10 level
SYN: abnormal small-inducible cytokine B10 level
SYN: abnormal IP-10 level
SYN: abnormal IP10 level
SOURCE: PMID:24642726,  https://www.prospecbio.com/ip-10

Also, create:

- increased/decreased child terms of abnormal CXCL10 level

- abnormal circulating CXCL10 level (a child of abnormal circulating chemokine level MP:0010209) and increased/decreased circulating child terms

- abnormal CXCL10 secretion (a child of abnormal chemokine secretion MP:0008722 ) and increased/decreased secretion child terms

NOTE: Alternative def of CXCL10 UPKB:P02778
DEF: pro-inflammatory cytokine  involved in a wide variety of processes such as chemotaxis, differentiation, and activation of peripheral immune cells, regulation of cell growth, apoptosis and modulation of angiostatic effects; it plays an important role during viral infections by stimulating the activation and migration of immune cells to the infected sites
SOURCE: https://www.uniprot.org/uniprot/P02778, UniProtKB - P02778 (CXL10_HUMAN)

**Comment by sbello** [comment]
alt def: deviation from the normal levels of this pro-inflammatory cytokine that is secreted by a wide range of cell types  in response to interferon-gamma, and produces its effects by binding to the cell surface chemokine receptor CXCR3

**Comment by anna-anagnostop** [comment]
Added new terms:

abnormal CXCL10 level MP:0031224
decreased CXCL10 level MP:0031225
increased CXCL10 level MP:0031226

abnormal circulating CXCL10 level MP:0031218
decreased circulating CXCL10 level MP:0031219
increased circulating CXCL10 level MP:0031220

abnormal CXCL10 secretion MP:0031221
decreased CXCL10 secretion MP:0031222
increased CXCL10 secretion MP:0031223
