### ISSUE TITLE
Vision/eye MP terms fix

### ISSUE THREAD

**Issue by abby-jonesKOMP** [obophenotype/mammalian-phenotype-ontology#3348]
Could you please add hyphens to the following MP terms:

abnormal a-wave shape (MP:0012034)
abnormal a-wave amplitude (MP:0012030)
decreased a-wave amplitude (MP:0012143)
increased a-wave amplitude (MP:0012145)
abnormal b-wave amplitude (MP:0012031)
decreased b-wave amplitude (MP:0012144)
increased b-wave amplitude (MP:0012146)
abnormal c-wave shape (MP:0012040)
abnormal a-wave implicit time (MP:0012038)
decreased a-wave implicit time (MP:0012148)
increased a-wave implicit time (MP:0012147)
abnormal b-wave implicit time (MP:0012039)
decreased b-wave implicit time (MP:0012149)
increased b-wave implicit time (MP:0012150)
abnormal a-wave latency (MP:0012036)
decreased a-wave latency (MP:0012152)
increased a-wave latency (MP:0012151)
abnormal b-wave latency (MP:0012037)
decreased b-wave latency (MP:0012154)
increased b-wave latency (MP:0012153)
absent b-wave (MP:0020439)

**Comment by sbello** [comment]
fixed in labels, definitions and synonyms
