### ISSUE TITLE
diffuse alveolar damage

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#3354]
Consider adding new term:

diffuse alveolar damage

see HPO term Diffuse alveolar damage HP:0033006 and discussion in https://github.com/obophenotype/human-phenotype-ontology/issues/5626

MODIFIED HPO DEF: a common histological injury pattern of the lung, whereby the early stages are characterized by epithelial cell necrosis and sloughing, fibrous exudate, edema, and hyaline membranes made of surfactant and proteins, filling the alveoli and resulting in impaired gas exchange; in later stages, type II cells and myofibroblasts proliferate within the interstitium and airspaces; the corresponding clinical entity is ARDS (acute respiratory distress syndrome)

See also https://www.atsjournals.org/doi/full/10.1513/AnnalsATS.201609-728PS (PMID: 28570160)

Related to COVID-19 lung pathology

Annotations to genotypes MGI:6401000, MGI:3771372, MGI:6402832, MGI:6402445

**Comment by sbello** [comment]
possibly abnormal response to lung injury?

**Comment by anna-anagnostop** [comment]
Let's place it under abnormal pulmonary alveolar system morphology (replicate HPO placement)

**Comment by anna-anagnostop** [comment]
Added diffuse alveolar damage MP:0031237
