### ISSUE TITLE
Synonym request: vascular leakage 

### ISSUE THREAD

**Issue by LaurensWilming** [obophenotype/mammalian-phenotype-ontology#3355]
>2. Synonyms
 for MP:0003070 increased vascular permeability
**vascular leakage** 

>4. Any additional notes to clarify the meaning or use of the term. 
**PMID:32668247**

**Comment by sbello** [comment]
Does increased permeability always = leakage? Possibly this should be a narrow synonym or a new child?

**Comment by anna-anagnostop** [comment]
Check current MP annotations to increased vascular permeability MP:0003070 
[increased vascular permeability.txt](https://github.com/obophenotype/mammalian-phenotype-ontology/files/6061697/increased.vascular.permeability.txt)
; many refer to vascular leakage.

Note: HPO term Capillary leak HP:0030005 uses Increased capillary permeability as an exact synonym see HPO ticket [#309](https://github.com/obophenotype/human-phenotype-ontology/issues/309) (closed)

**Comment by anna-anagnostop** [comment]
Add as an exact synonym

**Comment by anna-anagnostop** [comment]
Done!
