### ISSUE TITLE
abnormal weight terms - duplicated EQ 

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#3372]
Related to #3359

Currently, ALL abnormal X weight terms appear to have a duplicated EQ in Protege.

**Comment by sbello** [comment]
@matentzn Might this be a glitch in the build using patterns?

**Comment by sbello** [comment]
Screenshot
![double_eq](https://user-images.githubusercontent.com/10979793/110344215-44a33e80-7ffb-11eb-86f1-5da44029b850.png)

**Comment by sbello** [comment]
Also see duplicated EQ for:
tooth abscess

Do not see duplicates for (one example for each pattern currently in use):
abnormal intestinal secretion
abnormal Meibomian gland physiology
abnormal Bowman membrane
brachypodia
decreased amygdala size
Meibomian gland atrophy
oral mucosa blisters
