### ISSUE TITLE
Increased tumor incidence terms

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#363]
1\.  What's the difference between our terms hepatoma and increased susceptibility to hepatoma?  These terms seem to reflect the same thing \(i.e. an increased incidence of hepatoma\).

2\.  We have many specific tumor types that are not listed as children of more general tumor types:
-adrenal gland adenoma \[MP:0009044\] is not a child of adrenal tumor
-skin hamartoma \[MP:0009469\]  is not a child of skin tumor
-hepatic hemangioma \[MP:0002047\] is not a child of liver tumor while retinal hemangioma is a child of retinal tumor
-medulloblastoma \[MP:0006283\] is not a child of brain tumor

3\.  We have specific organ tumors without parents for the general tumor type:
-no renal tumor even though we have several types or renal tumors

4\.  Some tumor types we do not list:
-mesothelioma \(3 associated alleles I will be adding 10 more using various combinations of 3 alleles not already associated with this tumor type\)
-schwannoma \(2 plus 5 more genotypes entered earlier today and more to come\)
-meningioma \(4 plus\)
-osteomas \(10 plus\)
-lymphosarcoma \(4 plus\)
-neurofibroma \(18 plus\)
-cholangiocarcinoma \(2 plus\)
-odontosarcoma \(just added alleles with this term in the genotype\)
-odontoma \(just added alleles with this term in the genotype\)

This terms might not all be needed but are suggestions.
Michelle

Reported by: michknow

Original Ticket: [obo/mammalian-phenotype-requests/363](https://sourceforge.net/p/obo/mammalian-phenotype-requests/363)

**Comment by cindyJax** [comment]
Section was previously reorganized.
