### ISSUE TITLE
cholesterol composition

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#411]
Please consider adding the terms:

abnormal cholesterol composition
def - any alteration in the chemical make up of cholesterol, the principal sterol of vertebrates and the precursor of many steroids
child of abnormal cholesterol homeostasis

abnormal HDL cholesterol composition
def - any alteration in the chemical make up of the small lipoprotein:cholesterol complex that transports cholesterol out of the arteries and to the liver for reprocessing or excretion 
child of abnormal cholesterol composition

abnormal LDL cholesterol composition
def - any alteration in the chemical make up of  the lipoprotein:cholesterol complex that transports cholesterol out of the arteries and around the body, for use by various tissues in normal bodily functions 
child of abnormal cholesterol composition

abnormal VLDL cholesterol composition
def - any alteration in the chemical make up of  the lipoprotein:cholesterol complex that transports triglycerides from the intestine and liver to muscle and adipose tissue 
child of abnormal cholesterol composition

Thanks,
Sue

Reported by: sbello

Original Ticket: [obo/mammalian-phenotype-requests/411](https://sourceforge.net/p/obo/mammalian-phenotype-requests/411)

**Comment by cindyJax** [comment]
Completed.
