### ISSUE TITLE
circadian terms

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#449]
Currently all of the circadian terms we have are under behavior however circadian patterns are seen in no behavioral areas ( for example glucose and lipid homeostasis in J:131694). Perhaps we should obsolete the current terms and create new terms specific to behavior (under behavior) and physiology (under homeostasis), similar to what you did for the response terms.
Thanks,
Sue

Reported by: sbello

Original Ticket: [obo/mammalian-phenotype-requests/449](https://sourceforge.net/p/obo/mammalian-phenotype-requests/449)

**Comment by sbello** [comment]
Where to place non-behavior circadian terms? GO has circadian rhythm as a child of biological process. If we want to be able to have all circadian terms under one parent, do we need a new high level MP term? I don't think we can put these under homeostasis/metabolism as GO does not put circadian terms under homeostasis and they don't fit under metabolism really. We could place specific terms like 'abnormal circadian regulation of heart rate' under the appropriate parent but we would not be able to collect all these terms under a single parent.

**Comment by sbello** [comment]
examples genotypes:
MGI:5562895 - abnormality in expression of circadian genes

Questionable terms for placement under behavior:
abnormal circadian regulation of heart rate (MP:0011021)
abnormal circadian regulation of systemic arterial blood pressure (MP:0011022)
abnormal circadian temperature homeostasis (MP:0011020)

**Comment by sbello** [comment]
Decision, obsolete the existing circadian rhythm term, create a new abnormal circadian behavior term and move non-behavior terms to other parents

**Comment by sbello** [comment]
created circadian behavior terms for each of the generic circadian rhythm terms

**Comment by sbello** [comment]
J:227078 - corneal photoentrainment
J:41859, J:135186 - SCN firing - moved to neuron physiology
J:101977 - neural entrainment
J:193286 - fibroblast proliferation and liver gene expression
j:223990, J:194037, J:121578 - SCN - moved to hypothalamus physiology
J:194037 - fibroblasts
J:224319 - liver
J:164451, J:93213 - food intake
