### ISSUE TITLE
abnroaml physiological response to restraint

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#450]
Please consider adding the term
abnormal physiological response to restraint
def - any anomaly in the physiological or morphological changes induced by close physical confinement
child of homeostasis/metabolism phenotype
Searching for restraint brings back 49 alleles many of which mention hormone responses to restraint. The paper \(J:125921\) I'm working on looks at circadian variations in restraint induced changes in blood pressure and adrenaline level.
Thanks,
Sue

Reported by: sbello

Original Ticket: [obo/mammalian-phenotype-requests/450](https://sourceforge.net/p/obo/mammalian-phenotype-requests/450)

**Comment by cindyJax** [comment]
Not added.
