### ISSUE TITLE
related  to blood coagulation 

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#456]
request for new child of   abnormal blood coagulation \[MP:0002551\]

altered susceptibility to warfarin

def. a change in the likelihood that an organism will respond to this substance that normally reduces the formation of blood clots by blocking the formation of certain clotting factors

Reported by: llw2

Original Ticket: [obo/mammalian-phenotype-requests/456](https://sourceforge.net/p/obo/mammalian-phenotype-requests/456)

**Comment by cindyJax** [comment]
Not added - There are better ways of dealing with stressors and conditions than creating a term for each one.
