### ISSUE TITLE
split leukocyte rolling and leukocyte adhesion 

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#471]
Please consider splitting the terms abnormal leukocyte rolling \(MP:0003627\) and abnormal leukocyte adhesion \(MP:0003628\) into increased and decreased children. 

We should also add a term for abnormal leukocyte rolling velocity as 28 existing annotations describe this phenotype. We should probably also obsolete the current leukocyte rolling term as this term specifies number of leukocytes rolling or else change the current term to abnormal number of rolling leukocytes and add a new term of abnormal leukocyte rolling to cover both number and velocity. \(Only 11 of the current annotations mention number\)

Thanks,
Sue

Reported by: sbello

Original Ticket: [obo/mammalian-phenotype-requests/471](https://sourceforge.net/p/obo/mammalian-phenotype-requests/471)

**Comment by sbello** [comment]
MP:0020332 impaired
MP:0020333 enhanced
