### ISSUE TITLE
induced joint inflammation

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#486]
review placement of induced arthritis terms - also belongs under "arthritis"?  or just move?

review induced joint inflammation term - is this needed?

check joint inflammation terms for induced arthritis annotations

Reported by: cindyJax

Original Ticket: [obo/mammalian-phenotype-requests/486](https://sourceforge.net/p/obo/mammalian-phenotype-requests/486)

**Comment by cindyJax** [comment]
Done
