### ISSUE TITLE
sucrose preference

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#531]
perhaps you could add an abnormal sucrose preference to the abnormal liquid preference \[MP:0001423\] parent. J:155739 has a mutant that would be applicable and there are 4 with sucrose in the notes field for this MP.

Reported by: jbubier

Original Ticket: [obo/mammalian-phenotype-requests/531](https://sourceforge.net/p/obo/mammalian-phenotype-requests/531)

**Comment by sbello** [comment]
MP:0020379 - abnormal sucrose solution preference
