### ISSUE TITLE
Tooth morphology

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#541]
J:102001 describes defects in the periodontal junctional epithelium.  As I understand it, the JE is a specialized epithelium that attaches to the mineralized surface of the tooth.  See http://en.wikipedia.org/wiki/Junctional\_epithelium and intro of paper.  The MP term abnormal tooth morphology [MP:0002100] is defined as "atypical size, shape or hard tissue structure of the teeth."  However, we have anothr term for the hard tissues of the tooth and children of abnormal tooth morphology include soft tissues.  

Please re-examine the definition and see if periodontal junctional epithelium can be included.  For not I've put the annotations under abnormal tooth morphology.

Reported by: michknow

Original Ticket: [obo/mammalian-phenotype-requests/541](https://sourceforge.net/p/obo/mammalian-phenotype-requests/541)

**Comment by sbello** [comment]
updated the definition of tooth to clarify that this includes both soft and hard tissue
added terms for gum  and gum epithelium morphology as this is where the junctional epithelium phenotypes should go (MP:0020459, MP:0020460)
