### ISSUE TITLE
primary palate

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#573]
We have a term for primary palate development, but terms for morphology and absence could be added as well as cleft primary palate \(how does this relate to cleft lip?\).  Also consider abnormal fusion to secondary palate and abnormal fusion to nasal prominence.

Reported by: cindyJax

Original Ticket: [obo/mammalian-phenotype-requests/573](https://sourceforge.net/p/obo/mammalian-phenotype-requests/573)

**Comment by cindyJax** [comment]
This was done.
