### ISSUE TITLE
digestive system physiology depth

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#586]
H Cindy,
I put some specifics about proliferation within the large intestine crypts of Lieberkuhn at the high term abnormal digestive system physiology MP:0001663. This was for J157019. I noticed other proliferation/apoptosis phenotypes stuck in under the morphology terms \(like MP:0004842 abnormal large intestine crypts of Lieberkuhn morphology\) where there is some granularity, like J:115873. Perhaps we need some physiology terms at that same depth? 

Reported by: jbubier

Original Ticket: [obo/mammalian-phenotype-requests/586](https://sourceforge.net/p/obo/mammalian-phenotype-requests/586)

**Comment by cindyJax** [comment]
This was completed.
