### ISSUE TITLE
addictive substance

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#636]
What is required for the substance to be considered an addictive substance vs a xenobiotic? A chemical of abuse \(in humans?\) ,Induces drug seeking behavior? Do we just mean narcotics or do we include stimulants, and sedatives, anything psychoactive? Wikipedia defines an addiction as "a chronic neurobiological disorder that has genetic, psychosocial, and environmental dimensions and is characterized by one of the following: the continued use of a substance despite its detrimental effects, impaired control over the use of a drug \(compulsive behavior\), and preoccupation with a drug's use for non-therapeutic purposes \(i.e. craving the drug\)."

Reported by: jbubier

Original Ticket: [obo/mammalian-phenotype-requests/636](https://sourceforge.net/p/obo/mammalian-phenotype-requests/636)

**Comment by sbello** [comment]
I've clarified the definition of 'xenobiotic' to make it clear this is a substance foreign to any living organism. Many addictive substances are of biological origin and so would not be xenobiotics. Some substances may be both addictive and xenobiotics and these should be double annotated.
