### ISSUE TITLE
galactolipid

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#677]
Would be better to do galactolipid.  They assessed cerebrosides and sulfatides which I’d put under galactolipids, no?.  \(Note was to remind myself what I put where and why.\)

Galactolipids are not limited to myelin...

but I could add galactocerebroside \(GalC\) which is myelin-specific?

Melissa Berry wrote:
&gt; Abnormal galactolipid level
&gt; This is cerebrosides and sulfatides and they are part of myelin.
&gt;
&gt; Note to self: J:5170, I put it under abnormal myelin.

Reported by: *anonymous

Original Ticket: [obo/mammalian-phenotype-requests/677](https://sourceforge.net/p/obo/mammalian-phenotype-requests/677)

**Comment by sbello** [comment]
According to https://en.wikipedia.org/wiki/Galactocerebroside galactocerebroside is  oligodendrocyte specific not myelin specific

**Comment by sbello** [comment]
MP:0020380 abnormal galatolipid level
