### ISSUE TITLE
melanophages

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#694]
Melanophages are macrophages which have ingested \(endocytosis\) melanosomes or melanin. \(Weiss et al, 1988; James et al, 1987; Cooper et al, 1986\) . This term is used in paper J:160072 and allele Nfkbiz&lt;tm1Mamo&gt;. Where would it go? Under abnormal macrophage morphology \[MP:0002446\] where osteoclasts Kupffer cells are?

Reported by: jbubier

Original Ticket: [obo/mammalian-phenotype-requests/694](https://sourceforge.net/p/obo/mammalian-phenotype-requests/694)

**Comment by sbello** [comment]
MP:0020334
