### ISSUE TITLE
hypothalamus subterms

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#771]
Add and reorganize hypothalamus subterms; see MA and consult Terry H to see if current MP terms are synonymous with current MA terms.

Reported by: cindyJax

Original Ticket: [obo/mammalian-phenotype-requests/771](https://sourceforge.net/p/obo/mammalian-phenotype-requests/771)

**Comment by cindyJax** [comment]
Done
