### ISSUE TITLE
abnormal Purkinje cell dendrite morphology

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#780]
Please consider making abnormal Purkinje cell dendrite morphology \(MP:0008572\) a child of  abnormal dendrite morphology \(MP:0008143\).
Thanks,
Sue

Reported by: sbello

Original Ticket: [obo/mammalian-phenotype-requests/780](https://sourceforge.net/p/obo/mammalian-phenotype-requests/780)

**Comment by sbello** [comment]
MP:0020335 - dentate gyrus

**Comment by sbello** [comment]
MP:0020336 - motor neuron

**Comment by sbello** [comment]
MP:0020337 - pyramidal neuron
MP:0020338 - hippocampal pyramidal neuron

**Comment by sbello** [comment]
MP:0020339 - retinal ganglion cell
