### ISSUE TITLE
abnormal vertical behavior

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#787]
Please consider adding the term
abnormal vertical behavior
def - any anomaly in the types or amount of activity thast occurs along the vertical axis
In J:102926 mice show a decreased incidence of rearing and an increased incidence of jumping in an open field which doesn't fit well with either increased or decreased vertical activity. For now I have placed this under abnormal locomotor activation.
Thanks,
Sue

Reported by: sbello

Original Ticket: [obo/mammalian-phenotype-requests/787](https://sourceforge.net/p/obo/mammalian-phenotype-requests/787)

**Comment by cindyJax** [comment]
No other examples.
