### ISSUE TITLE
RE spleen function

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#836]
new child of  abnormal splenocyte proliferation \[MP:0009334\]

reduced hyperplastic response   def: a decreased capacity to respond to anemia inducing agents such as phenylhydrazine by increasing proliferation of  erythropoietic progenitor and precursor cells 

Reported by: llw2

Original Ticket: [obo/mammalian-phenotype-requests/836](https://sourceforge.net/p/obo/mammalian-phenotype-requests/836)

**Comment by cindyJax** [comment]
Decided not to create a term for response to this specific situation
