### ISSUE TITLE
Organization of proliferation terms

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#842]
I'm a little confused about the placement of specific cell proliferation terms. In general, proliferation terms are under physiology trees. However, proliferation terms in regards to development fall under morphology \(abnormal neuronal precursor proliferation \[MP:0004948\]\). This seems to be a conflict.

Reported by: michknow

Original Ticket: [obo/mammalian-phenotype-requests/842](https://sourceforge.net/p/obo/mammalian-phenotype-requests/842)

**Comment by cindyJax** [comment]
long standing problem described elsewhere.
