### ISSUE TITLE
RE hemoglobin 

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#974]
new child for  abnormal hemoglobin \[MP:0001588\]

abnormal heme-heme interaction
def small alterations occur in the three-dimensional structure of iron-protoporphyrin complexes change binding affinity during oxygenation of red blood cells

Reported by: llw2

Original Ticket: [obo/mammalian-phenotype-requests/974](https://sourceforge.net/p/obo/mammalian-phenotype-requests/974)

**Comment by cindyJax** [comment]
Not appropriate for MP
