### ISSUE TITLE
postnatal lethality

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/mammalian-phenotype-ontology#993]
we have postnatal  lethality covering before and by weaning
could we expand definition to the next developmental benchmark after weaning, sexual maturity

postnatal lethality \[MP:0002082\]
current def : premature death anytime between the neonatal period and weaning age \(Mus: P1 to approximately 3 weeks of age\)

requested def:  premature death anytime between the neonatal period and sexual maturity \(Mus: P1 to approximately 5-8 weeks of age\)
note: 5-8 weeks covers precocious strains -  the bulk that breed between 6 and 7 weeks of age -and wild mice that often reproduce "later"

Reported by: llw2

Original Ticket: [obo/mammalian-phenotype-requests/993](https://sourceforge.net/p/obo/mammalian-phenotype-requests/993)

**Comment by cindyJax** [comment]
No more staging terms for lethality.  There are better ways of dealing with this.
